
# This file is automatically generated, you probably don't want to edit this

artOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "artOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mode = "cross_sectional",
            dep_var_cs = NULL,
            fixed_factors_cs = NULL,
            long_format = "wide",
            dep_var_long = NULL,
            fixed_factors_long = NULL,
            subject_id_var = NULL,
            time_var = NULL,
            wave_vars = NULL,
            run_posthoc = FALSE,
            posthoc_correction = "holm",
            calc_es = FALSE,
            es_method = "cohens_d",
            run_analysis = FALSE, ...) {

            super$initialize(
                package="BSS",
                name="art",
                requiresData=TRUE,
                ...)

            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "cross_sectional",
                    "longitudinal"),
                default="cross_sectional")
            private$..dep_var_cs <- jmvcore::OptionVariable$new(
                "dep_var_cs",
                dep_var_cs,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..fixed_factors_cs <- jmvcore::OptionVariables$new(
                "fixed_factors_cs",
                fixed_factors_cs,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..long_format <- jmvcore::OptionList$new(
                "long_format",
                long_format,
                options=list(
                    "wide",
                    "long"),
                default="wide")
            private$..dep_var_long <- jmvcore::OptionVariable$new(
                "dep_var_long",
                dep_var_long,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..fixed_factors_long <- jmvcore::OptionVariables$new(
                "fixed_factors_long",
                fixed_factors_long,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..subject_id_var <- jmvcore::OptionVariable$new(
                "subject_id_var",
                subject_id_var,
                suggested=list(
                    "nominal",
                    "id"),
                permitted=list(
                    "factor",
                    "numeric",
                    "id"))
            private$..time_var <- jmvcore::OptionVariable$new(
                "time_var",
                time_var,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..wave_vars <- jmvcore::OptionVariables$new(
                "wave_vars",
                wave_vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..run_posthoc <- jmvcore::OptionBool$new(
                "run_posthoc",
                run_posthoc,
                default=FALSE)
            private$..posthoc_correction <- jmvcore::OptionList$new(
                "posthoc_correction",
                posthoc_correction,
                options=list(
                    "holm",
                    "bonferroni",
                    "tukey",
                    "none"),
                default="holm")
            private$..calc_es <- jmvcore::OptionBool$new(
                "calc_es",
                calc_es,
                default=FALSE)
            private$..es_method <- jmvcore::OptionList$new(
                "es_method",
                es_method,
                options=list(
                    "cohens_d",
                    "hedges_g"),
                default="cohens_d")
            private$..run_analysis <- jmvcore::OptionBool$new(
                "run_analysis",
                run_analysis,
                default=FALSE)

            self$.addOption(private$..mode)
            self$.addOption(private$..dep_var_cs)
            self$.addOption(private$..fixed_factors_cs)
            self$.addOption(private$..long_format)
            self$.addOption(private$..dep_var_long)
            self$.addOption(private$..fixed_factors_long)
            self$.addOption(private$..subject_id_var)
            self$.addOption(private$..time_var)
            self$.addOption(private$..wave_vars)
            self$.addOption(private$..run_posthoc)
            self$.addOption(private$..posthoc_correction)
            self$.addOption(private$..calc_es)
            self$.addOption(private$..es_method)
            self$.addOption(private$..run_analysis)
        }),
    active = list(
        mode = function() private$..mode$value,
        dep_var_cs = function() private$..dep_var_cs$value,
        fixed_factors_cs = function() private$..fixed_factors_cs$value,
        long_format = function() private$..long_format$value,
        dep_var_long = function() private$..dep_var_long$value,
        fixed_factors_long = function() private$..fixed_factors_long$value,
        subject_id_var = function() private$..subject_id_var$value,
        time_var = function() private$..time_var$value,
        wave_vars = function() private$..wave_vars$value,
        run_posthoc = function() private$..run_posthoc$value,
        posthoc_correction = function() private$..posthoc_correction$value,
        calc_es = function() private$..calc_es$value,
        es_method = function() private$..es_method$value,
        run_analysis = function() private$..run_analysis$value),
    private = list(
        ..mode = NA,
        ..dep_var_cs = NA,
        ..fixed_factors_cs = NA,
        ..long_format = NA,
        ..dep_var_long = NA,
        ..fixed_factors_long = NA,
        ..subject_id_var = NA,
        ..time_var = NA,
        ..wave_vars = NA,
        ..run_posthoc = NA,
        ..posthoc_correction = NA,
        ..calc_es = NA,
        ..es_method = NA,
        ..run_analysis = NA)
)

artResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "artResults",
    inherit = jmvcore::Group,
    active = list(
        analysisInfo = function() private$.items[["analysisInfo"]],
        anovaTable = function() private$.items[["anovaTable"]],
        posthocTable = function() private$.items[["posthocTable"]],
        effectSizeTable = function() private$.items[["effectSizeTable"]],
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Aligned Rank Transform (ART)")
            self$add(jmvcore::Html$new(
                options=options,
                name="analysisInfo",
                title="About ART Analysis",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="anovaTable",
                title="Nonparametric ANOVA Results (Aligned Rank Transform)",
                visible="(run_analysis)",
                refs=list(
                    "ARTool"),
                clearWith=list(
                    "mode",
                    "dep_var_cs",
                    "fixed_factors_cs",
                    "dep_var_long",
                    "fixed_factors_long",
                    "long_format",
                    "subject_id_var",
                    "time_var",
                    "wave_vars",
                    "run_analysis"),
                columns=list(
                    list(
                        `name`="factor", 
                        `title`="Term", 
                        `type`="text"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="number", 
                        `format`="dp:0"),
                    list(
                        `name`="df_res", 
                        `title`="df.res", 
                        `type`="number", 
                        `format`="dp:2"),
                    list(
                        `name`="f_value", 
                        `title`="F", 
                        `type`="number", 
                        `format`="dp:3"),
                    list(
                        `name`="p_value", 
                        `title`="p", 
                        `type`="number", 
                        `format`="pvalue"),
                    list(
                        `name`="part_eta_sq", 
                        `title`="Partial \u03B7\u00B2", 
                        `type`="number", 
                        `format`="dp:3"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="posthocTable",
                title="Pairwise Post-Hoc Tests (art.con)",
                visible="(run_analysis && run_posthoc)",
                refs=list(
                    "ARTool",
                    "emmeans"),
                clearWith=list(
                    "mode",
                    "dep_var_cs",
                    "fixed_factors_cs",
                    "dep_var_long",
                    "fixed_factors_long",
                    "long_format",
                    "subject_id_var",
                    "time_var",
                    "wave_vars",
                    "run_posthoc",
                    "posthoc_correction",
                    "run_analysis"),
                columns=list(
                    list(
                        `name`="factor", 
                        `title`="Factor / Interaction", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="contrast", 
                        `title`="Contrast", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number", 
                        `format`="dp:3"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `format`="dp:3"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="number", 
                        `format`="dp:2"),
                    list(
                        `name`="t_ratio", 
                        `title`="t", 
                        `type`="number", 
                        `format`="dp:3"),
                    list(
                        `name`="p_value", 
                        `title`="p", 
                        `type`="number", 
                        `format`="pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="effectSizeTable",
                title="Pairwise Effect Sizes",
                visible="(run_analysis && run_posthoc && calc_es)",
                refs=list(
                    "ARTool",
                    "emmeans"),
                clearWith=list(
                    "mode",
                    "dep_var_cs",
                    "fixed_factors_cs",
                    "dep_var_long",
                    "fixed_factors_long",
                    "long_format",
                    "subject_id_var",
                    "time_var",
                    "wave_vars",
                    "run_posthoc",
                    "calc_es",
                    "es_method",
                    "run_analysis"),
                columns=list(
                    list(
                        `name`="factor", 
                        `title`="Factor / Interaction", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="contrast", 
                        `title`="Contrast", 
                        `type`="text"),
                    list(
                        `name`="method", 
                        `title`="Method", 
                        `type`="text"),
                    list(
                        `name`="es_value", 
                        `title`="Effect Size", 
                        `type`="number", 
                        `format`="dp:3"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Analysis Summary",
                visible=FALSE,
                clearWith=list(
                    "mode",
                    "dep_var_cs",
                    "fixed_factors_cs",
                    "dep_var_long",
                    "fixed_factors_long",
                    "long_format",
                    "subject_id_var",
                    "time_var",
                    "wave_vars",
                    "run_analysis")))}))

artBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "artBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BSS",
                name = "art",
                version = c(1,0,0),
                options = options,
                results = artResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Aligned Rank Transform (ART)
#'
#' 
#' @param data .
#' @param mode .
#' @param dep_var_cs .
#' @param fixed_factors_cs .
#' @param long_format .
#' @param dep_var_long .
#' @param fixed_factors_long .
#' @param subject_id_var .
#' @param time_var .
#' @param wave_vars .
#' @param run_posthoc .
#' @param posthoc_correction .
#' @param calc_es .
#' @param es_method .
#' @param run_analysis .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$analysisInfo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$anovaTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$posthocTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$effectSizeTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$anovaTable$asDF}
#'
#' \code{as.data.frame(results$anovaTable)}
#'
#' @export
art <- function(
    data,
    mode = "cross_sectional",
    dep_var_cs,
    fixed_factors_cs,
    long_format = "wide",
    dep_var_long,
    fixed_factors_long,
    subject_id_var,
    time_var,
    wave_vars,
    run_posthoc = FALSE,
    posthoc_correction = "holm",
    calc_es = FALSE,
    es_method = "cohens_d",
    run_analysis = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("art requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep_var_cs)) dep_var_cs <- jmvcore::resolveQuo(jmvcore::enquo(dep_var_cs))
    if ( ! missing(fixed_factors_cs)) fixed_factors_cs <- jmvcore::resolveQuo(jmvcore::enquo(fixed_factors_cs))
    if ( ! missing(dep_var_long)) dep_var_long <- jmvcore::resolveQuo(jmvcore::enquo(dep_var_long))
    if ( ! missing(fixed_factors_long)) fixed_factors_long <- jmvcore::resolveQuo(jmvcore::enquo(fixed_factors_long))
    if ( ! missing(subject_id_var)) subject_id_var <- jmvcore::resolveQuo(jmvcore::enquo(subject_id_var))
    if ( ! missing(time_var)) time_var <- jmvcore::resolveQuo(jmvcore::enquo(time_var))
    if ( ! missing(wave_vars)) wave_vars <- jmvcore::resolveQuo(jmvcore::enquo(wave_vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep_var_cs), dep_var_cs, NULL),
            `if`( ! missing(fixed_factors_cs), fixed_factors_cs, NULL),
            `if`( ! missing(dep_var_long), dep_var_long, NULL),
            `if`( ! missing(fixed_factors_long), fixed_factors_long, NULL),
            `if`( ! missing(subject_id_var), subject_id_var, NULL),
            `if`( ! missing(time_var), time_var, NULL),
            `if`( ! missing(wave_vars), wave_vars, NULL))


    options <- artOptions$new(
        mode = mode,
        dep_var_cs = dep_var_cs,
        fixed_factors_cs = fixed_factors_cs,
        long_format = long_format,
        dep_var_long = dep_var_long,
        fixed_factors_long = fixed_factors_long,
        subject_id_var = subject_id_var,
        time_var = time_var,
        wave_vars = wave_vars,
        run_posthoc = run_posthoc,
        posthoc_correction = posthoc_correction,
        calc_es = calc_es,
        es_method = es_method,
        run_analysis = run_analysis)

    analysis <- artClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

