
# This file is automatically generated, you probably don't want to edit this

DataPresentationOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "DataPresentationOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            analysisType = "cross_sectional",
            deps = NULL,
            group = NULL,
            rm_vars = NULL,
            group_long = NULL,
            cov = NULL,
            cov_long = NULL,
            plotType = "bar",
            intStyle = "legend",
            showLines = TRUE,
            errorType = "sd",
            ciWidth = 95,
            showPoints = FALSE,
            showTable = TRUE,
            tableFormat = "apa",
            tableTitle = "Table 1. Descriptive statistics by group",
            tableNote = "Note. M = mean; SD = standard deviation; SE = standard error; CI = confidence interval; N = sample size.",
            themePlot = "classic",
            colorPalette = "set1",
            color1 = "none",
            color2 = "none",
            color3 = "none",
            color4 = "none",
            color5 = "none",
            color6 = "none",
            color7 = "none",
            color8 = "none",
            titleText = "",
            subtitleText = "",
            xLabel = "",
            yLabel = "",
            xAngle = 0,
            legendPosition = "right",
            removeGap = FALSE,
            customYAxis = FALSE,
            yMin = 0,
            yMax = 100,
            yStep = 10,
            fontSizeTitle = 14,
            fontSizeSubtitle = 12,
            fontSizeAxis = 11,
            fontSizeAxisTitle = 12,
            fontSizeLegend = 10,
            lineWidth = 0.8,
            errorLineWidth = 0.8,
            axisLineWidth = 0.8,
            barWidth = 0.7,
            barAlpha = 1,
            pointSize = 2,
            pointAlpha = 0.5, ...) {

            super$initialize(
                package="BSS",
                name="DataPresentation",
                requiresData=TRUE,
                ...)

            private$..analysisType <- jmvcore::OptionList$new(
                "analysisType",
                analysisType,
                options=list(
                    "cross_sectional",
                    "longitudinal"),
                default="cross_sectional")
            private$..deps <- jmvcore::OptionVariables$new(
                "deps",
                deps,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariables$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..rm_vars <- jmvcore::OptionVariables$new(
                "rm_vars",
                rm_vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group_long <- jmvcore::OptionVariables$new(
                "group_long",
                group_long,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..cov <- jmvcore::OptionVariable$new(
                "cov",
                cov,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..cov_long <- jmvcore::OptionVariable$new(
                "cov_long",
                cov_long,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..plotType <- jmvcore::OptionList$new(
                "plotType",
                plotType,
                options=list(
                    "bar",
                    "boxplot",
                    "meandp"),
                default="bar")
            private$..intStyle <- jmvcore::OptionList$new(
                "intStyle",
                intStyle,
                options=list(
                    "legend",
                    "x_axis"),
                default="legend")
            private$..showLines <- jmvcore::OptionBool$new(
                "showLines",
                showLines,
                default=TRUE)
            private$..errorType <- jmvcore::OptionList$new(
                "errorType",
                errorType,
                options=list(
                    "sd",
                    "se",
                    "ci"),
                default="sd")
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..showPoints <- jmvcore::OptionBool$new(
                "showPoints",
                showPoints,
                default=FALSE)
            private$..showTable <- jmvcore::OptionBool$new(
                "showTable",
                showTable,
                default=TRUE)
            private$..tableFormat <- jmvcore::OptionList$new(
                "tableFormat",
                tableFormat,
                options=list(
                    "apa",
                    "abnt",
                    "vancouver",
                    "chicago"),
                default="apa")
            private$..tableTitle <- jmvcore::OptionString$new(
                "tableTitle",
                tableTitle,
                default="Table 1. Descriptive statistics by group")
            private$..tableNote <- jmvcore::OptionString$new(
                "tableNote",
                tableNote,
                default="Note. M = mean; SD = standard deviation; SE = standard error; CI = confidence interval; N = sample size.")
            private$..themePlot <- jmvcore::OptionList$new(
                "themePlot",
                themePlot,
                options=list(
                    "classic",
                    "minimal",
                    "bw",
                    "gray",
                    "light"),
                default="classic")
            private$..colorPalette <- jmvcore::OptionList$new(
                "colorPalette",
                colorPalette,
                options=list(
                    "set1",
                    "set2",
                    "set3",
                    "pastel1",
                    "pastel2",
                    "dark2",
                    "viridis",
                    "plasma",
                    "manual"),
                default="set1")
            private$..color1 <- jmvcore::OptionList$new(
                "color1",
                color1,
                options=list(
                    "none",
                    "#E41A1C",
                    "#377EB8",
                    "#4DAF4A",
                    "#984EA3",
                    "#FF7F00",
                    "#FFFF33",
                    "#A65628",
                    "#F781BF",
                    "#999999",
                    "#000000",
                    "#FFFFFF",
                    "#1B9E77",
                    "#D95F02",
                    "#7570B3",
                    "#E7298A",
                    "#66A61E",
                    "#E6AB02",
                    "#A6761D",
                    "#666666"),
                default="none")
            private$..color2 <- jmvcore::OptionList$new(
                "color2",
                color2,
                options=list(
                    "none",
                    "#E41A1C",
                    "#377EB8",
                    "#4DAF4A",
                    "#984EA3",
                    "#FF7F00",
                    "#FFFF33",
                    "#A65628",
                    "#F781BF",
                    "#999999",
                    "#000000",
                    "#FFFFFF",
                    "#1B9E77",
                    "#D95F02",
                    "#7570B3",
                    "#E7298A",
                    "#66A61E",
                    "#E6AB02",
                    "#A6761D",
                    "#666666"),
                default="none")
            private$..color3 <- jmvcore::OptionList$new(
                "color3",
                color3,
                options=list(
                    "none",
                    "#E41A1C",
                    "#377EB8",
                    "#4DAF4A",
                    "#984EA3",
                    "#FF7F00",
                    "#FFFF33",
                    "#A65628",
                    "#F781BF",
                    "#999999",
                    "#000000",
                    "#FFFFFF",
                    "#1B9E77",
                    "#D95F02",
                    "#7570B3",
                    "#E7298A",
                    "#66A61E",
                    "#E6AB02",
                    "#A6761D",
                    "#666666"),
                default="none")
            private$..color4 <- jmvcore::OptionList$new(
                "color4",
                color4,
                options=list(
                    "none",
                    "#E41A1C",
                    "#377EB8",
                    "#4DAF4A",
                    "#984EA3",
                    "#FF7F00",
                    "#FFFF33",
                    "#A65628",
                    "#F781BF",
                    "#999999",
                    "#000000",
                    "#FFFFFF",
                    "#1B9E77",
                    "#D95F02",
                    "#7570B3",
                    "#E7298A",
                    "#66A61E",
                    "#E6AB02",
                    "#A6761D",
                    "#666666"),
                default="none")
            private$..color5 <- jmvcore::OptionList$new(
                "color5",
                color5,
                options=list(
                    "none",
                    "#E41A1C",
                    "#377EB8",
                    "#4DAF4A",
                    "#984EA3",
                    "#FF7F00",
                    "#FFFF33",
                    "#A65628",
                    "#F781BF",
                    "#999999",
                    "#000000",
                    "#FFFFFF",
                    "#1B9E77",
                    "#D95F02",
                    "#7570B3",
                    "#E7298A",
                    "#66A61E",
                    "#E6AB02",
                    "#A6761D",
                    "#666666"),
                default="none")
            private$..color6 <- jmvcore::OptionList$new(
                "color6",
                color6,
                options=list(
                    "none",
                    "#E41A1C",
                    "#377EB8",
                    "#4DAF4A",
                    "#984EA3",
                    "#FF7F00",
                    "#FFFF33",
                    "#A65628",
                    "#F781BF",
                    "#999999",
                    "#000000",
                    "#FFFFFF",
                    "#1B9E77",
                    "#D95F02",
                    "#7570B3",
                    "#E7298A",
                    "#66A61E",
                    "#E6AB02",
                    "#A6761D",
                    "#666666"),
                default="none")
            private$..color7 <- jmvcore::OptionList$new(
                "color7",
                color7,
                options=list(
                    "none",
                    "#E41A1C",
                    "#377EB8",
                    "#4DAF4A",
                    "#984EA3",
                    "#FF7F00",
                    "#FFFF33",
                    "#A65628",
                    "#F781BF",
                    "#999999",
                    "#000000",
                    "#FFFFFF",
                    "#1B9E77",
                    "#D95F02",
                    "#7570B3",
                    "#E7298A",
                    "#66A61E",
                    "#E6AB02",
                    "#A6761D",
                    "#666666"),
                default="none")
            private$..color8 <- jmvcore::OptionList$new(
                "color8",
                color8,
                options=list(
                    "none",
                    "#E41A1C",
                    "#377EB8",
                    "#4DAF4A",
                    "#984EA3",
                    "#FF7F00",
                    "#FFFF33",
                    "#A65628",
                    "#F781BF",
                    "#999999",
                    "#000000",
                    "#FFFFFF",
                    "#1B9E77",
                    "#D95F02",
                    "#7570B3",
                    "#E7298A",
                    "#66A61E",
                    "#E6AB02",
                    "#A6761D",
                    "#666666"),
                default="none")
            private$..titleText <- jmvcore::OptionString$new(
                "titleText",
                titleText,
                default="")
            private$..subtitleText <- jmvcore::OptionString$new(
                "subtitleText",
                subtitleText,
                default="")
            private$..xLabel <- jmvcore::OptionString$new(
                "xLabel",
                xLabel,
                default="")
            private$..yLabel <- jmvcore::OptionString$new(
                "yLabel",
                yLabel,
                default="")
            private$..xAngle <- jmvcore::OptionNumber$new(
                "xAngle",
                xAngle,
                min=0,
                max=90,
                default=0)
            private$..legendPosition <- jmvcore::OptionList$new(
                "legendPosition",
                legendPosition,
                options=list(
                    "right",
                    "left",
                    "top",
                    "bottom",
                    "none"),
                default="right")
            private$..removeGap <- jmvcore::OptionBool$new(
                "removeGap",
                removeGap,
                default=FALSE)
            private$..customYAxis <- jmvcore::OptionBool$new(
                "customYAxis",
                customYAxis,
                default=FALSE)
            private$..yMin <- jmvcore::OptionNumber$new(
                "yMin",
                yMin,
                default=0)
            private$..yMax <- jmvcore::OptionNumber$new(
                "yMax",
                yMax,
                default=100)
            private$..yStep <- jmvcore::OptionNumber$new(
                "yStep",
                yStep,
                default=10)
            private$..fontSizeTitle <- jmvcore::OptionNumber$new(
                "fontSizeTitle",
                fontSizeTitle,
                min=6,
                max=32,
                default=14)
            private$..fontSizeSubtitle <- jmvcore::OptionNumber$new(
                "fontSizeSubtitle",
                fontSizeSubtitle,
                min=6,
                max=32,
                default=12)
            private$..fontSizeAxis <- jmvcore::OptionNumber$new(
                "fontSizeAxis",
                fontSizeAxis,
                min=6,
                max=32,
                default=11)
            private$..fontSizeAxisTitle <- jmvcore::OptionNumber$new(
                "fontSizeAxisTitle",
                fontSizeAxisTitle,
                min=6,
                max=32,
                default=12)
            private$..fontSizeLegend <- jmvcore::OptionNumber$new(
                "fontSizeLegend",
                fontSizeLegend,
                min=6,
                max=32,
                default=10)
            private$..lineWidth <- jmvcore::OptionNumber$new(
                "lineWidth",
                lineWidth,
                min=0,
                max=5,
                default=0.8)
            private$..errorLineWidth <- jmvcore::OptionNumber$new(
                "errorLineWidth",
                errorLineWidth,
                min=0,
                max=5,
                default=0.8)
            private$..axisLineWidth <- jmvcore::OptionNumber$new(
                "axisLineWidth",
                axisLineWidth,
                min=0,
                max=5,
                default=0.8)
            private$..barWidth <- jmvcore::OptionNumber$new(
                "barWidth",
                barWidth,
                min=0.1,
                max=1,
                default=0.7)
            private$..barAlpha <- jmvcore::OptionNumber$new(
                "barAlpha",
                barAlpha,
                min=0,
                max=1,
                default=1)
            private$..pointSize <- jmvcore::OptionNumber$new(
                "pointSize",
                pointSize,
                min=0.5,
                max=10,
                default=2)
            private$..pointAlpha <- jmvcore::OptionNumber$new(
                "pointAlpha",
                pointAlpha,
                min=0,
                max=1,
                default=0.5)

            self$.addOption(private$..analysisType)
            self$.addOption(private$..deps)
            self$.addOption(private$..group)
            self$.addOption(private$..rm_vars)
            self$.addOption(private$..group_long)
            self$.addOption(private$..cov)
            self$.addOption(private$..cov_long)
            self$.addOption(private$..plotType)
            self$.addOption(private$..intStyle)
            self$.addOption(private$..showLines)
            self$.addOption(private$..errorType)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..showPoints)
            self$.addOption(private$..showTable)
            self$.addOption(private$..tableFormat)
            self$.addOption(private$..tableTitle)
            self$.addOption(private$..tableNote)
            self$.addOption(private$..themePlot)
            self$.addOption(private$..colorPalette)
            self$.addOption(private$..color1)
            self$.addOption(private$..color2)
            self$.addOption(private$..color3)
            self$.addOption(private$..color4)
            self$.addOption(private$..color5)
            self$.addOption(private$..color6)
            self$.addOption(private$..color7)
            self$.addOption(private$..color8)
            self$.addOption(private$..titleText)
            self$.addOption(private$..subtitleText)
            self$.addOption(private$..xLabel)
            self$.addOption(private$..yLabel)
            self$.addOption(private$..xAngle)
            self$.addOption(private$..legendPosition)
            self$.addOption(private$..removeGap)
            self$.addOption(private$..customYAxis)
            self$.addOption(private$..yMin)
            self$.addOption(private$..yMax)
            self$.addOption(private$..yStep)
            self$.addOption(private$..fontSizeTitle)
            self$.addOption(private$..fontSizeSubtitle)
            self$.addOption(private$..fontSizeAxis)
            self$.addOption(private$..fontSizeAxisTitle)
            self$.addOption(private$..fontSizeLegend)
            self$.addOption(private$..lineWidth)
            self$.addOption(private$..errorLineWidth)
            self$.addOption(private$..axisLineWidth)
            self$.addOption(private$..barWidth)
            self$.addOption(private$..barAlpha)
            self$.addOption(private$..pointSize)
            self$.addOption(private$..pointAlpha)
        }),
    active = list(
        analysisType = function() private$..analysisType$value,
        deps = function() private$..deps$value,
        group = function() private$..group$value,
        rm_vars = function() private$..rm_vars$value,
        group_long = function() private$..group_long$value,
        cov = function() private$..cov$value,
        cov_long = function() private$..cov_long$value,
        plotType = function() private$..plotType$value,
        intStyle = function() private$..intStyle$value,
        showLines = function() private$..showLines$value,
        errorType = function() private$..errorType$value,
        ciWidth = function() private$..ciWidth$value,
        showPoints = function() private$..showPoints$value,
        showTable = function() private$..showTable$value,
        tableFormat = function() private$..tableFormat$value,
        tableTitle = function() private$..tableTitle$value,
        tableNote = function() private$..tableNote$value,
        themePlot = function() private$..themePlot$value,
        colorPalette = function() private$..colorPalette$value,
        color1 = function() private$..color1$value,
        color2 = function() private$..color2$value,
        color3 = function() private$..color3$value,
        color4 = function() private$..color4$value,
        color5 = function() private$..color5$value,
        color6 = function() private$..color6$value,
        color7 = function() private$..color7$value,
        color8 = function() private$..color8$value,
        titleText = function() private$..titleText$value,
        subtitleText = function() private$..subtitleText$value,
        xLabel = function() private$..xLabel$value,
        yLabel = function() private$..yLabel$value,
        xAngle = function() private$..xAngle$value,
        legendPosition = function() private$..legendPosition$value,
        removeGap = function() private$..removeGap$value,
        customYAxis = function() private$..customYAxis$value,
        yMin = function() private$..yMin$value,
        yMax = function() private$..yMax$value,
        yStep = function() private$..yStep$value,
        fontSizeTitle = function() private$..fontSizeTitle$value,
        fontSizeSubtitle = function() private$..fontSizeSubtitle$value,
        fontSizeAxis = function() private$..fontSizeAxis$value,
        fontSizeAxisTitle = function() private$..fontSizeAxisTitle$value,
        fontSizeLegend = function() private$..fontSizeLegend$value,
        lineWidth = function() private$..lineWidth$value,
        errorLineWidth = function() private$..errorLineWidth$value,
        axisLineWidth = function() private$..axisLineWidth$value,
        barWidth = function() private$..barWidth$value,
        barAlpha = function() private$..barAlpha$value,
        pointSize = function() private$..pointSize$value,
        pointAlpha = function() private$..pointAlpha$value),
    private = list(
        ..analysisType = NA,
        ..deps = NA,
        ..group = NA,
        ..rm_vars = NA,
        ..group_long = NA,
        ..cov = NA,
        ..cov_long = NA,
        ..plotType = NA,
        ..intStyle = NA,
        ..showLines = NA,
        ..errorType = NA,
        ..ciWidth = NA,
        ..showPoints = NA,
        ..showTable = NA,
        ..tableFormat = NA,
        ..tableTitle = NA,
        ..tableNote = NA,
        ..themePlot = NA,
        ..colorPalette = NA,
        ..color1 = NA,
        ..color2 = NA,
        ..color3 = NA,
        ..color4 = NA,
        ..color5 = NA,
        ..color6 = NA,
        ..color7 = NA,
        ..color8 = NA,
        ..titleText = NA,
        ..subtitleText = NA,
        ..xLabel = NA,
        ..yLabel = NA,
        ..xAngle = NA,
        ..legendPosition = NA,
        ..removeGap = NA,
        ..customYAxis = NA,
        ..yMin = NA,
        ..yMax = NA,
        ..yStep = NA,
        ..fontSizeTitle = NA,
        ..fontSizeSubtitle = NA,
        ..fontSizeAxis = NA,
        ..fontSizeAxisTitle = NA,
        ..fontSizeLegend = NA,
        ..lineWidth = NA,
        ..errorLineWidth = NA,
        ..axisLineWidth = NA,
        ..barWidth = NA,
        ..barAlpha = NA,
        ..pointSize = NA,
        ..pointAlpha = NA)
)

DataPresentationResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "DataPresentationResults",
    inherit = jmvcore::Group,
    active = list(
        messages = function() private$.items[["messages"]],
        descriptiveTable = function() private$.items[["descriptiveTable"]],
        plots = function() private$.items[["plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Data Presentation")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="messages",
                title="Analysis Status",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="descriptiveTable",
                title="Descriptive Statistics",
                visible="(showTable)",
                refs=list(
                    "dplyr",
                    "tidyr",
                    "emmeans"),
                clearWith=list(
                    "analysisType",
                    "deps",
                    "group",
                    "rm_vars",
                    "group_long",
                    "cov",
                    "cov_long",
                    "showTable",
                    "tableFormat",
                    "tableTitle",
                    "tableNote",
                    "ciWidth",
                    "intStyle"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="mean", 
                        `title`="M", 
                        `type`="number", 
                        `format`="dp:2"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number", 
                        `format`="dp:2"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `format`="dp:2"),
                    list(
                        `name`="ci_lower", 
                        `title`="CI Lower", 
                        `type`="number", 
                        `format`="dp:2"),
                    list(
                        `name`="ci_upper", 
                        `title`="CI Upper", 
                        `type`="number", 
                        `format`="dp:2"),
                    list(
                        `name`="median", 
                        `title`="Mdn", 
                        `type`="number", 
                        `format`="dp:2"),
                    list(
                        `name`="min", 
                        `title`="Min", 
                        `type`="number", 
                        `format`="dp:2"),
                    list(
                        `name`="max", 
                        `title`="Max", 
                        `type`="number", 
                        `format`="dp:2"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="plots",
                title="Group Comparison Plot",
                refs=list(
                    "ggplot2",
                    "dplyr",
                    "tidyr"),
                clearWith=list(
                    "analysisType",
                    "deps",
                    "group",
                    "rm_vars",
                    "group_long",
                    "cov",
                    "cov_long",
                    "plotType",
                    "intStyle",
                    "showLines",
                    "errorType",
                    "ciWidth",
                    "showPoints",
                    "themePlot",
                    "colorPalette",
                    "color1",
                    "color2",
                    "color3",
                    "color4",
                    "color5",
                    "color6",
                    "color7",
                    "color8",
                    "titleText",
                    "subtitleText",
                    "xLabel",
                    "yLabel",
                    "xAngle",
                    "legendPosition",
                    "removeGap",
                    "customYAxis",
                    "yMin",
                    "yMax",
                    "yStep",
                    "fontSizeTitle",
                    "fontSizeSubtitle",
                    "fontSizeAxis",
                    "fontSizeAxisTitle",
                    "fontSizeLegend",
                    "lineWidth",
                    "errorLineWidth",
                    "axisLineWidth",
                    "barWidth",
                    "barAlpha",
                    "pointSize",
                    "pointAlpha"),
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    width=600,
                    height=500,
                    requiresData=TRUE,
                    renderFun=".plotGroup")))}))

DataPresentationBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "DataPresentationBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BSS",
                name = "DataPresentation",
                version = c(1,2,0),
                options = options,
                results = DataPresentationResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Data Presentation
#'
#' 
#' @param data .
#' @param analysisType .
#' @param deps .
#' @param group .
#' @param rm_vars .
#' @param group_long .
#' @param cov .
#' @param cov_long .
#' @param plotType .
#' @param intStyle .
#' @param showLines .
#' @param errorType .
#' @param ciWidth .
#' @param showPoints .
#' @param showTable .
#' @param tableFormat .
#' @param tableTitle .
#' @param tableNote .
#' @param themePlot .
#' @param colorPalette .
#' @param color1 .
#' @param color2 .
#' @param color3 .
#' @param color4 .
#' @param color5 .
#' @param color6 .
#' @param color7 .
#' @param color8 .
#' @param titleText .
#' @param subtitleText .
#' @param xLabel .
#' @param yLabel .
#' @param xAngle .
#' @param legendPosition .
#' @param removeGap .
#' @param customYAxis .
#' @param yMin .
#' @param yMax .
#' @param yStep .
#' @param fontSizeTitle .
#' @param fontSizeSubtitle .
#' @param fontSizeAxis .
#' @param fontSizeAxisTitle .
#' @param fontSizeLegend .
#' @param lineWidth .
#' @param errorLineWidth .
#' @param axisLineWidth .
#' @param barWidth .
#' @param barAlpha .
#' @param pointSize .
#' @param pointAlpha .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$messages} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$descriptiveTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab One plot per dependent variable \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$descriptiveTable$asDF}
#'
#' \code{as.data.frame(results$descriptiveTable)}
#'
#' @export
DataPresentation <- function(
    data,
    analysisType = "cross_sectional",
    deps,
    group,
    rm_vars,
    group_long,
    cov,
    cov_long,
    plotType = "bar",
    intStyle = "legend",
    showLines = TRUE,
    errorType = "sd",
    ciWidth = 95,
    showPoints = FALSE,
    showTable = TRUE,
    tableFormat = "apa",
    tableTitle = "Table 1. Descriptive statistics by group",
    tableNote = "Note. M = mean; SD = standard deviation; SE = standard error; CI = confidence interval; N = sample size.",
    themePlot = "classic",
    colorPalette = "set1",
    color1 = "none",
    color2 = "none",
    color3 = "none",
    color4 = "none",
    color5 = "none",
    color6 = "none",
    color7 = "none",
    color8 = "none",
    titleText = "",
    subtitleText = "",
    xLabel = "",
    yLabel = "",
    xAngle = 0,
    legendPosition = "right",
    removeGap = FALSE,
    customYAxis = FALSE,
    yMin = 0,
    yMax = 100,
    yStep = 10,
    fontSizeTitle = 14,
    fontSizeSubtitle = 12,
    fontSizeAxis = 11,
    fontSizeAxisTitle = 12,
    fontSizeLegend = 10,
    lineWidth = 0.8,
    errorLineWidth = 0.8,
    axisLineWidth = 0.8,
    barWidth = 0.7,
    barAlpha = 1,
    pointSize = 2,
    pointAlpha = 0.5) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("DataPresentation requires jmvcore to be installed (restart may be required)")

    if ( ! missing(deps)) deps <- jmvcore::resolveQuo(jmvcore::enquo(deps))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if ( ! missing(rm_vars)) rm_vars <- jmvcore::resolveQuo(jmvcore::enquo(rm_vars))
    if ( ! missing(group_long)) group_long <- jmvcore::resolveQuo(jmvcore::enquo(group_long))
    if ( ! missing(cov)) cov <- jmvcore::resolveQuo(jmvcore::enquo(cov))
    if ( ! missing(cov_long)) cov_long <- jmvcore::resolveQuo(jmvcore::enquo(cov_long))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(deps), deps, NULL),
            `if`( ! missing(group), group, NULL),
            `if`( ! missing(rm_vars), rm_vars, NULL),
            `if`( ! missing(group_long), group_long, NULL),
            `if`( ! missing(cov), cov, NULL),
            `if`( ! missing(cov_long), cov_long, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in group_long) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- DataPresentationOptions$new(
        analysisType = analysisType,
        deps = deps,
        group = group,
        rm_vars = rm_vars,
        group_long = group_long,
        cov = cov,
        cov_long = cov_long,
        plotType = plotType,
        intStyle = intStyle,
        showLines = showLines,
        errorType = errorType,
        ciWidth = ciWidth,
        showPoints = showPoints,
        showTable = showTable,
        tableFormat = tableFormat,
        tableTitle = tableTitle,
        tableNote = tableNote,
        themePlot = themePlot,
        colorPalette = colorPalette,
        color1 = color1,
        color2 = color2,
        color3 = color3,
        color4 = color4,
        color5 = color5,
        color6 = color6,
        color7 = color7,
        color8 = color8,
        titleText = titleText,
        subtitleText = subtitleText,
        xLabel = xLabel,
        yLabel = yLabel,
        xAngle = xAngle,
        legendPosition = legendPosition,
        removeGap = removeGap,
        customYAxis = customYAxis,
        yMin = yMin,
        yMax = yMax,
        yStep = yStep,
        fontSizeTitle = fontSizeTitle,
        fontSizeSubtitle = fontSizeSubtitle,
        fontSizeAxis = fontSizeAxis,
        fontSizeAxisTitle = fontSizeAxisTitle,
        fontSizeLegend = fontSizeLegend,
        lineWidth = lineWidth,
        errorLineWidth = errorLineWidth,
        axisLineWidth = axisLineWidth,
        barWidth = barWidth,
        barAlpha = barAlpha,
        pointSize = pointSize,
        pointAlpha = pointAlpha)

    analysis <- DataPresentationClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

