
# This file is automatically generated, you probably don't want to edit this

dataimputationOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dataimputationOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mode = "mice_cs",
            vars_mice_cs = NULL,
            predictor_vars_mice_cs = NULL,
            imputation_method_mice_cs = "pmm",
            num_imputations_mice_cs = 5,
            maxiter_mice_cs = 10,
            seed_mice_cs = "",
            run_imputation_mice_cs = FALSE,
            show_pattern_plot_mice_cs = FALSE,
            show_correlation_plot_mice_cs = FALSE,
            show_trace_plot_mice_cs = FALSE,
            show_density_plot_mice_cs = FALSE,
            show_strip_plot_mice_cs = FALSE,
            vars_mice_long = NULL,
            predictor_vars_mice_long = NULL,
            data_format_mice_long = "wide",
            subject_id_var_mice_long = NULL,
            time_var_mice_long = NULL,
            group_var_mice_long = NULL,
            fixed_covariates_mice_long = NULL,
            wave_vars_mice_long = NULL,
            imputation_method_mice_long = "2l.pmm",
            num_imputations_mice_long = 5,
            maxiter_mice_long = 10,
            seed_mice_long = "",
            run_imputation_mice_long = FALSE,
            show_pattern_plot_mice_long = FALSE,
            show_correlation_plot_mice_long = FALSE,
            show_trace_plot_mice_long = FALSE,
            show_density_plot_mice_long = FALSE,
            show_strip_plot_mice_long = FALSE,
            vars_mr = NULL,
            predictor_vars_mr = NULL,
            use_multiple_imputation_mr = FALSE,
            num_imputations_mr = 5,
            maxiter_mr = 10,
            num_trees_mr = 100,
            pmm_k_mr = 5,
            seed_mr = "",
            run_imputation_mr = FALSE,
            show_pattern_plot_mr = FALSE,
            show_correlation_plot_mr = FALSE, ...) {

            super$initialize(
                package="BSS",
                name="dataimputation",
                requiresData=TRUE,
                ...)

            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "mice_cs",
                    "mice_long",
                    "missranger"),
                default="mice_cs")
            private$..vars_mice_cs <- jmvcore::OptionVariables$new(
                "vars_mice_cs",
                vars_mice_cs,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..predictor_vars_mice_cs <- jmvcore::OptionVariables$new(
                "predictor_vars_mice_cs",
                predictor_vars_mice_cs,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..imputation_method_mice_cs <- jmvcore::OptionList$new(
                "imputation_method_mice_cs",
                imputation_method_mice_cs,
                options=list(
                    "pmm",
                    "norm",
                    "logreg",
                    "polyreg"),
                default="pmm")
            private$..num_imputations_mice_cs <- jmvcore::OptionInteger$new(
                "num_imputations_mice_cs",
                num_imputations_mice_cs,
                default=5,
                min=2,
                max=50)
            private$..maxiter_mice_cs <- jmvcore::OptionInteger$new(
                "maxiter_mice_cs",
                maxiter_mice_cs,
                default=10,
                min=1,
                max=100)
            private$..seed_mice_cs <- jmvcore::OptionString$new(
                "seed_mice_cs",
                seed_mice_cs,
                default="")
            private$..run_imputation_mice_cs <- jmvcore::OptionBool$new(
                "run_imputation_mice_cs",
                run_imputation_mice_cs,
                default=FALSE)
            private$..show_pattern_plot_mice_cs <- jmvcore::OptionBool$new(
                "show_pattern_plot_mice_cs",
                show_pattern_plot_mice_cs,
                default=FALSE)
            private$..show_correlation_plot_mice_cs <- jmvcore::OptionBool$new(
                "show_correlation_plot_mice_cs",
                show_correlation_plot_mice_cs,
                default=FALSE)
            private$..show_trace_plot_mice_cs <- jmvcore::OptionBool$new(
                "show_trace_plot_mice_cs",
                show_trace_plot_mice_cs,
                default=FALSE)
            private$..show_density_plot_mice_cs <- jmvcore::OptionBool$new(
                "show_density_plot_mice_cs",
                show_density_plot_mice_cs,
                default=FALSE)
            private$..show_strip_plot_mice_cs <- jmvcore::OptionBool$new(
                "show_strip_plot_mice_cs",
                show_strip_plot_mice_cs,
                default=FALSE)
            private$..imputedColsOutput_mice_cs <- jmvcore::OptionOutput$new(
                "imputedColsOutput_mice_cs")
            private$..vars_mice_long <- jmvcore::OptionVariables$new(
                "vars_mice_long",
                vars_mice_long,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..predictor_vars_mice_long <- jmvcore::OptionVariables$new(
                "predictor_vars_mice_long",
                predictor_vars_mice_long,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..data_format_mice_long <- jmvcore::OptionList$new(
                "data_format_mice_long",
                data_format_mice_long,
                options=list(
                    "long",
                    "wide"),
                default="wide")
            private$..subject_id_var_mice_long <- jmvcore::OptionVariable$new(
                "subject_id_var_mice_long",
                subject_id_var_mice_long,
                suggested=list(
                    "nominal",
                    "id"),
                permitted=list(
                    "factor",
                    "numeric",
                    "id"))
            private$..time_var_mice_long <- jmvcore::OptionVariable$new(
                "time_var_mice_long",
                time_var_mice_long,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..group_var_mice_long <- jmvcore::OptionVariable$new(
                "group_var_mice_long",
                group_var_mice_long,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..fixed_covariates_mice_long <- jmvcore::OptionVariables$new(
                "fixed_covariates_mice_long",
                fixed_covariates_mice_long,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..wave_vars_mice_long <- jmvcore::OptionVariables$new(
                "wave_vars_mice_long",
                wave_vars_mice_long,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..imputation_method_mice_long <- jmvcore::OptionList$new(
                "imputation_method_mice_long",
                imputation_method_mice_long,
                options=list(
                    "2l.pmm",
                    "2l.continuous"),
                default="2l.pmm")
            private$..num_imputations_mice_long <- jmvcore::OptionInteger$new(
                "num_imputations_mice_long",
                num_imputations_mice_long,
                default=5,
                min=2,
                max=50)
            private$..maxiter_mice_long <- jmvcore::OptionInteger$new(
                "maxiter_mice_long",
                maxiter_mice_long,
                default=10,
                min=1,
                max=100)
            private$..seed_mice_long <- jmvcore::OptionString$new(
                "seed_mice_long",
                seed_mice_long,
                default="")
            private$..run_imputation_mice_long <- jmvcore::OptionBool$new(
                "run_imputation_mice_long",
                run_imputation_mice_long,
                default=FALSE)
            private$..show_pattern_plot_mice_long <- jmvcore::OptionBool$new(
                "show_pattern_plot_mice_long",
                show_pattern_plot_mice_long,
                default=FALSE)
            private$..show_correlation_plot_mice_long <- jmvcore::OptionBool$new(
                "show_correlation_plot_mice_long",
                show_correlation_plot_mice_long,
                default=FALSE)
            private$..show_trace_plot_mice_long <- jmvcore::OptionBool$new(
                "show_trace_plot_mice_long",
                show_trace_plot_mice_long,
                default=FALSE)
            private$..show_density_plot_mice_long <- jmvcore::OptionBool$new(
                "show_density_plot_mice_long",
                show_density_plot_mice_long,
                default=FALSE)
            private$..show_strip_plot_mice_long <- jmvcore::OptionBool$new(
                "show_strip_plot_mice_long",
                show_strip_plot_mice_long,
                default=FALSE)
            private$..imputedColsOutput_mice_long <- jmvcore::OptionOutput$new(
                "imputedColsOutput_mice_long")
            private$..vars_mr <- jmvcore::OptionVariables$new(
                "vars_mr",
                vars_mr,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..predictor_vars_mr <- jmvcore::OptionVariables$new(
                "predictor_vars_mr",
                predictor_vars_mr,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..use_multiple_imputation_mr <- jmvcore::OptionBool$new(
                "use_multiple_imputation_mr",
                use_multiple_imputation_mr,
                default=FALSE)
            private$..num_imputations_mr <- jmvcore::OptionInteger$new(
                "num_imputations_mr",
                num_imputations_mr,
                default=5,
                min=2,
                max=50)
            private$..maxiter_mr <- jmvcore::OptionInteger$new(
                "maxiter_mr",
                maxiter_mr,
                default=10,
                min=1,
                max=100)
            private$..num_trees_mr <- jmvcore::OptionInteger$new(
                "num_trees_mr",
                num_trees_mr,
                default=100,
                min=1,
                max=200)
            private$..pmm_k_mr <- jmvcore::OptionInteger$new(
                "pmm_k_mr",
                pmm_k_mr,
                default=5,
                min=0,
                max=20)
            private$..seed_mr <- jmvcore::OptionString$new(
                "seed_mr",
                seed_mr,
                default="")
            private$..run_imputation_mr <- jmvcore::OptionBool$new(
                "run_imputation_mr",
                run_imputation_mr,
                default=FALSE)
            private$..show_pattern_plot_mr <- jmvcore::OptionBool$new(
                "show_pattern_plot_mr",
                show_pattern_plot_mr,
                default=FALSE)
            private$..show_correlation_plot_mr <- jmvcore::OptionBool$new(
                "show_correlation_plot_mr",
                show_correlation_plot_mr,
                default=FALSE)
            private$..imputedColsOutput_mr <- jmvcore::OptionOutput$new(
                "imputedColsOutput_mr")

            self$.addOption(private$..mode)
            self$.addOption(private$..vars_mice_cs)
            self$.addOption(private$..predictor_vars_mice_cs)
            self$.addOption(private$..imputation_method_mice_cs)
            self$.addOption(private$..num_imputations_mice_cs)
            self$.addOption(private$..maxiter_mice_cs)
            self$.addOption(private$..seed_mice_cs)
            self$.addOption(private$..run_imputation_mice_cs)
            self$.addOption(private$..show_pattern_plot_mice_cs)
            self$.addOption(private$..show_correlation_plot_mice_cs)
            self$.addOption(private$..show_trace_plot_mice_cs)
            self$.addOption(private$..show_density_plot_mice_cs)
            self$.addOption(private$..show_strip_plot_mice_cs)
            self$.addOption(private$..imputedColsOutput_mice_cs)
            self$.addOption(private$..vars_mice_long)
            self$.addOption(private$..predictor_vars_mice_long)
            self$.addOption(private$..data_format_mice_long)
            self$.addOption(private$..subject_id_var_mice_long)
            self$.addOption(private$..time_var_mice_long)
            self$.addOption(private$..group_var_mice_long)
            self$.addOption(private$..fixed_covariates_mice_long)
            self$.addOption(private$..wave_vars_mice_long)
            self$.addOption(private$..imputation_method_mice_long)
            self$.addOption(private$..num_imputations_mice_long)
            self$.addOption(private$..maxiter_mice_long)
            self$.addOption(private$..seed_mice_long)
            self$.addOption(private$..run_imputation_mice_long)
            self$.addOption(private$..show_pattern_plot_mice_long)
            self$.addOption(private$..show_correlation_plot_mice_long)
            self$.addOption(private$..show_trace_plot_mice_long)
            self$.addOption(private$..show_density_plot_mice_long)
            self$.addOption(private$..show_strip_plot_mice_long)
            self$.addOption(private$..imputedColsOutput_mice_long)
            self$.addOption(private$..vars_mr)
            self$.addOption(private$..predictor_vars_mr)
            self$.addOption(private$..use_multiple_imputation_mr)
            self$.addOption(private$..num_imputations_mr)
            self$.addOption(private$..maxiter_mr)
            self$.addOption(private$..num_trees_mr)
            self$.addOption(private$..pmm_k_mr)
            self$.addOption(private$..seed_mr)
            self$.addOption(private$..run_imputation_mr)
            self$.addOption(private$..show_pattern_plot_mr)
            self$.addOption(private$..show_correlation_plot_mr)
            self$.addOption(private$..imputedColsOutput_mr)
        }),
    active = list(
        mode = function() private$..mode$value,
        vars_mice_cs = function() private$..vars_mice_cs$value,
        predictor_vars_mice_cs = function() private$..predictor_vars_mice_cs$value,
        imputation_method_mice_cs = function() private$..imputation_method_mice_cs$value,
        num_imputations_mice_cs = function() private$..num_imputations_mice_cs$value,
        maxiter_mice_cs = function() private$..maxiter_mice_cs$value,
        seed_mice_cs = function() private$..seed_mice_cs$value,
        run_imputation_mice_cs = function() private$..run_imputation_mice_cs$value,
        show_pattern_plot_mice_cs = function() private$..show_pattern_plot_mice_cs$value,
        show_correlation_plot_mice_cs = function() private$..show_correlation_plot_mice_cs$value,
        show_trace_plot_mice_cs = function() private$..show_trace_plot_mice_cs$value,
        show_density_plot_mice_cs = function() private$..show_density_plot_mice_cs$value,
        show_strip_plot_mice_cs = function() private$..show_strip_plot_mice_cs$value,
        imputedColsOutput_mice_cs = function() private$..imputedColsOutput_mice_cs$value,
        vars_mice_long = function() private$..vars_mice_long$value,
        predictor_vars_mice_long = function() private$..predictor_vars_mice_long$value,
        data_format_mice_long = function() private$..data_format_mice_long$value,
        subject_id_var_mice_long = function() private$..subject_id_var_mice_long$value,
        time_var_mice_long = function() private$..time_var_mice_long$value,
        group_var_mice_long = function() private$..group_var_mice_long$value,
        fixed_covariates_mice_long = function() private$..fixed_covariates_mice_long$value,
        wave_vars_mice_long = function() private$..wave_vars_mice_long$value,
        imputation_method_mice_long = function() private$..imputation_method_mice_long$value,
        num_imputations_mice_long = function() private$..num_imputations_mice_long$value,
        maxiter_mice_long = function() private$..maxiter_mice_long$value,
        seed_mice_long = function() private$..seed_mice_long$value,
        run_imputation_mice_long = function() private$..run_imputation_mice_long$value,
        show_pattern_plot_mice_long = function() private$..show_pattern_plot_mice_long$value,
        show_correlation_plot_mice_long = function() private$..show_correlation_plot_mice_long$value,
        show_trace_plot_mice_long = function() private$..show_trace_plot_mice_long$value,
        show_density_plot_mice_long = function() private$..show_density_plot_mice_long$value,
        show_strip_plot_mice_long = function() private$..show_strip_plot_mice_long$value,
        imputedColsOutput_mice_long = function() private$..imputedColsOutput_mice_long$value,
        vars_mr = function() private$..vars_mr$value,
        predictor_vars_mr = function() private$..predictor_vars_mr$value,
        use_multiple_imputation_mr = function() private$..use_multiple_imputation_mr$value,
        num_imputations_mr = function() private$..num_imputations_mr$value,
        maxiter_mr = function() private$..maxiter_mr$value,
        num_trees_mr = function() private$..num_trees_mr$value,
        pmm_k_mr = function() private$..pmm_k_mr$value,
        seed_mr = function() private$..seed_mr$value,
        run_imputation_mr = function() private$..run_imputation_mr$value,
        show_pattern_plot_mr = function() private$..show_pattern_plot_mr$value,
        show_correlation_plot_mr = function() private$..show_correlation_plot_mr$value,
        imputedColsOutput_mr = function() private$..imputedColsOutput_mr$value),
    private = list(
        ..mode = NA,
        ..vars_mice_cs = NA,
        ..predictor_vars_mice_cs = NA,
        ..imputation_method_mice_cs = NA,
        ..num_imputations_mice_cs = NA,
        ..maxiter_mice_cs = NA,
        ..seed_mice_cs = NA,
        ..run_imputation_mice_cs = NA,
        ..show_pattern_plot_mice_cs = NA,
        ..show_correlation_plot_mice_cs = NA,
        ..show_trace_plot_mice_cs = NA,
        ..show_density_plot_mice_cs = NA,
        ..show_strip_plot_mice_cs = NA,
        ..imputedColsOutput_mice_cs = NA,
        ..vars_mice_long = NA,
        ..predictor_vars_mice_long = NA,
        ..data_format_mice_long = NA,
        ..subject_id_var_mice_long = NA,
        ..time_var_mice_long = NA,
        ..group_var_mice_long = NA,
        ..fixed_covariates_mice_long = NA,
        ..wave_vars_mice_long = NA,
        ..imputation_method_mice_long = NA,
        ..num_imputations_mice_long = NA,
        ..maxiter_mice_long = NA,
        ..seed_mice_long = NA,
        ..run_imputation_mice_long = NA,
        ..show_pattern_plot_mice_long = NA,
        ..show_correlation_plot_mice_long = NA,
        ..show_trace_plot_mice_long = NA,
        ..show_density_plot_mice_long = NA,
        ..show_strip_plot_mice_long = NA,
        ..imputedColsOutput_mice_long = NA,
        ..vars_mr = NA,
        ..predictor_vars_mr = NA,
        ..use_multiple_imputation_mr = NA,
        ..num_imputations_mr = NA,
        ..maxiter_mr = NA,
        ..num_trees_mr = NA,
        ..pmm_k_mr = NA,
        ..seed_mr = NA,
        ..run_imputation_mr = NA,
        ..show_pattern_plot_mr = NA,
        ..show_correlation_plot_mr = NA,
        ..imputedColsOutput_mr = NA)
)

dataimputationResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dataimputationResults",
    inherit = jmvcore::Group,
    active = list(
        imputationInfo_mice_cs = function() private$.items[["imputationInfo_mice_cs"]],
        missingnessTable_mice_cs = function() private$.items[["missingnessTable_mice_cs"]],
        imputedData_mice_cs = function() private$.items[["imputedData_mice_cs"]],
        patternPlot_mice_cs = function() private$.items[["patternPlot_mice_cs"]],
        correlationPlot_mice_cs = function() private$.items[["correlationPlot_mice_cs"]],
        tracePlot_mice_cs = function() private$.items[["tracePlot_mice_cs"]],
        densityPlot_mice_cs = function() private$.items[["densityPlot_mice_cs"]],
        stripPlot_mice_cs = function() private$.items[["stripPlot_mice_cs"]],
        imputedColsOutput_mice_cs = function() private$.items[["imputedColsOutput_mice_cs"]],
        imputationInfo_mice_long = function() private$.items[["imputationInfo_mice_long"]],
        missingnessTable_mice_long = function() private$.items[["missingnessTable_mice_long"]],
        imputedData_mice_long = function() private$.items[["imputedData_mice_long"]],
        patternPlot_mice_long = function() private$.items[["patternPlot_mice_long"]],
        correlationPlot_mice_long = function() private$.items[["correlationPlot_mice_long"]],
        tracePlot_mice_long = function() private$.items[["tracePlot_mice_long"]],
        densityPlot_mice_long = function() private$.items[["densityPlot_mice_long"]],
        stripPlot_mice_long = function() private$.items[["stripPlot_mice_long"]],
        imputedColsOutput_mice_long = function() private$.items[["imputedColsOutput_mice_long"]],
        imputationInfo_mr = function() private$.items[["imputationInfo_mr"]],
        missingnessTable_mr = function() private$.items[["missingnessTable_mr"]],
        imputedData_mr = function() private$.items[["imputedData_mr"]],
        patternPlot_mr = function() private$.items[["patternPlot_mr"]],
        correlationPlot_mr = function() private$.items[["correlationPlot_mr"]],
        imputedColsOutput_mr = function() private$.items[["imputedColsOutput_mr"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Missing data analysis and imputation")
            self$add(jmvcore::Html$new(
                options=options,
                name="imputationInfo_mice_cs",
                title="About MICE Cross-sectional Imputation",
                visible="(mode == 'mice_cs')"))
            self$add(jmvcore::Table$new(
                options=options,
                name="missingnessTable_mice_cs",
                title="Missingness Summary (Cross-sectional)",
                visible="(mode == 'mice_cs')",
                clearWith=list(
                    "vars_mice_cs",
                    "predictor_vars_mice_cs"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="n_missing", 
                        `title`="Missing (N)", 
                        `type`="integer"),
                    list(
                        `name`="pct_missing", 
                        `title`="Missing (%)", 
                        `type`="number", 
                        `format`="dp:1"),
                    list(
                        `name`="n_valid", 
                        `title`="Valid (N)", 
                        `type`="integer"),
                    list(
                        `name`="method_used", 
                        `title`="Method Applied", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="imputedData_mice_cs",
                title="Imputed Values (Pooled)",
                visible="(mode == 'mice_cs' && run_imputation_mice_cs)",
                refs=list(
                    "mice"),
                clearWith=list(
                    "vars_mice_cs",
                    "predictor_vars_mice_cs",
                    "run_imputation_mice_cs",
                    "imputation_method_mice_cs",
                    "num_imputations_mice_cs",
                    "maxiter_mice_cs",
                    "seed_mice_cs"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="original", 
                        `title`="Original Value", 
                        `type`="text"),
                    list(
                        `name`="imputed", 
                        `title`="Pooled Imputed Value", 
                        `type`="text"),
                    list(
                        `name`="rowNumber", 
                        `title`="Row", 
                        `type`="integer"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="patternPlot_mice_cs",
                title="Missing Data Pattern (md.pattern)",
                width=700,
                height=500,
                renderFun=".renderPatternPlotMiceCS",
                visible="(mode == 'mice_cs' && show_pattern_plot_mice_cs)",
                requiresData=TRUE,
                refs=list(
                    "VIM"),
                clearWith=list(
                    "vars_mice_cs",
                    "predictor_vars_mice_cs")))
            self$add(jmvcore::Image$new(
                options=options,
                name="correlationPlot_mice_cs",
                title="Missingness Correlation Heatmap",
                width=700,
                height=500,
                renderFun=".renderCorrelationPlotMiceCS",
                visible="(mode == 'mice_cs' && show_correlation_plot_mice_cs)",
                requiresData=TRUE,
                refs=list(
                    "GGally"),
                clearWith=list(
                    "vars_mice_cs",
                    "predictor_vars_mice_cs")))
            self$add(jmvcore::Image$new(
                options=options,
                name="tracePlot_mice_cs",
                title="Convergence Trace Plot",
                width=700,
                height=500,
                renderFun=".renderTracePlotMiceCS",
                visible="(mode == 'mice_cs' && run_imputation_mice_cs && show_trace_plot_mice_cs)",
                requiresData=TRUE,
                refs=list(
                    "mice"),
                clearWith=list(
                    "vars_mice_cs",
                    "predictor_vars_mice_cs",
                    "run_imputation_mice_cs",
                    "imputation_method_mice_cs",
                    "num_imputations_mice_cs",
                    "maxiter_mice_cs",
                    "seed_mice_cs")))
            self$add(jmvcore::Image$new(
                options=options,
                name="densityPlot_mice_cs",
                title="Observed vs Imputed Distribution",
                width=700,
                height=500,
                renderFun=".renderDensityPlotMiceCS",
                visible="(mode == 'mice_cs' && run_imputation_mice_cs && show_density_plot_mice_cs)",
                requiresData=TRUE,
                refs=list(
                    "mice"),
                clearWith=list(
                    "vars_mice_cs",
                    "predictor_vars_mice_cs",
                    "run_imputation_mice_cs",
                    "imputation_method_mice_cs",
                    "num_imputations_mice_cs",
                    "maxiter_mice_cs",
                    "seed_mice_cs")))
            self$add(jmvcore::Image$new(
                options=options,
                name="stripPlot_mice_cs",
                title="Strip Plot by Variable",
                width=700,
                height=500,
                renderFun=".renderStripPlotMiceCS",
                visible="(mode == 'mice_cs' && run_imputation_mice_cs && show_strip_plot_mice_cs)",
                requiresData=TRUE,
                refs=list(
                    "mice"),
                clearWith=list(
                    "vars_mice_cs",
                    "predictor_vars_mice_cs",
                    "run_imputation_mice_cs",
                    "imputation_method_mice_cs",
                    "num_imputations_mice_cs",
                    "maxiter_mice_cs",
                    "seed_mice_cs")))
            self$add(jmvcore::Output$new(
                options=options,
                name="imputedColsOutput_mice_cs",
                title="Imputed Variables (MICE Cross-sectional)",
                initInRun=TRUE,
                clearWith=list(
                    "data",
                    "vars_mice_cs",
                    "predictor_vars_mice_cs",
                    "imputation_method_mice_cs",
                    "num_imputations_mice_cs",
                    "maxiter_mice_cs",
                    "seed_mice_cs",
                    "run_imputation_mice_cs")))
            self$add(jmvcore::Html$new(
                options=options,
                name="imputationInfo_mice_long",
                title="About MICE Longitudinal Imputation",
                visible="(mode == 'mice_long')"))
            self$add(jmvcore::Table$new(
                options=options,
                name="missingnessTable_mice_long",
                title="Missingness Summary (Longitudinal)",
                visible="(mode == 'mice_long')",
                clearWith=list(
                    "vars_mice_long",
                    "predictor_vars_mice_long",
                    "wave_vars_mice_long",
                    "data_format_mice_long"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="n_missing", 
                        `title`="Missing (N)", 
                        `type`="integer"),
                    list(
                        `name`="pct_missing", 
                        `title`="Missing (%)", 
                        `type`="number", 
                        `format`="dp:1"),
                    list(
                        `name`="n_valid", 
                        `title`="Valid (N)", 
                        `type`="integer"),
                    list(
                        `name`="method_used", 
                        `title`="Method Applied", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="imputedData_mice_long",
                title="Imputed Values (Pooled)",
                visible="(mode == 'mice_long' && run_imputation_mice_long)",
                refs=list(
                    "mice",
                    "miceadds"),
                clearWith=list(
                    "vars_mice_long",
                    "predictor_vars_mice_long",
                    "run_imputation_mice_long",
                    "imputation_method_mice_long",
                    "num_imputations_mice_long",
                    "maxiter_mice_long",
                    "seed_mice_long",
                    "data_format_mice_long",
                    "wave_vars_mice_long",
                    "subject_id_var_mice_long",
                    "time_var_mice_long",
                    "group_var_mice_long",
                    "fixed_covariates_mice_long"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="original", 
                        `title`="Original Value", 
                        `type`="text"),
                    list(
                        `name`="imputed", 
                        `title`="Pooled Imputed Value", 
                        `type`="text"),
                    list(
                        `name`="rowNumber", 
                        `title`="Row", 
                        `type`="integer"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="patternPlot_mice_long",
                title="Missing Data Pattern (md.pattern)",
                width=700,
                height=500,
                renderFun=".renderPatternPlotMiceLong",
                visible="(mode == 'mice_long' && show_pattern_plot_mice_long)",
                requiresData=TRUE,
                refs=list(
                    "VIM"),
                clearWith=list(
                    "vars_mice_long",
                    "predictor_vars_mice_long",
                    "wave_vars_mice_long",
                    "data_format_mice_long")))
            self$add(jmvcore::Image$new(
                options=options,
                name="correlationPlot_mice_long",
                title="Missingness Correlation Heatmap",
                width=700,
                height=500,
                renderFun=".renderCorrelationPlotMiceLong",
                visible="(mode == 'mice_long' && show_correlation_plot_mice_long)",
                requiresData=TRUE,
                refs=list(
                    "GGally"),
                clearWith=list(
                    "vars_mice_long",
                    "predictor_vars_mice_long",
                    "wave_vars_mice_long",
                    "data_format_mice_long")))
            self$add(jmvcore::Image$new(
                options=options,
                name="tracePlot_mice_long",
                title="Convergence Trace Plot",
                width=700,
                height=500,
                renderFun=".renderTracePlotMiceLong",
                visible="(mode == 'mice_long' && run_imputation_mice_long && show_trace_plot_mice_long)",
                requiresData=TRUE,
                refs=list(
                    "mice",
                    "miceadds"),
                clearWith=list(
                    "vars_mice_long",
                    "predictor_vars_mice_long",
                    "run_imputation_mice_long",
                    "imputation_method_mice_long",
                    "num_imputations_mice_long",
                    "maxiter_mice_long",
                    "seed_mice_long",
                    "data_format_mice_long",
                    "wave_vars_mice_long",
                    "subject_id_var_mice_long",
                    "time_var_mice_long",
                    "group_var_mice_long",
                    "fixed_covariates_mice_long")))
            self$add(jmvcore::Image$new(
                options=options,
                name="densityPlot_mice_long",
                title="Observed vs Imputed Distribution",
                width=700,
                height=500,
                renderFun=".renderDensityPlotMiceLong",
                visible="(mode == 'mice_long' && run_imputation_mice_long && show_density_plot_mice_long)",
                requiresData=TRUE,
                refs=list(
                    "mice",
                    "miceadds"),
                clearWith=list(
                    "vars_mice_long",
                    "predictor_vars_mice_long",
                    "run_imputation_mice_long",
                    "imputation_method_mice_long",
                    "num_imputations_mice_long",
                    "maxiter_mice_long",
                    "seed_mice_long",
                    "data_format_mice_long",
                    "wave_vars_mice_long",
                    "subject_id_var_mice_long",
                    "time_var_mice_long",
                    "group_var_mice_long",
                    "fixed_covariates_mice_long")))
            self$add(jmvcore::Image$new(
                options=options,
                name="stripPlot_mice_long",
                title="Strip Plot by Variable",
                width=700,
                height=500,
                renderFun=".renderStripPlotMiceLong",
                visible="(mode == 'mice_long' && run_imputation_mice_long && show_strip_plot_mice_long)",
                requiresData=TRUE,
                refs=list(
                    "mice",
                    "miceadds"),
                clearWith=list(
                    "vars_mice_long",
                    "predictor_vars_mice_long",
                    "run_imputation_mice_long",
                    "imputation_method_mice_long",
                    "num_imputations_mice_long",
                    "maxiter_mice_long",
                    "seed_mice_long",
                    "data_format_mice_long",
                    "wave_vars_mice_long",
                    "subject_id_var_mice_long",
                    "time_var_mice_long",
                    "group_var_mice_long",
                    "fixed_covariates_mice_long")))
            self$add(jmvcore::Output$new(
                options=options,
                name="imputedColsOutput_mice_long",
                title="Imputed Variables (MICE Longitudinal)",
                initInRun=TRUE,
                clearWith=list(
                    "data",
                    "vars_mice_long",
                    "predictor_vars_mice_long",
                    "imputation_method_mice_long",
                    "num_imputations_mice_long",
                    "maxiter_mice_long",
                    "seed_mice_long",
                    "run_imputation_mice_long",
                    "data_format_mice_long",
                    "wave_vars_mice_long",
                    "subject_id_var_mice_long",
                    "time_var_mice_long",
                    "group_var_mice_long",
                    "fixed_covariates_mice_long")))
            self$add(jmvcore::Html$new(
                options=options,
                name="imputationInfo_mr",
                title="About missRanger Imputation",
                visible="(mode == 'missranger')"))
            self$add(jmvcore::Table$new(
                options=options,
                name="missingnessTable_mr",
                title="Missingness Summary (missRanger)",
                visible="(mode == 'missranger')",
                clearWith=list(
                    "vars_mr",
                    "predictor_vars_mr"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="n_missing", 
                        `title`="Missing (N)", 
                        `type`="integer"),
                    list(
                        `name`="pct_missing", 
                        `title`="Missing (%)", 
                        `type`="number", 
                        `format`="dp:1"),
                    list(
                        `name`="n_valid", 
                        `title`="Valid (N)", 
                        `type`="integer"),
                    list(
                        `name`="method_used", 
                        `title`="Method Applied", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="imputedData_mr",
                title="Imputed Values (missRanger)",
                visible="(mode == 'missranger' && run_imputation_mr)",
                refs=list(
                    "missRanger"),
                clearWith=list(
                    "vars_mr",
                    "predictor_vars_mr",
                    "run_imputation_mr",
                    "use_multiple_imputation_mr",
                    "num_imputations_mr",
                    "maxiter_mr",
                    "num_trees_mr",
                    "pmm_k_mr",
                    "seed_mr"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="original", 
                        `title`="Original Value", 
                        `type`="text"),
                    list(
                        `name`="imputed", 
                        `title`="Imputed Value", 
                        `type`="text"),
                    list(
                        `name`="rowNumber", 
                        `title`="Row", 
                        `type`="integer"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="patternPlot_mr",
                title="Missing Data Pattern (md.pattern)",
                width=700,
                height=500,
                renderFun=".renderPatternPlotMR",
                visible="(mode == 'missranger' && show_pattern_plot_mr)",
                requiresData=TRUE,
                refs=list(
                    "VIM"),
                clearWith=list(
                    "vars_mr",
                    "predictor_vars_mr")))
            self$add(jmvcore::Image$new(
                options=options,
                name="correlationPlot_mr",
                title="Missingness Correlation Heatmap",
                width=700,
                height=500,
                renderFun=".renderCorrelationPlotMR",
                visible="(mode == 'missranger' && show_correlation_plot_mr)",
                requiresData=TRUE,
                refs=list(
                    "GGally"),
                clearWith=list(
                    "vars_mr",
                    "predictor_vars_mr")))
            self$add(jmvcore::Output$new(
                options=options,
                name="imputedColsOutput_mr",
                title="Imputed Variables (missRanger)",
                initInRun=TRUE,
                clearWith=list(
                    "data",
                    "vars_mr",
                    "predictor_vars_mr",
                    "use_multiple_imputation_mr",
                    "num_imputations_mr",
                    "maxiter_mr",
                    "num_trees_mr",
                    "pmm_k_mr",
                    "seed_mr",
                    "run_imputation_mr")))}))

dataimputationBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dataimputationBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BSS",
                name = "dataimputation",
                version = c(1,0,0),
                options = options,
                results = dataimputationResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Missing data analysis and imputation
#'
#' 
#' @param data .
#' @param mode .
#' @param vars_mice_cs .
#' @param predictor_vars_mice_cs .
#' @param imputation_method_mice_cs .
#' @param num_imputations_mice_cs .
#' @param maxiter_mice_cs .
#' @param seed_mice_cs .
#' @param run_imputation_mice_cs .
#' @param show_pattern_plot_mice_cs .
#' @param show_correlation_plot_mice_cs .
#' @param show_trace_plot_mice_cs .
#' @param show_density_plot_mice_cs .
#' @param show_strip_plot_mice_cs .
#' @param vars_mice_long .
#' @param predictor_vars_mice_long .
#' @param data_format_mice_long .
#' @param subject_id_var_mice_long .
#' @param time_var_mice_long .
#' @param group_var_mice_long .
#' @param fixed_covariates_mice_long .
#' @param wave_vars_mice_long .
#' @param imputation_method_mice_long .
#' @param num_imputations_mice_long .
#' @param maxiter_mice_long .
#' @param seed_mice_long .
#' @param run_imputation_mice_long .
#' @param show_pattern_plot_mice_long .
#' @param show_correlation_plot_mice_long .
#' @param show_trace_plot_mice_long .
#' @param show_density_plot_mice_long .
#' @param show_strip_plot_mice_long .
#' @param vars_mr .
#' @param predictor_vars_mr .
#' @param use_multiple_imputation_mr .
#' @param num_imputations_mr .
#' @param maxiter_mr .
#' @param num_trees_mr .
#' @param pmm_k_mr .
#' @param seed_mr .
#' @param run_imputation_mr .
#' @param show_pattern_plot_mr .
#' @param show_correlation_plot_mr .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$imputationInfo_mice_cs} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$missingnessTable_mice_cs} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$imputedData_mice_cs} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$patternPlot_mice_cs} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$correlationPlot_mice_cs} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$tracePlot_mice_cs} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$densityPlot_mice_cs} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$stripPlot_mice_cs} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$imputedColsOutput_mice_cs} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$imputationInfo_mice_long} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$missingnessTable_mice_long} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$imputedData_mice_long} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$patternPlot_mice_long} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$correlationPlot_mice_long} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$tracePlot_mice_long} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$densityPlot_mice_long} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$stripPlot_mice_long} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$imputedColsOutput_mice_long} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$imputationInfo_mr} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$missingnessTable_mr} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$imputedData_mr} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$patternPlot_mr} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$correlationPlot_mr} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$imputedColsOutput_mr} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$missingnessTable_mice_cs$asDF}
#'
#' \code{as.data.frame(results$missingnessTable_mice_cs)}
#'
#' @export
dataimputation <- function(
    data,
    mode = "mice_cs",
    vars_mice_cs,
    predictor_vars_mice_cs,
    imputation_method_mice_cs = "pmm",
    num_imputations_mice_cs = 5,
    maxiter_mice_cs = 10,
    seed_mice_cs = "",
    run_imputation_mice_cs = FALSE,
    show_pattern_plot_mice_cs = FALSE,
    show_correlation_plot_mice_cs = FALSE,
    show_trace_plot_mice_cs = FALSE,
    show_density_plot_mice_cs = FALSE,
    show_strip_plot_mice_cs = FALSE,
    vars_mice_long,
    predictor_vars_mice_long,
    data_format_mice_long = "wide",
    subject_id_var_mice_long,
    time_var_mice_long,
    group_var_mice_long,
    fixed_covariates_mice_long,
    wave_vars_mice_long,
    imputation_method_mice_long = "2l.pmm",
    num_imputations_mice_long = 5,
    maxiter_mice_long = 10,
    seed_mice_long = "",
    run_imputation_mice_long = FALSE,
    show_pattern_plot_mice_long = FALSE,
    show_correlation_plot_mice_long = FALSE,
    show_trace_plot_mice_long = FALSE,
    show_density_plot_mice_long = FALSE,
    show_strip_plot_mice_long = FALSE,
    vars_mr,
    predictor_vars_mr,
    use_multiple_imputation_mr = FALSE,
    num_imputations_mr = 5,
    maxiter_mr = 10,
    num_trees_mr = 100,
    pmm_k_mr = 5,
    seed_mr = "",
    run_imputation_mr = FALSE,
    show_pattern_plot_mr = FALSE,
    show_correlation_plot_mr = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("dataimputation requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars_mice_cs)) vars_mice_cs <- jmvcore::resolveQuo(jmvcore::enquo(vars_mice_cs))
    if ( ! missing(predictor_vars_mice_cs)) predictor_vars_mice_cs <- jmvcore::resolveQuo(jmvcore::enquo(predictor_vars_mice_cs))
    if ( ! missing(vars_mice_long)) vars_mice_long <- jmvcore::resolveQuo(jmvcore::enquo(vars_mice_long))
    if ( ! missing(predictor_vars_mice_long)) predictor_vars_mice_long <- jmvcore::resolveQuo(jmvcore::enquo(predictor_vars_mice_long))
    if ( ! missing(subject_id_var_mice_long)) subject_id_var_mice_long <- jmvcore::resolveQuo(jmvcore::enquo(subject_id_var_mice_long))
    if ( ! missing(time_var_mice_long)) time_var_mice_long <- jmvcore::resolveQuo(jmvcore::enquo(time_var_mice_long))
    if ( ! missing(group_var_mice_long)) group_var_mice_long <- jmvcore::resolveQuo(jmvcore::enquo(group_var_mice_long))
    if ( ! missing(fixed_covariates_mice_long)) fixed_covariates_mice_long <- jmvcore::resolveQuo(jmvcore::enquo(fixed_covariates_mice_long))
    if ( ! missing(wave_vars_mice_long)) wave_vars_mice_long <- jmvcore::resolveQuo(jmvcore::enquo(wave_vars_mice_long))
    if ( ! missing(vars_mr)) vars_mr <- jmvcore::resolveQuo(jmvcore::enquo(vars_mr))
    if ( ! missing(predictor_vars_mr)) predictor_vars_mr <- jmvcore::resolveQuo(jmvcore::enquo(predictor_vars_mr))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars_mice_cs), vars_mice_cs, NULL),
            `if`( ! missing(predictor_vars_mice_cs), predictor_vars_mice_cs, NULL),
            `if`( ! missing(vars_mice_long), vars_mice_long, NULL),
            `if`( ! missing(predictor_vars_mice_long), predictor_vars_mice_long, NULL),
            `if`( ! missing(subject_id_var_mice_long), subject_id_var_mice_long, NULL),
            `if`( ! missing(time_var_mice_long), time_var_mice_long, NULL),
            `if`( ! missing(group_var_mice_long), group_var_mice_long, NULL),
            `if`( ! missing(fixed_covariates_mice_long), fixed_covariates_mice_long, NULL),
            `if`( ! missing(wave_vars_mice_long), wave_vars_mice_long, NULL),
            `if`( ! missing(vars_mr), vars_mr, NULL),
            `if`( ! missing(predictor_vars_mr), predictor_vars_mr, NULL))


    options <- dataimputationOptions$new(
        mode = mode,
        vars_mice_cs = vars_mice_cs,
        predictor_vars_mice_cs = predictor_vars_mice_cs,
        imputation_method_mice_cs = imputation_method_mice_cs,
        num_imputations_mice_cs = num_imputations_mice_cs,
        maxiter_mice_cs = maxiter_mice_cs,
        seed_mice_cs = seed_mice_cs,
        run_imputation_mice_cs = run_imputation_mice_cs,
        show_pattern_plot_mice_cs = show_pattern_plot_mice_cs,
        show_correlation_plot_mice_cs = show_correlation_plot_mice_cs,
        show_trace_plot_mice_cs = show_trace_plot_mice_cs,
        show_density_plot_mice_cs = show_density_plot_mice_cs,
        show_strip_plot_mice_cs = show_strip_plot_mice_cs,
        vars_mice_long = vars_mice_long,
        predictor_vars_mice_long = predictor_vars_mice_long,
        data_format_mice_long = data_format_mice_long,
        subject_id_var_mice_long = subject_id_var_mice_long,
        time_var_mice_long = time_var_mice_long,
        group_var_mice_long = group_var_mice_long,
        fixed_covariates_mice_long = fixed_covariates_mice_long,
        wave_vars_mice_long = wave_vars_mice_long,
        imputation_method_mice_long = imputation_method_mice_long,
        num_imputations_mice_long = num_imputations_mice_long,
        maxiter_mice_long = maxiter_mice_long,
        seed_mice_long = seed_mice_long,
        run_imputation_mice_long = run_imputation_mice_long,
        show_pattern_plot_mice_long = show_pattern_plot_mice_long,
        show_correlation_plot_mice_long = show_correlation_plot_mice_long,
        show_trace_plot_mice_long = show_trace_plot_mice_long,
        show_density_plot_mice_long = show_density_plot_mice_long,
        show_strip_plot_mice_long = show_strip_plot_mice_long,
        vars_mr = vars_mr,
        predictor_vars_mr = predictor_vars_mr,
        use_multiple_imputation_mr = use_multiple_imputation_mr,
        num_imputations_mr = num_imputations_mr,
        maxiter_mr = maxiter_mr,
        num_trees_mr = num_trees_mr,
        pmm_k_mr = pmm_k_mr,
        seed_mr = seed_mr,
        run_imputation_mr = run_imputation_mr,
        show_pattern_plot_mr = show_pattern_plot_mr,
        show_correlation_plot_mr = show_correlation_plot_mr)

    analysis <- dataimputationClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

