
# This file is automatically generated, you probably don't want to edit this

dataTransformOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dataTransformOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            method = "yeojohnson",
            auto_shift = TRUE,
            suffix = "_transfrmd",
            show_lambda_table = TRUE,
            show_normality_table = TRUE,
            alpha_sw = 0.05,
            show_qq_plot = TRUE,
            show_hist_plot = TRUE, ...) {

            super$initialize(
                package="BSS",
                name="dataTransform",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                required=TRUE,
                permitted=list(
                    "numeric"))
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "boxcox",
                    "yeojohnson",
                    "johnson"),
                default="yeojohnson")
            private$..auto_shift <- jmvcore::OptionBool$new(
                "auto_shift",
                auto_shift,
                default=TRUE)
            private$..suffix <- jmvcore::OptionString$new(
                "suffix",
                suffix,
                default="_transfrmd")
            private$..show_lambda_table <- jmvcore::OptionBool$new(
                "show_lambda_table",
                show_lambda_table,
                default=TRUE)
            private$..show_normality_table <- jmvcore::OptionBool$new(
                "show_normality_table",
                show_normality_table,
                default=TRUE)
            private$..alpha_sw <- jmvcore::OptionNumber$new(
                "alpha_sw",
                alpha_sw,
                default=0.05,
                min=0.01,
                max=0.1)
            private$..show_qq_plot <- jmvcore::OptionBool$new(
                "show_qq_plot",
                show_qq_plot,
                default=TRUE)
            private$..show_hist_plot <- jmvcore::OptionBool$new(
                "show_hist_plot",
                show_hist_plot,
                default=TRUE)
            private$..transformedVarsOutput <- jmvcore::OptionOutput$new(
                "transformedVarsOutput")

            self$.addOption(private$..vars)
            self$.addOption(private$..method)
            self$.addOption(private$..auto_shift)
            self$.addOption(private$..suffix)
            self$.addOption(private$..show_lambda_table)
            self$.addOption(private$..show_normality_table)
            self$.addOption(private$..alpha_sw)
            self$.addOption(private$..show_qq_plot)
            self$.addOption(private$..show_hist_plot)
            self$.addOption(private$..transformedVarsOutput)
        }),
    active = list(
        vars = function() private$..vars$value,
        method = function() private$..method$value,
        auto_shift = function() private$..auto_shift$value,
        suffix = function() private$..suffix$value,
        show_lambda_table = function() private$..show_lambda_table$value,
        show_normality_table = function() private$..show_normality_table$value,
        alpha_sw = function() private$..alpha_sw$value,
        show_qq_plot = function() private$..show_qq_plot$value,
        show_hist_plot = function() private$..show_hist_plot$value,
        transformedVarsOutput = function() private$..transformedVarsOutput$value),
    private = list(
        ..vars = NA,
        ..method = NA,
        ..auto_shift = NA,
        ..suffix = NA,
        ..show_lambda_table = NA,
        ..show_normality_table = NA,
        ..alpha_sw = NA,
        ..show_qq_plot = NA,
        ..show_hist_plot = NA,
        ..transformedVarsOutput = NA)
)

dataTransformResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dataTransformResults",
    inherit = jmvcore::Group,
    active = list(
        transformInfo = function() private$.items[["transformInfo"]],
        lambdaTable = function() private$.items[["lambdaTable"]],
        normalityTable = function() private$.items[["normalityTable"]],
        qqPlots = function() private$.items[["qqPlots"]],
        histPlots = function() private$.items[["histPlots"]],
        transformedVarsOutput = function() private$.items[["transformedVarsOutput"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Data Transformation")
            self$add(jmvcore::Html$new(
                options=options,
                name="transformInfo",
                title="About Data Transformation",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="lambdaTable",
                title="Lambda (\u03BB) Summary",
                visible="(show_lambda_table)",
                refs=list(
                    "bestNormalize",
                    "SuppDists"),
                clearWith=list(
                    "vars",
                    "method",
                    "auto_shift"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="method", 
                        `title`="Method", 
                        `type`="text"),
                    list(
                        `name`="parameter", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number", 
                        `format`="dp:4"),
                    list(
                        `name`="shift_applied", 
                        `title`="Shift Applied", 
                        `type`="text"),
                    list(
                        `name`="shift_value", 
                        `title`="Shift Value", 
                        `type`="number", 
                        `format`="dp:4"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="normalityTable",
                title="Shapiro-Wilk Normality Test",
                visible="(show_normality_table)",
                clearWith=list(
                    "vars",
                    "method",
                    "auto_shift",
                    "alpha_sw"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="moment", 
                        `title`="Moment", 
                        `type`="text"),
                    list(
                        `name`="W", 
                        `title`="W", 
                        `type`="number", 
                        `format`="dp:4"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="dp:4"),
                    list(
                        `name`="result", 
                        `title`="Normality", 
                        `type`="text"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="qqPlots",
                title="Q-Q Plot",
                items="(vars)",
                visible="(show_qq_plot)",
                refs=list(
                    "ggplot2",
                    "gridExtra"),
                clearWith=list(
                    "vars",
                    "method",
                    "auto_shift"),
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    width=650,
                    height=400,
                    renderFun=".qqPlot",
                    requiresData=TRUE)))
            self$add(jmvcore::Array$new(
                options=options,
                name="histPlots",
                title="Histogram",
                items="(vars)",
                visible="(show_hist_plot)",
                refs=list(
                    "ggplot2",
                    "gridExtra"),
                clearWith=list(
                    "vars",
                    "method",
                    "auto_shift"),
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    width=650,
                    height=400,
                    renderFun=".histPlot",
                    requiresData=TRUE)))
            self$add(jmvcore::Output$new(
                options=options,
                name="transformedVarsOutput",
                title="Transformed Variables",
                initInRun=TRUE,
                clearWith=list(
                    "data",
                    "vars",
                    "method",
                    "auto_shift",
                    "suffix")))}))

dataTransformBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dataTransformBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BSS",
                name = "dataTransform",
                version = c(0,0,1),
                options = options,
                results = dataTransformResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Data Transformation
#'
#' 
#' @param data .
#' @param vars .
#' @param method .
#' @param auto_shift .
#' @param suffix .
#' @param show_lambda_table .
#' @param show_normality_table .
#' @param alpha_sw .
#' @param show_qq_plot .
#' @param show_hist_plot .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$transformInfo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$lambdaTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$normalityTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$qqPlots} \tab \tab \tab \tab \tab an array of images \cr
#'   \code{results$histPlots} \tab \tab \tab \tab \tab an array of images \cr
#'   \code{results$transformedVarsOutput} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$lambdaTable$asDF}
#'
#' \code{as.data.frame(results$lambdaTable)}
#'
#' @export
dataTransform <- function(
    data,
    vars,
    method = "yeojohnson",
    auto_shift = TRUE,
    suffix = "_transfrmd",
    show_lambda_table = TRUE,
    show_normality_table = TRUE,
    alpha_sw = 0.05,
    show_qq_plot = TRUE,
    show_hist_plot = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("dataTransform requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- dataTransformOptions$new(
        vars = vars,
        method = method,
        auto_shift = auto_shift,
        suffix = suffix,
        show_lambda_table = show_lambda_table,
        show_normality_table = show_normality_table,
        alpha_sw = alpha_sw,
        show_qq_plot = show_qq_plot,
        show_hist_plot = show_hist_plot)

    analysis <- dataTransformClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

