dataTransformClass <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
  "dataTransformClass",
  inherit = dataTransformBase,
  private = list(
    
    .init = function() {
      if (is.null(self$options$vars) || length(self$options$vars) == 0) return()
      
      html <- self$results$transformInfo
      html$setContent("<h3>Data Transformation</h3><p>Power transformations for normality. NAs are preserved.</p>")
      
      if (self$options$show_lambda_table) {
        tbl <- self$results$lambdaTable
        tbl$setNote(
          "citation",
          "Note. Box-Cox and Yeo-Johnson transformations are performed using the bestNormalize package. Johnson curve transformations are performed using the SuppDists package. Citations: (1) Peterson, R. A. (2021). Finding optimal normalizing transformations via bestNormalize. The R Journal, 13(1), 310-329. (2) Wheeler, B. (2020). SuppDists: Supplementary Distributions. R package. (3) Box, G. E., & Cox, D. R. (1964). An analysis of transformations. Journal of the Royal Statistical Society: Series B, 26(2), 211-243. (4) Yeo, I. K., & Johnson, R. A. (2000). A new family of power transformations to improve normality or symmetry. Biometrika, 87(4), 955-969. (5) Johnson, N. L. (1949). Systems of frequency curves generated by methods of translation. Biometrika, 36(1/2), 149-176."
        )
        for (var in self$options$vars) {
          if (self$options$method == "johnson") {
            tbl$addRow(rowKey=paste0(var, "_type"), values=list(variable=var, method="Johnson", parameter="System (1=SU, 2=SB, 3=SL, 4=SN)"))
            tbl$addRow(rowKey=paste0(var, "_gamma"), values=list(variable=var, method="Johnson", parameter="Gamma"))
            tbl$addRow(rowKey=paste0(var, "_delta"), values=list(variable=var, method="Johnson", parameter="Delta"))
            tbl$addRow(rowKey=paste0(var, "_xi"), values=list(variable=var, method="Johnson", parameter="Xi"))
            tbl$addRow(rowKey=paste0(var, "_lambda"), values=list(variable=var, method="Johnson", parameter="Lambda"))
          } else {
            method_name <- ifelse(self$options$method == "boxcox", "Box-Cox", "Yeo-Johnson")
            tbl$addRow(rowKey=var, values=list(variable=var, method=method_name, parameter="Lambda (λ)"))
          }
        }
      }
      
      if (self$options$show_normality_table) {
        ntbl <- self$results$normalityTable
        ntbl$setNote(
          "citation",
          "Note. Shapiro-Wilk normality test is performed using stats::shapiro.test. Citation: Shapiro, S. S., & Wilk, M. B. (1965). An analysis of variance test for normality (complete samples). Biometrika, 52(3/4), 591-611."
        )
        for (var in self$options$vars) {
          ntbl$addRow(rowKey=paste0(var, "_before"), values=list(variable=var, moment="Before"))
          ntbl$addRow(rowKey=paste0(var, "_after"), values=list(variable=var, moment="After"))
        }
      }
    },
    
    .run = function() {
      vars <- self$options$vars
      if (is.null(vars) || length(vars) == 0) return()
      
      data <- self$data
      method <- self$options$method
      auto_shift <- self$options$auto_shift
      alpha_sw <- self$options$alpha_sw
      all_treated_vectors <- list()
      
      for (var in vars) {
        x <- data[[var]]
        is_valid <- !is.na(x)
        x_clean <- x[is_valid]
        
        if (length(x_clean) < 3 || stats::var(x_clean) == 0) next
        
        shift_val <- 0
        x_trans_clean <- NULL
        
        if (method == "boxcox") {
          min_x <- min(x_clean)
          if (min_x <= 0) {
            if (auto_shift) { 
              shift_val <- abs(min_x) + 0.001
              x_clean <- x_clean + shift_val
            }
            else jmvcore::reject("Box-Cox requires positive values.")
          }
          bc <- bestNormalize::boxcox(x_clean)
          x_trans_clean <- bc$x.t
          shift_applied <- ifelse(shift_val > 0, "Yes", "No")
          if(self$options$show_lambda_table) {
            self$results$lambdaTable$setRow(rowKey=var, values=list(value=bc$lambda, shift_applied=shift_applied, shift_value=shift_val))
          }
        } else if (method == "yeojohnson") {
          yj <- bestNormalize::yeojohnson(x_clean)
          x_trans_clean <- yj$x.t
          if(self$options$show_lambda_table) {
            self$results$lambdaTable$setRow(rowKey=var, values=list(value=yj$lambda, shift_applied="No", shift_value=0))
          }
        } else if (method == "johnson") {
          jt <- tryCatch(SuppDists::JohnsonFit(x_clean, moment="quant"), error=function(e) SuppDists::JohnsonFit(x_clean, moment="use"))
          y <- (x_clean - jt$xi) / jt$lambda
          if (jt$type == "SL") {
            y <- pmax(y, 1e-09)
          } else if (jt$type == "SB") {
            y <- pmin(pmax(y, 1e-09), 1 - 1e-09)
          }
          x_trans_clean <- switch(jt$type, "SN"=jt$gamma+jt$delta*y, "SL"=jt$gamma+jt$delta*log(y), "SU"=jt$gamma+jt$delta*asinh(y), "SB"=jt$gamma+jt$delta*log(y/(1-y)))
          if(self$options$show_lambda_table) {
            self$results$lambdaTable$setRow(rowKey=paste0(var, "_type"), values=list(value=switch(jt$type,"SU"=1,"SB"=2,"SL"=3,"SN"=4,0)))
            self$results$lambdaTable$setRow(rowKey=paste0(var, "_gamma"), values=list(value=jt$gamma))
            self$results$lambdaTable$setRow(rowKey=paste0(var, "_delta"), values=list(value=jt$delta))
            self$results$lambdaTable$setRow(rowKey=paste0(var, "_xi"), values=list(value=jt$xi))
            self$results$lambdaTable$setRow(rowKey=paste0(var, "_lambda"), values=list(value=jt$lambda))
          }
        }
        
        x_trans_full <- rep(NA, length(x))
        x_trans_full[is_valid] <- x_trans_clean
        all_treated_vectors[[var]] <- x_trans_full
        
        if (self$options$show_normality_table) {
          private$runShapiro(var, x_clean, "before", alpha_sw)
          private$runShapiro(var, x_trans_clean, "after", alpha_sw)
        }
        if (self$options$show_qq_plot) self$results$qqPlots$get(key=var)$setState(data.frame(before=x_clean, after=x_trans_clean))
        if (self$options$show_hist_plot) self$results$histPlots$get(key=var)$setState(data.frame(before=x_clean, after=x_trans_clean))
      }
      
      if (length(all_treated_vectors) > 0 && self$results$transformedVarsOutput$isNotFilled()) {
        keys <- names(all_treated_vectors)
        titles <- paste0(keys, self$options$suffix)
        self$results$transformedVarsOutput$set(
          keys=keys, 
          titles=titles, 
          descriptions=rep("Transformed variable", length(keys)), 
          measureTypes=rep("continuous", length(keys))
        )
        for (var in keys) self$results$transformedVarsOutput$setValues(key=var, values=all_treated_vectors[[var]])
      }
    },
    
    runShapiro = function(var, data_clean, moment, alpha) {
      n <- length(data_clean)
      if(n<3) return()
      if (n > 5000) {
        if (exists(".Random.seed", envir = .GlobalEnv, inherits = FALSE)) {
          old_seed <- get(".Random.seed", envir = .GlobalEnv, inherits = FALSE)
          on.exit(assign(".Random.seed", old_seed, envir = .GlobalEnv))
        }
        set.seed(12345)
        data_sw <- sample(data_clean, 5000)
      } else {
        data_sw <- data_clean
      }
      res <- stats::shapiro.test(data_sw)
      self$results$normalityTable$setRow(rowKey=paste0(var, "_", moment), values=list(W=res$statistic, p=res$p.value, result=ifelse(res$p.value > alpha, "Normal", "Non-Normal")))
    },
    
    .qqPlot = function(image, ggtheme, ...) {
      if (is.null(image$state)) return(FALSE)
      df <- image$state
      p1 <- ggplot2::ggplot(df, ggplot2::aes(sample=before)) + ggplot2::stat_qq(color="#336699") + ggplot2::stat_qq_line(color="red") + ggtheme
      p2 <- ggplot2::ggplot(df, ggplot2::aes(sample=after)) + ggplot2::stat_qq(color="#339966") + ggplot2::stat_qq_line(color="red") + ggtheme
      print(gridExtra::grid.arrange(p1, p2, ncol=2)); TRUE
    },
    
    .histPlot = function(image, ggtheme, ...) {
      if (is.null(image$state)) return(FALSE)
      df <- image$state
      p1 <- ggplot2::ggplot(df, ggplot2::aes(x=before)) + ggplot2::geom_histogram(fill="#336699", bins=30) + ggtheme
      p2 <- ggplot2::ggplot(df, ggplot2::aes(x=after)) + ggplot2::geom_histogram(fill="#339966", bins=30) + ggtheme
      print(gridExtra::grid.arrange(p1, p2, ncol=2)); TRUE
    }
  )
)