
# This file is automatically generated, you probably don't want to edit this

DDAOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "DDAOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            covs = NULL,
            prop = FALSE,
            coef = TRUE,
            structCoef = TRUE,
            gc = TRUE,
            plot = FALSE,
            width = 500,
            height = 500,
            discScores = FALSE,
            pairwiseES = FALSE, ...) {

            super$initialize(
                package="BSS",
                name="DDA",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..prop <- jmvcore::OptionBool$new(
                "prop",
                prop,
                default=FALSE)
            private$..coef <- jmvcore::OptionBool$new(
                "coef",
                coef,
                default=TRUE)
            private$..structCoef <- jmvcore::OptionBool$new(
                "structCoef",
                structCoef,
                default=TRUE)
            private$..gc <- jmvcore::OptionBool$new(
                "gc",
                gc,
                default=TRUE)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..width <- jmvcore::OptionInteger$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionInteger$new(
                "height",
                height,
                default=500)
            private$..discScores <- jmvcore::OptionBool$new(
                "discScores",
                discScores,
                default=FALSE)
            private$..pairwiseES <- jmvcore::OptionBool$new(
                "pairwiseES",
                pairwiseES,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..covs)
            self$.addOption(private$..prop)
            self$.addOption(private$..coef)
            self$.addOption(private$..structCoef)
            self$.addOption(private$..gc)
            self$.addOption(private$..plot)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..discScores)
            self$.addOption(private$..pairwiseES)
        }),
    active = list(
        dep = function() private$..dep$value,
        covs = function() private$..covs$value,
        prop = function() private$..prop$value,
        coef = function() private$..coef$value,
        structCoef = function() private$..structCoef$value,
        gc = function() private$..gc$value,
        plot = function() private$..plot$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        discScores = function() private$..discScores$value,
        pairwiseES = function() private$..pairwiseES$value),
    private = list(
        ..dep = NA,
        ..covs = NA,
        ..prop = NA,
        ..coef = NA,
        ..structCoef = NA,
        ..gc = NA,
        ..plot = NA,
        ..width = NA,
        ..height = NA,
        ..discScores = NA,
        ..pairwiseES = NA)
)

DDAResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "DDAResults",
    inherit = jmvcore::Group,
    active = list(
        prop = function() private$.items[["prop"]],
        coef = function() private$.items[["coef"]],
        structCoefTable = function() private$.items[["structCoefTable"]],
        gc = function() private$.items[["gc"]],
        plot = function() private$.items[["plot"]],
        discScoresTable = function() private$.items[["discScoresTable"]],
        pairwiseESTable = function() private$.items[["pairwiseESTable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Descriptive Discriminant Analysis")
            self$add(jmvcore::Table$new(
                options=options,
                name="prop",
                title="Proportion of trace",
                visible="(prop)",
                rows=1,
                clearWith=list(
                    "covs",
                    "dep"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="Proportion(%)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="coef",
                title="Coefficients of linear discriminants",
                refs="MASS",
                visible="(coef)",
                clearWith=list(
                    "covs",
                    "dep"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="structCoefTable",
                title="Structure Coefficients",
                visible="(structCoef)",
                refs=list(
                    "MASS"),
                clearWith=list(
                    "covs",
                    "dep"),
                columns=list(
                    list(
                        `name`="varName", 
                        `title`="", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="gc",
                title="Group centroids",
                refs="MASS",
                visible="(gc)",
                clearWith=list(
                    "covs",
                    "dep"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Groups", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Descriptive discriminant analysis plot",
                requiresData=TRUE,
                visible="(plot)",
                renderFun=".plot",
                clearWith=list(
                    "covs",
                    "dep",
                    "width",
                    "height")))
            self$add(jmvcore::Table$new(
                options=options,
                name="discScoresTable",
                title="Discriminant Scores",
                visible="(discScores)",
                refs=list(
                    "MASS"),
                clearWith=list(
                    "covs",
                    "dep"),
                columns=list(
                    list(
                        `name`="obs", 
                        `title`="Observation", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="pairwiseESTable",
                title="Pairwise Effect Sizes",
                visible="(pairwiseES)",
                refs=list(
                    "effsize"),
                clearWith=list(
                    "covs",
                    "dep"),
                columns=list(
                    list(
                        `name`="group1", 
                        `title`="Group 1", 
                        `type`="text"),
                    list(
                        `name`="group2", 
                        `title`="Group 2", 
                        `type`="text"),
                    list(
                        `name`="cohenD", 
                        `title`="Cohen's d", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="hedgesG", 
                        `title`="Hedges' g", 
                        `type`="number", 
                        `format`="zto"))))}))

DDABase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "DDABase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BSS",
                name = "DDA",
                version = c(1,0,0),
                options = options,
                results = DDAResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Descriptive Discriminant Analysis
#'
#' 
#' @param data .
#' @param dep .
#' @param covs .
#' @param prop .
#' @param coef .
#' @param structCoef .
#' @param gc .
#' @param plot .
#' @param width .
#' @param height .
#' @param discScores .
#' @param pairwiseES .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$prop} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$coef} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$structCoefTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$gc} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$discScoresTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pairwiseESTable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$prop$asDF}
#'
#' \code{as.data.frame(results$prop)}
#'
#' @export
DDA <- function(
    data,
    dep,
    covs,
    prop = FALSE,
    coef = TRUE,
    structCoef = TRUE,
    gc = TRUE,
    plot = FALSE,
    width = 500,
    height = 500,
    discScores = FALSE,
    pairwiseES = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("DDA requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(covs), covs, NULL))

    for (v in dep) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- DDAOptions$new(
        dep = dep,
        covs = covs,
        prop = prop,
        coef = coef,
        structCoef = structCoef,
        gc = gc,
        plot = plot,
        width = width,
        height = height,
        discScores = discScores,
        pairwiseES = pairwiseES)

    analysis <- DDAClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

