
# This file is automatically generated, you probably don't want to edit this

dixonQTestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dixonQTestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            var = NULL,
            group = NULL,
            alpha = "alpha05",
            treatment = "none",
            dispBox = FALSE, ...) {

            super$initialize(
                package="BSS",
                name="dixonQTest",
                requiresData=TRUE,
                ...)

            private$..var <- jmvcore::OptionVariable$new(
                "var",
                var,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariables$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..alpha <- jmvcore::OptionList$new(
                "alpha",
                alpha,
                options=list(
                    "alpha10",
                    "alpha05",
                    "alpha01"),
                default="alpha05")
            private$..treatment <- jmvcore::OptionList$new(
                "treatment",
                treatment,
                options=list(
                    "none",
                    "trim_asym",
                    "win_valid"),
                default="none")
            private$..dispBox <- jmvcore::OptionBool$new(
                "dispBox",
                dispBox,
                default=FALSE)
            private$..treatedData <- jmvcore::OptionOutput$new(
                "treatedData")

            self$.addOption(private$..var)
            self$.addOption(private$..group)
            self$.addOption(private$..alpha)
            self$.addOption(private$..treatment)
            self$.addOption(private$..dispBox)
            self$.addOption(private$..treatedData)
        }),
    active = list(
        var = function() private$..var$value,
        group = function() private$..group$value,
        alpha = function() private$..alpha$value,
        treatment = function() private$..treatment$value,
        dispBox = function() private$..dispBox$value,
        treatedData = function() private$..treatedData$value),
    private = list(
        ..var = NA,
        ..group = NA,
        ..alpha = NA,
        ..treatment = NA,
        ..dispBox = NA,
        ..treatedData = NA)
)

dixonQTestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dixonQTestResults",
    inherit = jmvcore::Group,
    active = list(
        dixonInfo = function() private$.items[["dixonInfo"]],
        dixonTable = function() private$.items[["dixonTable"]],
        outlierList = function() private$.items[["outlierList"]],
        plot = function() private$.items[["plot"]],
        treatedData = function() private$.items[["treatedData"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Outlier Detection Results")
            self$add(jmvcore::Html$new(
                options=options,
                name="dixonInfo",
                title="About Dixon's Q Test",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="dixonTable",
                title="Dixon's Q Test Results",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="group_level", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="outlier_value", 
                        `title`="Outlier Value", 
                        `type`="number"),
                    list(
                        `name`="outlier_side", 
                        `title`="Side", 
                        `type`="text"),
                    list(
                        `name`="q_statistic", 
                        `title`="Q Statistic", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="q_critical", 
                        `title`="Q Critical", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="significant", 
                        `title`="Outlier Detected", 
                        `type`="text"),
                    list(
                        `name`="treatmentApplied", 
                        `title`="Treatment Applied", 
                        `type`="text", 
                        `visible`="(treatment != 'none')"),
                    list(
                        `name`="modifiedN", 
                        `title`="Valid N (After Treatment)", 
                        `type`="integer", 
                        `visible`="(treatment != 'none')"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="outlierList",
                title="Identified Outliers",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="group_level", 
                        `title`="Group", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="rowNumber", 
                        `title`="Row", 
                        `type`="integer"),
                    list(
                        `name`="outlier_value", 
                        `title`="Value", 
                        `type`="number"),
                    list(
                        `name`="outlier_side", 
                        `title`="Side", 
                        `type`="text"),
                    list(
                        `name`="q_statistic", 
                        `title`="Q Statistic", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Boxplot",
                width=500,
                height=400,
                renderFun=".plot",
                visible="(dispBox)"))
            self$add(jmvcore::Output$new(
                options=options,
                name="treatedData",
                title="Treated Variable",
                initInRun=TRUE,
                clearWith=list(
                    "var",
                    "group",
                    "alpha",
                    "treatment")))}))

dixonQTestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dixonQTestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BSS",
                name = "dixonQTest",
                version = c(1,0,0),
                options = options,
                results = dixonQTestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Dixon's Q Test
#'
#' 
#' @param data .
#' @param var .
#' @param group .
#' @param alpha .
#' @param treatment .
#' @param dispBox .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$dixonInfo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$dixonTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$outlierList} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$treatedData} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$dixonTable$asDF}
#'
#' \code{as.data.frame(results$dixonTable)}
#'
#' @export
dixonQTest <- function(
    data,
    var,
    group = NULL,
    alpha = "alpha05",
    treatment = "none",
    dispBox = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("dixonQTest requires jmvcore to be installed (restart may be required)")

    if ( ! missing(var)) var <- jmvcore::resolveQuo(jmvcore::enquo(var))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(var), var, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- dixonQTestOptions$new(
        var = var,
        group = group,
        alpha = alpha,
        treatment = treatment,
        dispBox = dispBox)

    analysis <- dixonQTestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

