
# This file is automatically generated, you probably don't want to edit this

effectSizeCalculationOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "effectSizeCalculationOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            test_type = "Friedman",
            chi_square_value = 0,
            df = 1,
            sample_size = 0,
            num_conditions = 2, ...) {

            super$initialize(
                package="BSS",
                name="effectSizeCalculation",
                requiresData=FALSE,
                ...)

            private$..test_type <- jmvcore::OptionList$new(
                "test_type",
                test_type,
                options=list(
                    "Friedman",
                    "McNemar"),
                default="Friedman")
            private$..chi_square_value <- jmvcore::OptionNumber$new(
                "chi_square_value",
                chi_square_value,
                default=0)
            private$..df <- jmvcore::OptionInteger$new(
                "df",
                df,
                default=1)
            private$..sample_size <- jmvcore::OptionInteger$new(
                "sample_size",
                sample_size,
                default=0)
            private$..num_conditions <- jmvcore::OptionInteger$new(
                "num_conditions",
                num_conditions,
                default=2)

            self$.addOption(private$..test_type)
            self$.addOption(private$..chi_square_value)
            self$.addOption(private$..df)
            self$.addOption(private$..sample_size)
            self$.addOption(private$..num_conditions)
        }),
    active = list(
        test_type = function() private$..test_type$value,
        chi_square_value = function() private$..chi_square_value$value,
        df = function() private$..df$value,
        sample_size = function() private$..sample_size$value,
        num_conditions = function() private$..num_conditions$value),
    private = list(
        ..test_type = NA,
        ..chi_square_value = NA,
        ..df = NA,
        ..sample_size = NA,
        ..num_conditions = NA)
)

effectSizeCalculationResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "effectSizeCalculationResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        effectSizeTable = function() private$.items[["effectSizeTable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Effect Size Calculation")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Effect Size"))
            self$add(jmvcore::Table$new(
                options=options,
                name="effectSizeTable",
                title="Effect Size Calculation Results",
                rows="(test_type)",
                visible=TRUE,
                columns=list(
                    list(
                        `name`="test_type", 
                        `title`="Test Type", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="chi_square_value", 
                        `title`="Chi-Square (\u03C7\u00B2)", 
                        `type`="number", 
                        `visible`=TRUE),
                    list(
                        `name`="df", 
                        `title`="Degrees of Freedom (df)", 
                        `type`="integer", 
                        `visible`=TRUE),
                    list(
                        `name`="sample_size", 
                        `title`="Sample Size (n)", 
                        `type`="integer", 
                        `visible`=TRUE),
                    list(
                        `name`="num_conditions", 
                        `title`="Number of Conditions (k)", 
                        `type`="integer", 
                        `visible`="(test_type == \"Friedman\")"),
                    list(
                        `name`="effect_size", 
                        `title`="Effect Size", 
                        `type`="number", 
                        `visible`=TRUE),
                    list(
                        `name`="interpretation", 
                        `title`="Interpretation", 
                        `type`="text", 
                        `visible`=TRUE))))}))

effectSizeCalculationBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "effectSizeCalculationBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BSS",
                name = "effectSizeCalculation",
                version = c(0,0,1),
                options = options,
                results = effectSizeCalculationResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Non-parametric tests
#'
#' 
#' @param test_type .
#' @param chi_square_value .
#' @param df .
#' @param sample_size .
#' @param num_conditions .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$effectSizeTable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$effectSizeTable$asDF}
#'
#' \code{as.data.frame(results$effectSizeTable)}
#'
#' @export
effectSizeCalculation <- function(
    test_type = "Friedman",
    chi_square_value = 0,
    df = 1,
    sample_size = 0,
    num_conditions = 2) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("effectSizeCalculation requires jmvcore to be installed (restart may be required)")


    options <- effectSizeCalculationOptions$new(
        test_type = test_type,
        chi_square_value = chi_square_value,
        df = df,
        sample_size = sample_size,
        num_conditions = num_conditions)

    analysis <- effectSizeCalculationClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

