
# This file is automatically generated, you probably don't want to edit this

effectSizeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "effectSizeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mode = "cross_sectional",
            dep_vars_cs = NULL,
            indep_vars_cs = NULL,
            cov = NULL,
            dep_vars_long = NULL,
            indep_vars_long = NULL,
            cov_long = NULL,
            subject_id_var = NULL,
            time_var = NULL,
            wave_vars = NULL,
            long_format = "wide",
            include_interactions = FALSE,
            run_analysis = FALSE,
            es_method = "cohens_d",
            show_cles = FALSE,
            reference_group = "",
            es_method_long = "cohens_dz",
            show_cles_long = FALSE,
            reference_group_long = "",
            use_glm = FALSE,
            es_glm = "glm_gaussian",
            ci_method = "analytical",
            n_bootstrap = 1000,
            ci_level = "ci_95", ...) {

            super$initialize(
                package="BSS",
                name="effectSize",
                requiresData=TRUE,
                ...)

            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "cross_sectional",
                    "longitudinal"),
                default="cross_sectional")
            private$..dep_vars_cs <- jmvcore::OptionVariables$new(
                "dep_vars_cs",
                dep_vars_cs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..indep_vars_cs <- jmvcore::OptionVariables$new(
                "indep_vars_cs",
                indep_vars_cs,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..cov <- jmvcore::OptionVariable$new(
                "cov",
                cov,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..dep_vars_long <- jmvcore::OptionVariables$new(
                "dep_vars_long",
                dep_vars_long,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..indep_vars_long <- jmvcore::OptionVariables$new(
                "indep_vars_long",
                indep_vars_long,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..cov_long <- jmvcore::OptionVariable$new(
                "cov_long",
                cov_long,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..subject_id_var <- jmvcore::OptionVariable$new(
                "subject_id_var",
                subject_id_var,
                suggested=list(
                    "nominal",
                    "id"),
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..time_var <- jmvcore::OptionVariable$new(
                "time_var",
                time_var,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..wave_vars <- jmvcore::OptionVariables$new(
                "wave_vars",
                wave_vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..long_format <- jmvcore::OptionList$new(
                "long_format",
                long_format,
                options=list(
                    "wide",
                    "long"),
                default="wide")
            private$..include_interactions <- jmvcore::OptionBool$new(
                "include_interactions",
                include_interactions,
                default=FALSE)
            private$..run_analysis <- jmvcore::OptionBool$new(
                "run_analysis",
                run_analysis,
                default=FALSE)
            private$..es_method <- jmvcore::OptionList$new(
                "es_method",
                es_method,
                options=list(
                    "cohens_d",
                    "hedges_g",
                    "glass_delta",
                    "rank_biserial"),
                default="cohens_d")
            private$..show_cles <- jmvcore::OptionBool$new(
                "show_cles",
                show_cles,
                default=FALSE)
            private$..reference_group <- jmvcore::OptionString$new(
                "reference_group",
                reference_group,
                default="")
            private$..es_method_long <- jmvcore::OptionList$new(
                "es_method_long",
                es_method_long,
                options=list(
                    "cohens_dz",
                    "hedges_gz",
                    "glass_dz",
                    "rank_biserial_paired"),
                default="cohens_dz")
            private$..show_cles_long <- jmvcore::OptionBool$new(
                "show_cles_long",
                show_cles_long,
                default=FALSE)
            private$..reference_group_long <- jmvcore::OptionString$new(
                "reference_group_long",
                reference_group_long,
                default="")
            private$..use_glm <- jmvcore::OptionBool$new(
                "use_glm",
                use_glm,
                default=FALSE)
            private$..es_glm <- jmvcore::OptionList$new(
                "es_glm",
                es_glm,
                options=list(
                    "glm_gaussian",
                    "glm_gamma",
                    "glm_inv_gaussian"),
                default="glm_gaussian")
            private$..ci_method <- jmvcore::OptionList$new(
                "ci_method",
                ci_method,
                options=list(
                    "analytical",
                    "bootstrap"),
                default="analytical")
            private$..n_bootstrap <- jmvcore::OptionInteger$new(
                "n_bootstrap",
                n_bootstrap,
                default=1000,
                min=100,
                max=10000)
            private$..ci_level <- jmvcore::OptionList$new(
                "ci_level",
                ci_level,
                options=list(
                    "ci_95",
                    "ci_90",
                    "ci_99"),
                default="ci_95")

            self$.addOption(private$..mode)
            self$.addOption(private$..dep_vars_cs)
            self$.addOption(private$..indep_vars_cs)
            self$.addOption(private$..cov)
            self$.addOption(private$..dep_vars_long)
            self$.addOption(private$..indep_vars_long)
            self$.addOption(private$..cov_long)
            self$.addOption(private$..subject_id_var)
            self$.addOption(private$..time_var)
            self$.addOption(private$..wave_vars)
            self$.addOption(private$..long_format)
            self$.addOption(private$..include_interactions)
            self$.addOption(private$..run_analysis)
            self$.addOption(private$..es_method)
            self$.addOption(private$..show_cles)
            self$.addOption(private$..reference_group)
            self$.addOption(private$..es_method_long)
            self$.addOption(private$..show_cles_long)
            self$.addOption(private$..reference_group_long)
            self$.addOption(private$..use_glm)
            self$.addOption(private$..es_glm)
            self$.addOption(private$..ci_method)
            self$.addOption(private$..n_bootstrap)
            self$.addOption(private$..ci_level)
        }),
    active = list(
        mode = function() private$..mode$value,
        dep_vars_cs = function() private$..dep_vars_cs$value,
        indep_vars_cs = function() private$..indep_vars_cs$value,
        cov = function() private$..cov$value,
        dep_vars_long = function() private$..dep_vars_long$value,
        indep_vars_long = function() private$..indep_vars_long$value,
        cov_long = function() private$..cov_long$value,
        subject_id_var = function() private$..subject_id_var$value,
        time_var = function() private$..time_var$value,
        wave_vars = function() private$..wave_vars$value,
        long_format = function() private$..long_format$value,
        include_interactions = function() private$..include_interactions$value,
        run_analysis = function() private$..run_analysis$value,
        es_method = function() private$..es_method$value,
        show_cles = function() private$..show_cles$value,
        reference_group = function() private$..reference_group$value,
        es_method_long = function() private$..es_method_long$value,
        show_cles_long = function() private$..show_cles_long$value,
        reference_group_long = function() private$..reference_group_long$value,
        use_glm = function() private$..use_glm$value,
        es_glm = function() private$..es_glm$value,
        ci_method = function() private$..ci_method$value,
        n_bootstrap = function() private$..n_bootstrap$value,
        ci_level = function() private$..ci_level$value),
    private = list(
        ..mode = NA,
        ..dep_vars_cs = NA,
        ..indep_vars_cs = NA,
        ..cov = NA,
        ..dep_vars_long = NA,
        ..indep_vars_long = NA,
        ..cov_long = NA,
        ..subject_id_var = NA,
        ..time_var = NA,
        ..wave_vars = NA,
        ..long_format = NA,
        ..include_interactions = NA,
        ..run_analysis = NA,
        ..es_method = NA,
        ..show_cles = NA,
        ..reference_group = NA,
        ..es_method_long = NA,
        ..show_cles_long = NA,
        ..reference_group_long = NA,
        ..use_glm = NA,
        ..es_glm = NA,
        ..ci_method = NA,
        ..n_bootstrap = NA,
        ..ci_level = NA)
)

effectSizeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "effectSizeResults",
    inherit = jmvcore::Group,
    active = list(
        analysisInfo = function() private$.items[["analysisInfo"]],
        ameBenchmark = function() private$.items[["ameBenchmark"]],
        effectSizeTable = function() private$.items[["effectSizeTable"]],
        effectSizeTableLongBetween = function() private$.items[["effectSizeTableLongBetween"]],
        clesTable = function() private$.items[["clesTable"]],
        clesLongTable = function() private$.items[["clesLongTable"]],
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Effect Size")
            self$add(jmvcore::Html$new(
                options=options,
                name="analysisInfo",
                title="About Effect Size Analysis",
                visible=TRUE))
            self$add(jmvcore::Html$new(
                options=options,
                name="ameBenchmark",
                title="AME Interpretation Benchmark",
                visible="(use_glm)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="effectSizeTable",
                title="Within-Subjects Effect Sizes (Time Effects)",
                visible="(run_analysis)",
                refs=list(
                    "effectsize",
                    "emmeans"),
                clearWith=list(
                    "mode",
                    "dep_vars_cs",
                    "indep_vars_cs",
                    "dep_vars_long",
                    "indep_vars_long",
                    "include_interactions",
                    "es_method",
                    "reference_group",
                    "use_glm",
                    "es_glm",
                    "ci_method",
                    "n_bootstrap",
                    "ci_level",
                    "run_analysis",
                    "long_format",
                    "time_var",
                    "wave_vars",
                    "subject_id_var",
                    "es_method_long",
                    "reference_group_long",
                    "cov",
                    "cov_long"),
                columns=list(
                    list(
                        `name`="dv", 
                        `title`="DV", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="iv", 
                        `title`="IV", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="comparison", 
                        `title`="Comparison", 
                        `type`="text"),
                    list(
                        `name`="method", 
                        `title`="Method", 
                        `type`="text"),
                    list(
                        `name`="es_value", 
                        `title`="Effect Size", 
                        `type`="number", 
                        `format`="dp:3"),
                    list(
                        `name`="ci_lower", 
                        `title`="CI Lower", 
                        `type`="number", 
                        `format`="dp:3"),
                    list(
                        `name`="ci_upper", 
                        `title`="CI Upper", 
                        `type`="number", 
                        `format`="dp:3"),
                    list(
                        `name`="interpretation", 
                        `title`="Interpretation", 
                        `type`="text"),
                    list(
                        `name`="n_obs", 
                        `title`="N", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="effectSizeTableLongBetween",
                title="Between-Subjects Effect Sizes (Group Differences)",
                visible="(run_analysis && mode == 'longitudinal')",
                refs=list(
                    "effectsize",
                    "emmeans"),
                clearWith=list(
                    "mode",
                    "dep_vars_long",
                    "indep_vars_long",
                    "include_interactions",
                    "es_method",
                    "ci_method",
                    "n_bootstrap",
                    "ci_level",
                    "run_analysis",
                    "long_format",
                    "wave_vars",
                    "time_var",
                    "cov",
                    "cov_long"),
                columns=list(
                    list(
                        `name`="dv", 
                        `title`="Time Point", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="iv", 
                        `title`="Grouping Variable", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="comparison", 
                        `title`="Comparison", 
                        `type`="text"),
                    list(
                        `name`="method", 
                        `title`="Method", 
                        `type`="text"),
                    list(
                        `name`="es_value", 
                        `title`="Effect Size", 
                        `type`="number", 
                        `format`="dp:3"),
                    list(
                        `name`="ci_lower", 
                        `title`="CI Lower", 
                        `type`="number", 
                        `format`="dp:3"),
                    list(
                        `name`="ci_upper", 
                        `title`="CI Upper", 
                        `type`="number", 
                        `format`="dp:3"),
                    list(
                        `name`="interpretation", 
                        `title`="Interpretation", 
                        `type`="text"),
                    list(
                        `name`="n_obs", 
                        `title`="N", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="clesTable",
                title="Common Language Effect Size (CLES) - Independent Samples",
                visible="(run_analysis && mode == 'cross_sectional' && show_cles)",
                refs=list(
                    "effectsize",
                    "emmeans"),
                clearWith=list(
                    "mode",
                    "dep_vars_cs",
                    "indep_vars_cs",
                    "include_interactions",
                    "es_method",
                    "reference_group",
                    "use_glm",
                    "es_glm",
                    "ci_method",
                    "n_bootstrap",
                    "ci_level",
                    "run_analysis",
                    "show_cles",
                    "cov",
                    "cov_long"),
                columns=list(
                    list(
                        `name`="dv", 
                        `title`="DV", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="iv", 
                        `title`="IV", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="comparison", 
                        `title`="Comparison", 
                        `type`="text"),
                    list(
                        `name`="cles", 
                        `title`="CLES", 
                        `type`="number", 
                        `format`="dp:3"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="clesLongTable",
                title="Common Language Effect Size (CLES) - Paired Samples",
                visible="(run_analysis && mode == 'longitudinal' && show_cles_long)",
                refs=list(
                    "effectsize",
                    "emmeans"),
                clearWith=list(
                    "mode",
                    "run_analysis",
                    "dep_vars_long",
                    "indep_vars_long",
                    "long_format",
                    "time_var",
                    "wave_vars",
                    "subject_id_var",
                    "es_method_long",
                    "reference_group_long",
                    "show_cles_long",
                    "cov",
                    "cov_long"),
                columns=list(
                    list(
                        `name`="dv", 
                        `title`="DV", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="comparison", 
                        `title`="Comparison", 
                        `type`="text"),
                    list(
                        `name`="cles", 
                        `title`="CLES (paired)", 
                        `type`="number", 
                        `format`="dp:3"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Analysis Summary",
                visible=FALSE,
                clearWith=list(
                    "mode",
                    "dep_vars_cs",
                    "indep_vars_cs",
                    "dep_vars_long",
                    "indep_vars_long",
                    "include_interactions",
                    "es_method",
                    "reference_group",
                    "use_glm",
                    "es_glm",
                    "ci_method",
                    "n_bootstrap",
                    "ci_level",
                    "run_analysis",
                    "long_format",
                    "time_var",
                    "wave_vars",
                    "subject_id_var",
                    "es_method_long",
                    "reference_group_long")))}))

effectSizeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "effectSizeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BSS",
                name = "effectSize",
                version = c(0,0,1),
                options = options,
                results = effectSizeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Effect Size Calculation
#'
#' 
#' @param data .
#' @param mode .
#' @param dep_vars_cs .
#' @param indep_vars_cs .
#' @param cov .
#' @param dep_vars_long .
#' @param indep_vars_long .
#' @param cov_long .
#' @param subject_id_var .
#' @param time_var .
#' @param wave_vars .
#' @param long_format .
#' @param include_interactions .
#' @param run_analysis .
#' @param es_method .
#' @param show_cles .
#' @param reference_group .
#' @param es_method_long .
#' @param show_cles_long .
#' @param reference_group_long .
#' @param use_glm .
#' @param es_glm .
#' @param ci_method .
#' @param n_bootstrap .
#' @param ci_level .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$analysisInfo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$ameBenchmark} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$effectSizeTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$effectSizeTableLongBetween} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$clesTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$clesLongTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$effectSizeTable$asDF}
#'
#' \code{as.data.frame(results$effectSizeTable)}
#'
#' @export
effectSize <- function(
    data,
    mode = "cross_sectional",
    dep_vars_cs,
    indep_vars_cs,
    cov,
    dep_vars_long,
    indep_vars_long,
    cov_long,
    subject_id_var,
    time_var,
    wave_vars,
    long_format = "wide",
    include_interactions = FALSE,
    run_analysis = FALSE,
    es_method = "cohens_d",
    show_cles = FALSE,
    reference_group = "",
    es_method_long = "cohens_dz",
    show_cles_long = FALSE,
    reference_group_long = "",
    use_glm = FALSE,
    es_glm = "glm_gaussian",
    ci_method = "analytical",
    n_bootstrap = 1000,
    ci_level = "ci_95") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("effectSize requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep_vars_cs)) dep_vars_cs <- jmvcore::resolveQuo(jmvcore::enquo(dep_vars_cs))
    if ( ! missing(indep_vars_cs)) indep_vars_cs <- jmvcore::resolveQuo(jmvcore::enquo(indep_vars_cs))
    if ( ! missing(cov)) cov <- jmvcore::resolveQuo(jmvcore::enquo(cov))
    if ( ! missing(dep_vars_long)) dep_vars_long <- jmvcore::resolveQuo(jmvcore::enquo(dep_vars_long))
    if ( ! missing(indep_vars_long)) indep_vars_long <- jmvcore::resolveQuo(jmvcore::enquo(indep_vars_long))
    if ( ! missing(cov_long)) cov_long <- jmvcore::resolveQuo(jmvcore::enquo(cov_long))
    if ( ! missing(subject_id_var)) subject_id_var <- jmvcore::resolveQuo(jmvcore::enquo(subject_id_var))
    if ( ! missing(time_var)) time_var <- jmvcore::resolveQuo(jmvcore::enquo(time_var))
    if ( ! missing(wave_vars)) wave_vars <- jmvcore::resolveQuo(jmvcore::enquo(wave_vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep_vars_cs), dep_vars_cs, NULL),
            `if`( ! missing(indep_vars_cs), indep_vars_cs, NULL),
            `if`( ! missing(cov), cov, NULL),
            `if`( ! missing(dep_vars_long), dep_vars_long, NULL),
            `if`( ! missing(indep_vars_long), indep_vars_long, NULL),
            `if`( ! missing(cov_long), cov_long, NULL),
            `if`( ! missing(subject_id_var), subject_id_var, NULL),
            `if`( ! missing(time_var), time_var, NULL),
            `if`( ! missing(wave_vars), wave_vars, NULL))


    options <- effectSizeOptions$new(
        mode = mode,
        dep_vars_cs = dep_vars_cs,
        indep_vars_cs = indep_vars_cs,
        cov = cov,
        dep_vars_long = dep_vars_long,
        indep_vars_long = indep_vars_long,
        cov_long = cov_long,
        subject_id_var = subject_id_var,
        time_var = time_var,
        wave_vars = wave_vars,
        long_format = long_format,
        include_interactions = include_interactions,
        run_analysis = run_analysis,
        es_method = es_method,
        show_cles = show_cles,
        reference_group = reference_group,
        es_method_long = es_method_long,
        show_cles_long = show_cles_long,
        reference_group_long = reference_group_long,
        use_glm = use_glm,
        es_glm = es_glm,
        ci_method = ci_method,
        n_bootstrap = n_bootstrap,
        ci_level = ci_level)

    analysis <- effectSizeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

