
# This file is automatically generated, you probably don't want to edit this

finiteSampleSizeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "finiteSampleSizeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            method = "Cochran",
            population_size = 1000,
            confidence_level = 95,
            margin_error = 5,
            population_proportion = 0.5,
            correction = FALSE, ...) {

            super$initialize(
                package="BSS",
                name="finiteSampleSize",
                requiresData=FALSE,
                ...)

            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "Cochran",
                    "Slovin"),
                default="Cochran")
            private$..population_size <- jmvcore::OptionInteger$new(
                "population_size",
                population_size,
                default=1000)
            private$..confidence_level <- jmvcore::OptionNumber$new(
                "confidence_level",
                confidence_level,
                default=95)
            private$..margin_error <- jmvcore::OptionNumber$new(
                "margin_error",
                margin_error,
                default=5)
            private$..population_proportion <- jmvcore::OptionNumber$new(
                "population_proportion",
                population_proportion,
                default=0.5)
            private$..correction <- jmvcore::OptionBool$new(
                "correction",
                correction,
                default=FALSE)

            self$.addOption(private$..method)
            self$.addOption(private$..population_size)
            self$.addOption(private$..confidence_level)
            self$.addOption(private$..margin_error)
            self$.addOption(private$..population_proportion)
            self$.addOption(private$..correction)
        }),
    active = list(
        method = function() private$..method$value,
        population_size = function() private$..population_size$value,
        confidence_level = function() private$..confidence_level$value,
        margin_error = function() private$..margin_error$value,
        population_proportion = function() private$..population_proportion$value,
        correction = function() private$..correction$value),
    private = list(
        ..method = NA,
        ..population_size = NA,
        ..confidence_level = NA,
        ..margin_error = NA,
        ..population_proportion = NA,
        ..correction = NA)
)

finiteSampleSizeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "finiteSampleSizeResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        sampleSizeTable = function() private$.items[["sampleSizeTable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Finite Population Sample Size Calculation")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Finite Population Sample Size Calculation"))
            self$add(jmvcore::Table$new(
                options=options,
                name="sampleSizeTable",
                title="Sample Size Calculation Results",
                rows="(method)",
                visible=TRUE,
                columns=list(
                    list(
                        `name`="method", 
                        `title`="Method", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="population_size", 
                        `title`="Population Size (N)", 
                        `type`="integer", 
                        `visible`=TRUE),
                    list(
                        `name`="confidence_level", 
                        `title`="Confidence Level (%)", 
                        `type`="number", 
                        `visible`=TRUE),
                    list(
                        `name`="margin_error", 
                        `title`="Margin of Error (%)", 
                        `type`="number", 
                        `visible`=TRUE),
                    list(
                        `name`="population_proportion", 
                        `title`="Population Proportion (p)", 
                        `type`="number", 
                        `visible`="(method == \"Cochran\")"),
                    list(
                        `name`="sample_size", 
                        `title`="Sample Size (n)", 
                        `type`="integer", 
                        `visible`=TRUE),
                    list(
                        `name`="correction_applied", 
                        `title`="Small Sample Correction Applied", 
                        `type`="text", 
                        `visible`=TRUE))))}))

finiteSampleSizeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "finiteSampleSizeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BSS",
                name = "finiteSampleSize",
                version = c(0,0,1),
                options = options,
                results = finiteSampleSizeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Finite Population
#'
#' 
#' @param method .
#' @param population_size .
#' @param confidence_level .
#' @param margin_error .
#' @param population_proportion .
#' @param correction .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$sampleSizeTable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$sampleSizeTable$asDF}
#'
#' \code{as.data.frame(results$sampleSizeTable)}
#'
#' @export
finiteSampleSize <- function(
    method = "Cochran",
    population_size = 1000,
    confidence_level = 95,
    margin_error = 5,
    population_proportion = 0.5,
    correction = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("finiteSampleSize requires jmvcore to be installed (restart may be required)")


    options <- finiteSampleSizeOptions$new(
        method = method,
        population_size = population_size,
        confidence_level = confidence_level,
        margin_error = margin_error,
        population_proportion = population_proportion,
        correction = correction)

    analysis <- finiteSampleSizeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

