
# This file is automatically generated, you probably don't want to edit this

mgmOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mgmOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varsCont = NULL,
            varsCat = NULL,
            varsCount = NULL,
            groupVar = NULL,
            nodeGroupVar = NULL,
            lambdaSelMethod = "EBIC",
            kFolds = 3,
            lambdaGam = 0.5,
            ruleReg = "AND",
            tableCentrality = TRUE,
            tableClustering = FALSE,
            tableWeights = FALSE,
            plotCentrality = FALSE,
            plotClustering = FALSE,
            plotNetwork = TRUE,
            layoutAlgorithm = "spring",
            showLabels = TRUE,
            plotWidth = 500,
            plotHeight = 500, ...) {

            super$initialize(
                package="BSS",
                name="mgm",
                requiresData=TRUE,
                ...)

            private$..varsCont <- jmvcore::OptionVariables$new(
                "varsCont",
                varsCont,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..varsCat <- jmvcore::OptionVariables$new(
                "varsCat",
                varsCat,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..varsCount <- jmvcore::OptionVariables$new(
                "varsCount",
                varsCount,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..groupVar <- jmvcore::OptionVariable$new(
                "groupVar",
                groupVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..nodeGroupVar <- jmvcore::OptionVariable$new(
                "nodeGroupVar",
                nodeGroupVar,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor",
                    "id"),
                default=NULL)
            private$..lambdaSelMethod <- jmvcore::OptionList$new(
                "lambdaSelMethod",
                lambdaSelMethod,
                options=list(
                    "EBIC",
                    "CV"),
                default="EBIC")
            private$..kFolds <- jmvcore::OptionInteger$new(
                "kFolds",
                kFolds,
                default=3,
                min=2)
            private$..lambdaGam <- jmvcore::OptionNumber$new(
                "lambdaGam",
                lambdaGam,
                default=0.5,
                min=0,
                max=1)
            private$..ruleReg <- jmvcore::OptionList$new(
                "ruleReg",
                ruleReg,
                options=list(
                    "AND",
                    "OR"),
                default="AND")
            private$..tableCentrality <- jmvcore::OptionBool$new(
                "tableCentrality",
                tableCentrality,
                default=TRUE)
            private$..tableClustering <- jmvcore::OptionBool$new(
                "tableClustering",
                tableClustering,
                default=FALSE)
            private$..tableWeights <- jmvcore::OptionBool$new(
                "tableWeights",
                tableWeights,
                default=FALSE)
            private$..plotCentrality <- jmvcore::OptionBool$new(
                "plotCentrality",
                plotCentrality,
                default=FALSE)
            private$..plotClustering <- jmvcore::OptionBool$new(
                "plotClustering",
                plotClustering,
                default=FALSE)
            private$..plotNetwork <- jmvcore::OptionBool$new(
                "plotNetwork",
                plotNetwork,
                default=TRUE)
            private$..layoutAlgorithm <- jmvcore::OptionList$new(
                "layoutAlgorithm",
                layoutAlgorithm,
                options=list(
                    "spring",
                    "circle"),
                default="spring")
            private$..showLabels <- jmvcore::OptionBool$new(
                "showLabels",
                showLabels,
                default=TRUE)
            private$..plotWidth <- jmvcore::OptionInteger$new(
                "plotWidth",
                plotWidth,
                default=500)
            private$..plotHeight <- jmvcore::OptionInteger$new(
                "plotHeight",
                plotHeight,
                default=500)

            self$.addOption(private$..varsCont)
            self$.addOption(private$..varsCat)
            self$.addOption(private$..varsCount)
            self$.addOption(private$..groupVar)
            self$.addOption(private$..nodeGroupVar)
            self$.addOption(private$..lambdaSelMethod)
            self$.addOption(private$..kFolds)
            self$.addOption(private$..lambdaGam)
            self$.addOption(private$..ruleReg)
            self$.addOption(private$..tableCentrality)
            self$.addOption(private$..tableClustering)
            self$.addOption(private$..tableWeights)
            self$.addOption(private$..plotCentrality)
            self$.addOption(private$..plotClustering)
            self$.addOption(private$..plotNetwork)
            self$.addOption(private$..layoutAlgorithm)
            self$.addOption(private$..showLabels)
            self$.addOption(private$..plotWidth)
            self$.addOption(private$..plotHeight)
        }),
    active = list(
        varsCont = function() private$..varsCont$value,
        varsCat = function() private$..varsCat$value,
        varsCount = function() private$..varsCount$value,
        groupVar = function() private$..groupVar$value,
        nodeGroupVar = function() private$..nodeGroupVar$value,
        lambdaSelMethod = function() private$..lambdaSelMethod$value,
        kFolds = function() private$..kFolds$value,
        lambdaGam = function() private$..lambdaGam$value,
        ruleReg = function() private$..ruleReg$value,
        tableCentrality = function() private$..tableCentrality$value,
        tableClustering = function() private$..tableClustering$value,
        tableWeights = function() private$..tableWeights$value,
        plotCentrality = function() private$..plotCentrality$value,
        plotClustering = function() private$..plotClustering$value,
        plotNetwork = function() private$..plotNetwork$value,
        layoutAlgorithm = function() private$..layoutAlgorithm$value,
        showLabels = function() private$..showLabels$value,
        plotWidth = function() private$..plotWidth$value,
        plotHeight = function() private$..plotHeight$value),
    private = list(
        ..varsCont = NA,
        ..varsCat = NA,
        ..varsCount = NA,
        ..groupVar = NA,
        ..nodeGroupVar = NA,
        ..lambdaSelMethod = NA,
        ..kFolds = NA,
        ..lambdaGam = NA,
        ..ruleReg = NA,
        ..tableCentrality = NA,
        ..tableClustering = NA,
        ..tableWeights = NA,
        ..plotCentrality = NA,
        ..plotClustering = NA,
        ..plotNetwork = NA,
        ..layoutAlgorithm = NA,
        ..showLabels = NA,
        ..plotWidth = NA,
        ..plotHeight = NA)
)

mgmResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mgmResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        summary = function() private$.items[["summary"]],
        centrality = function() private$.items[["centrality"]],
        clustering = function() private$.items[["clustering"]],
        weights = function() private$.items[["weights"]],
        centralityPlot = function() private$.items[["centralityPlot"]],
        clusteringPlot = function() private$.items[["clusteringPlot"]],
        networkPlot = function() private$.items[["networkPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Network Analysis mgm")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="instructions",
                title=" ",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="summary",
                title="Network Summary",
                refs=list(
                    "mgm"),
                clearWith=list(
                    "varsCont",
                    "varsCat",
                    "varsCount",
                    "groupVar",
                    "nodeGroupVar",
                    "lambdaSelMethod",
                    "kFolds",
                    "lambdaGam",
                    "ruleReg"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(groupVar)"),
                    list(
                        `name`="nodes", 
                        `title`="Nodes", 
                        `type`="integer"),
                    list(
                        `name`="edges", 
                        `title`="Edges (Non-zero)", 
                        `type`="text"),
                    list(
                        `name`="sparsity", 
                        `title`="Sparsity", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="centrality",
                title="Centrality Measures",
                visible="(tableCentrality)",
                refs=list(
                    "mgm",
                    "qgraph"),
                clearWith=list(
                    "varsCont",
                    "varsCat",
                    "varsCount",
                    "groupVar",
                    "nodeGroupVar",
                    "lambdaSelMethod",
                    "kFolds",
                    "lambdaGam",
                    "ruleReg"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(groupVar)"),
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text", 
                        `format`="string"),
                    list(
                        `name`="strength", 
                        `title`="Strength", 
                        `type`="number"),
                    list(
                        `name`="closeness", 
                        `title`="Closeness", 
                        `type`="number"),
                    list(
                        `name`="betweenness", 
                        `title`="Betweenness", 
                        `type`="number"),
                    list(
                        `name`="expectedInfluence", 
                        `title`="Expected Influence", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="clustering",
                title="Clustering Measures per Variable",
                visible="(tableClustering)",
                refs=list(
                    "qgraph",
                    "igraph"),
                clearWith=list(
                    "varsCont",
                    "varsCat",
                    "varsCount",
                    "groupVar",
                    "nodeGroupVar",
                    "lambdaSelMethod",
                    "kFolds",
                    "lambdaGam",
                    "ruleReg"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(groupVar)"),
                    list(
                        `name`="node", 
                        `title`="Variable", 
                        `type`="text", 
                        `format`="string"),
                    list(
                        `name`="Barrat", 
                        `title`="Barrat", 
                        `type`="number"),
                    list(
                        `name`="Onnela", 
                        `title`="Onnela", 
                        `type`="number"),
                    list(
                        `name`="WS", 
                        `title`="WS", 
                        `type`="number"),
                    list(
                        `name`="Zhang", 
                        `title`="Zhang", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="weights",
                title="Weights (Adjacency Matrix)",
                visible="(tableWeights)",
                refs=list(
                    "mgm"),
                clearWith=list(
                    "varsCont",
                    "varsCat",
                    "varsCount",
                    "groupVar",
                    "nodeGroupVar",
                    "lambdaSelMethod",
                    "kFolds",
                    "lambdaGam",
                    "ruleReg"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(groupVar)"),
                    list(
                        `name`="rowname", 
                        `title`="", 
                        `type`="text", 
                        `format`="string"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="centralityPlot",
                title="Centrality Plot",
                requiresData=TRUE,
                visible="(plotCentrality)",
                renderFun=".plotCentrality",
                refs=list(
                    "qgraph",
                    "ggplot2",
                    "reshape2",
                    "gtools",
                    "dplyr"),
                clearWith=list(
                    "varsCont",
                    "varsCat",
                    "varsCount",
                    "groupVar",
                    "nodeGroupVar",
                    "lambdaSelMethod",
                    "kFolds",
                    "lambdaGam",
                    "ruleReg")))
            self$add(jmvcore::Image$new(
                options=options,
                name="clusteringPlot",
                title="Clustering Plot",
                requiresData=TRUE,
                visible="(plotClustering)",
                renderFun=".plotClustering",
                refs=list(
                    "igraph",
                    "ggplot2",
                    "reshape2",
                    "gtools",
                    "dplyr"),
                clearWith=list(
                    "varsCont",
                    "varsCat",
                    "varsCount",
                    "groupVar",
                    "nodeGroupVar",
                    "lambdaSelMethod",
                    "kFolds",
                    "lambdaGam",
                    "ruleReg")))
            self$add(jmvcore::Image$new(
                options=options,
                name="networkPlot",
                title="Network Plot",
                requiresData=TRUE,
                visible="(plotNetwork)",
                renderFun=".plotNetwork",
                refs=list(
                    "qgraph"),
                clearWith=list(
                    "varsCont",
                    "varsCat",
                    "varsCount",
                    "groupVar",
                    "nodeGroupVar",
                    "lambdaSelMethod",
                    "kFolds",
                    "lambdaGam",
                    "ruleReg",
                    "layoutAlgorithm",
                    "showLabels",
                    "plotWidth",
                    "plotHeight")))}))

mgmBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mgmBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BSS",
                name = "mgm",
                version = c(1,0,0),
                options = options,
                results = mgmResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' For mixed data
#'
#' 
#' @param data .
#' @param varsCont .
#' @param varsCat .
#' @param varsCount .
#' @param groupVar .
#' @param nodeGroupVar .
#' @param lambdaSelMethod .
#' @param kFolds .
#' @param lambdaGam .
#' @param ruleReg .
#' @param tableCentrality .
#' @param tableClustering .
#' @param tableWeights .
#' @param plotCentrality .
#' @param plotClustering .
#' @param plotNetwork .
#' @param layoutAlgorithm .
#' @param showLabels .
#' @param plotWidth .
#' @param plotHeight .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$centrality} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$clustering} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$weights} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$centralityPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$clusteringPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$networkPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summary$asDF}
#'
#' \code{as.data.frame(results$summary)}
#'
#' @export
mgm <- function(
    data,
    varsCont = NULL,
    varsCat = NULL,
    varsCount = NULL,
    groupVar = NULL,
    nodeGroupVar = NULL,
    lambdaSelMethod = "EBIC",
    kFolds = 3,
    lambdaGam = 0.5,
    ruleReg = "AND",
    tableCentrality = TRUE,
    tableClustering = FALSE,
    tableWeights = FALSE,
    plotCentrality = FALSE,
    plotClustering = FALSE,
    plotNetwork = TRUE,
    layoutAlgorithm = "spring",
    showLabels = TRUE,
    plotWidth = 500,
    plotHeight = 500) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mgm requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varsCont)) varsCont <- jmvcore::resolveQuo(jmvcore::enquo(varsCont))
    if ( ! missing(varsCat)) varsCat <- jmvcore::resolveQuo(jmvcore::enquo(varsCat))
    if ( ! missing(varsCount)) varsCount <- jmvcore::resolveQuo(jmvcore::enquo(varsCount))
    if ( ! missing(groupVar)) groupVar <- jmvcore::resolveQuo(jmvcore::enquo(groupVar))
    if ( ! missing(nodeGroupVar)) nodeGroupVar <- jmvcore::resolveQuo(jmvcore::enquo(nodeGroupVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varsCont), varsCont, NULL),
            `if`( ! missing(varsCat), varsCat, NULL),
            `if`( ! missing(varsCount), varsCount, NULL),
            `if`( ! missing(groupVar), groupVar, NULL),
            `if`( ! missing(nodeGroupVar), nodeGroupVar, NULL))

    for (v in varsCat) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in groupVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- mgmOptions$new(
        varsCont = varsCont,
        varsCat = varsCat,
        varsCount = varsCount,
        groupVar = groupVar,
        nodeGroupVar = nodeGroupVar,
        lambdaSelMethod = lambdaSelMethod,
        kFolds = kFolds,
        lambdaGam = lambdaGam,
        ruleReg = ruleReg,
        tableCentrality = tableCentrality,
        tableClustering = tableClustering,
        tableWeights = tableWeights,
        plotCentrality = plotCentrality,
        plotClustering = plotClustering,
        plotNetwork = plotNetwork,
        layoutAlgorithm = layoutAlgorithm,
        showLabels = showLabels,
        plotWidth = plotWidth,
        plotHeight = plotHeight)

    analysis <- mgmClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

