
# This file is automatically generated, you probably don't want to edit this

miceImputationOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "miceImputationOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            predictor_vars = NULL,
            show_pattern_plot = FALSE,
            show_trace_plot = FALSE,
            show_density_plot = FALSE,
            show_strip_plot = FALSE,
            show_correlation_plot = FALSE,
            imputation_method = "pmm",
            num_imputations = 5,
            maxiter = 10,
            seed = "",
            run_imputation = FALSE,
            data_format = "wide",
            subject_id_var = NULL,
            time_var = NULL,
            group_var = NULL,
            fixed_covariates = NULL,
            wave_vars = NULL, ...) {

            super$initialize(
                package="BSS",
                name="miceImputation",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                required=TRUE,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..predictor_vars <- jmvcore::OptionVariables$new(
                "predictor_vars",
                predictor_vars,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"),
                default=NULL)
            private$..show_pattern_plot <- jmvcore::OptionBool$new(
                "show_pattern_plot",
                show_pattern_plot,
                default=FALSE)
            private$..show_trace_plot <- jmvcore::OptionBool$new(
                "show_trace_plot",
                show_trace_plot,
                default=FALSE)
            private$..show_density_plot <- jmvcore::OptionBool$new(
                "show_density_plot",
                show_density_plot,
                default=FALSE)
            private$..show_strip_plot <- jmvcore::OptionBool$new(
                "show_strip_plot",
                show_strip_plot,
                default=FALSE)
            private$..show_correlation_plot <- jmvcore::OptionBool$new(
                "show_correlation_plot",
                show_correlation_plot,
                default=FALSE)
            private$..imputation_method <- jmvcore::OptionList$new(
                "imputation_method",
                imputation_method,
                options=list(
                    "pmm",
                    "norm",
                    "logreg",
                    "polyreg",
                    "2l.pmm",
                    "2l.continuous"),
                default="pmm")
            private$..num_imputations <- jmvcore::OptionInteger$new(
                "num_imputations",
                num_imputations,
                default=5,
                min=2,
                max=50)
            private$..maxiter <- jmvcore::OptionInteger$new(
                "maxiter",
                maxiter,
                default=10,
                min=1,
                max=100)
            private$..seed <- jmvcore::OptionString$new(
                "seed",
                seed,
                default="")
            private$..run_imputation <- jmvcore::OptionBool$new(
                "run_imputation",
                run_imputation,
                default=FALSE)
            private$..data_format <- jmvcore::OptionList$new(
                "data_format",
                data_format,
                options=list(
                    "long",
                    "wide"),
                default="wide")
            private$..subject_id_var <- jmvcore::OptionVariable$new(
                "subject_id_var",
                subject_id_var,
                suggested=list(
                    "nominal",
                    "id"),
                permitted=list(
                    "numeric",
                    "factor",
                    "id"),
                default=NULL)
            private$..time_var <- jmvcore::OptionVariable$new(
                "time_var",
                time_var,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"),
                default=NULL)
            private$..group_var <- jmvcore::OptionVariable$new(
                "group_var",
                group_var,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"),
                default=NULL)
            private$..fixed_covariates <- jmvcore::OptionVariables$new(
                "fixed_covariates",
                fixed_covariates,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"),
                default=NULL)
            private$..wave_vars <- jmvcore::OptionVariables$new(
                "wave_vars",
                wave_vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"),
                default=NULL)
            private$..imputedColsOutput <- jmvcore::OptionOutput$new(
                "imputedColsOutput")

            self$.addOption(private$..vars)
            self$.addOption(private$..predictor_vars)
            self$.addOption(private$..show_pattern_plot)
            self$.addOption(private$..show_trace_plot)
            self$.addOption(private$..show_density_plot)
            self$.addOption(private$..show_strip_plot)
            self$.addOption(private$..show_correlation_plot)
            self$.addOption(private$..imputation_method)
            self$.addOption(private$..num_imputations)
            self$.addOption(private$..maxiter)
            self$.addOption(private$..seed)
            self$.addOption(private$..run_imputation)
            self$.addOption(private$..data_format)
            self$.addOption(private$..subject_id_var)
            self$.addOption(private$..time_var)
            self$.addOption(private$..group_var)
            self$.addOption(private$..fixed_covariates)
            self$.addOption(private$..wave_vars)
            self$.addOption(private$..imputedColsOutput)
        }),
    active = list(
        vars = function() private$..vars$value,
        predictor_vars = function() private$..predictor_vars$value,
        show_pattern_plot = function() private$..show_pattern_plot$value,
        show_trace_plot = function() private$..show_trace_plot$value,
        show_density_plot = function() private$..show_density_plot$value,
        show_strip_plot = function() private$..show_strip_plot$value,
        show_correlation_plot = function() private$..show_correlation_plot$value,
        imputation_method = function() private$..imputation_method$value,
        num_imputations = function() private$..num_imputations$value,
        maxiter = function() private$..maxiter$value,
        seed = function() private$..seed$value,
        run_imputation = function() private$..run_imputation$value,
        data_format = function() private$..data_format$value,
        subject_id_var = function() private$..subject_id_var$value,
        time_var = function() private$..time_var$value,
        group_var = function() private$..group_var$value,
        fixed_covariates = function() private$..fixed_covariates$value,
        wave_vars = function() private$..wave_vars$value,
        imputedColsOutput = function() private$..imputedColsOutput$value),
    private = list(
        ..vars = NA,
        ..predictor_vars = NA,
        ..show_pattern_plot = NA,
        ..show_trace_plot = NA,
        ..show_density_plot = NA,
        ..show_strip_plot = NA,
        ..show_correlation_plot = NA,
        ..imputation_method = NA,
        ..num_imputations = NA,
        ..maxiter = NA,
        ..seed = NA,
        ..run_imputation = NA,
        ..data_format = NA,
        ..subject_id_var = NA,
        ..time_var = NA,
        ..group_var = NA,
        ..fixed_covariates = NA,
        ..wave_vars = NA,
        ..imputedColsOutput = NA)
)

miceImputationResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "miceImputationResults",
    inherit = jmvcore::Group,
    active = list(
        imputationInfo = function() private$.items[["imputationInfo"]],
        missingnessTable = function() private$.items[["missingnessTable"]],
        imputedData = function() private$.items[["imputedData"]],
        text = function() private$.items[["text"]],
        patternPlot = function() private$.items[["patternPlot"]],
        tracePlot = function() private$.items[["tracePlot"]],
        densityPlot = function() private$.items[["densityPlot"]],
        stripPlot = function() private$.items[["stripPlot"]],
        correlationPlot = function() private$.items[["correlationPlot"]],
        imputedColsOutput = function() private$.items[["imputedColsOutput"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="MICE Imputation")
            self$add(jmvcore::Html$new(
                options=options,
                name="imputationInfo",
                title="About MICE Imputation",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="missingnessTable",
                title="Missingness Summary",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="n_missing", 
                        `title`="Missing (N)", 
                        `type`="integer"),
                    list(
                        `name`="pct_missing", 
                        `title`="Missing (%)", 
                        `type`="number", 
                        `format`="dp:1"),
                    list(
                        `name`="n_valid", 
                        `title`="Valid (N)", 
                        `type`="integer"),
                    list(
                        `name`="method_used", 
                        `title`="Method Applied", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="imputedData",
                title="Imputed Values (Pooled)",
                clearWith=list(
                    "run_imputation",
                    "imputation_method",
                    "num_imputations",
                    "maxiter",
                    "seed"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="original", 
                        `title`="Original Value", 
                        `type`="text"),
                    list(
                        `name`="imputed", 
                        `title`="Pooled Imputed Value", 
                        `type`="text"),
                    list(
                        `name`="rowNumber", 
                        `title`="Row", 
                        `type`="integer"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Imputation Summary",
                visible=FALSE,
                clearWith=list(
                    "run_imputation",
                    "imputation_method",
                    "num_imputations")))
            self$add(jmvcore::Image$new(
                options=options,
                name="patternPlot",
                title="Missing Data Pattern",
                width=700,
                height=500,
                renderFun=".patternPlot",
                visible="(show_pattern_plot)",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "show_pattern_plot")))
            self$add(jmvcore::Image$new(
                options=options,
                name="tracePlot",
                title="Convergence Trace Plot",
                width=700,
                height=500,
                renderFun=".tracePlot",
                visible="(show_trace_plot)",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "run_imputation",
                    "imputation_method",
                    "num_imputations",
                    "maxiter",
                    "seed",
                    "show_trace_plot")))
            self$add(jmvcore::Image$new(
                options=options,
                name="densityPlot",
                title="Observed vs Imputed Distribution",
                width=700,
                height=500,
                renderFun=".densityPlot",
                visible="(show_density_plot)",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "run_imputation",
                    "imputation_method",
                    "num_imputations",
                    "maxiter",
                    "seed",
                    "show_density_plot")))
            self$add(jmvcore::Image$new(
                options=options,
                name="stripPlot",
                title="Strip Plot by Variable",
                width=700,
                height=500,
                renderFun=".stripPlot",
                visible="(show_strip_plot)",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "run_imputation",
                    "imputation_method",
                    "num_imputations",
                    "maxiter",
                    "seed",
                    "show_strip_plot")))
            self$add(jmvcore::Image$new(
                options=options,
                name="correlationPlot",
                title="Missingness Correlation Heatmap",
                width=700,
                height=500,
                renderFun=".correlationPlot",
                visible="(show_correlation_plot)",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "show_correlation_plot")))
            self$add(jmvcore::Output$new(
                options=options,
                name="imputedColsOutput",
                title="Imputed Variables (Pooled)",
                initInRun=TRUE,
                clearWith=list(
                    "data",
                    "vars",
                    "predictor_vars",
                    "imputation_method",
                    "num_imputations",
                    "maxiter",
                    "seed",
                    "run_imputation",
                    "subject_id_var",
                    "time_var",
                    "group_var",
                    "fixed_covariates",
                    "wave_vars",
                    "data_format")))}))

miceImputationBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "miceImputationBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BSS",
                name = "miceImputation",
                version = c(0,0,1),
                options = options,
                results = miceImputationResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' MICE Imputation
#'
#' 
#' @param data .
#' @param vars .
#' @param predictor_vars .
#' @param show_pattern_plot .
#' @param show_trace_plot .
#' @param show_density_plot .
#' @param show_strip_plot .
#' @param show_correlation_plot .
#' @param imputation_method .
#' @param num_imputations .
#' @param maxiter .
#' @param seed .
#' @param run_imputation .
#' @param data_format .
#' @param subject_id_var .
#' @param time_var .
#' @param group_var .
#' @param fixed_covariates .
#' @param wave_vars .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$imputationInfo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$missingnessTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$imputedData} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$patternPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$tracePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$densityPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$stripPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$correlationPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$imputedColsOutput} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$missingnessTable$asDF}
#'
#' \code{as.data.frame(results$missingnessTable)}
#'
#' @export
miceImputation <- function(
    data,
    vars,
    predictor_vars = NULL,
    show_pattern_plot = FALSE,
    show_trace_plot = FALSE,
    show_density_plot = FALSE,
    show_strip_plot = FALSE,
    show_correlation_plot = FALSE,
    imputation_method = "pmm",
    num_imputations = 5,
    maxiter = 10,
    seed = "",
    run_imputation = FALSE,
    data_format = "wide",
    subject_id_var = NULL,
    time_var = NULL,
    group_var = NULL,
    fixed_covariates = NULL,
    wave_vars = NULL) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("miceImputation requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(predictor_vars)) predictor_vars <- jmvcore::resolveQuo(jmvcore::enquo(predictor_vars))
    if ( ! missing(subject_id_var)) subject_id_var <- jmvcore::resolveQuo(jmvcore::enquo(subject_id_var))
    if ( ! missing(time_var)) time_var <- jmvcore::resolveQuo(jmvcore::enquo(time_var))
    if ( ! missing(group_var)) group_var <- jmvcore::resolveQuo(jmvcore::enquo(group_var))
    if ( ! missing(fixed_covariates)) fixed_covariates <- jmvcore::resolveQuo(jmvcore::enquo(fixed_covariates))
    if ( ! missing(wave_vars)) wave_vars <- jmvcore::resolveQuo(jmvcore::enquo(wave_vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(predictor_vars), predictor_vars, NULL),
            `if`( ! missing(subject_id_var), subject_id_var, NULL),
            `if`( ! missing(time_var), time_var, NULL),
            `if`( ! missing(group_var), group_var, NULL),
            `if`( ! missing(fixed_covariates), fixed_covariates, NULL),
            `if`( ! missing(wave_vars), wave_vars, NULL))


    options <- miceImputationOptions$new(
        vars = vars,
        predictor_vars = predictor_vars,
        show_pattern_plot = show_pattern_plot,
        show_trace_plot = show_trace_plot,
        show_density_plot = show_density_plot,
        show_strip_plot = show_strip_plot,
        show_correlation_plot = show_correlation_plot,
        imputation_method = imputation_method,
        num_imputations = num_imputations,
        maxiter = maxiter,
        seed = seed,
        run_imputation = run_imputation,
        data_format = data_format,
        subject_id_var = subject_id_var,
        time_var = time_var,
        group_var = group_var,
        fixed_covariates = fixed_covariates,
        wave_vars = wave_vars)

    analysis <- miceImputationClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

