
# This file is automatically generated, you probably don't want to edit this

missRangerImputationOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "missRangerImputationOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            predictor_vars = NULL,
            maxiter = 10,
            num_trees = 100,
            pmm_k = 5,
            seed = "",
            show_pattern_plot = FALSE,
            show_correlation_plot = FALSE, ...) {

            super$initialize(
                package="BSS",
                name="missRangerImputation",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                required=TRUE,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..predictor_vars <- jmvcore::OptionVariables$new(
                "predictor_vars",
                predictor_vars,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"),
                default=NULL)
            private$..maxiter <- jmvcore::OptionInteger$new(
                "maxiter",
                maxiter,
                default=10,
                min=1,
                max=100)
            private$..num_trees <- jmvcore::OptionInteger$new(
                "num_trees",
                num_trees,
                default=100,
                min=1,
                max=200)
            private$..pmm_k <- jmvcore::OptionInteger$new(
                "pmm_k",
                pmm_k,
                default=5,
                min=0,
                max=20)
            private$..seed <- jmvcore::OptionString$new(
                "seed",
                seed,
                default="")
            private$..show_pattern_plot <- jmvcore::OptionBool$new(
                "show_pattern_plot",
                show_pattern_plot,
                default=FALSE)
            private$..show_correlation_plot <- jmvcore::OptionBool$new(
                "show_correlation_plot",
                show_correlation_plot,
                default=FALSE)
            private$..imputedColsOutput <- jmvcore::OptionOutput$new(
                "imputedColsOutput")

            self$.addOption(private$..vars)
            self$.addOption(private$..predictor_vars)
            self$.addOption(private$..maxiter)
            self$.addOption(private$..num_trees)
            self$.addOption(private$..pmm_k)
            self$.addOption(private$..seed)
            self$.addOption(private$..show_pattern_plot)
            self$.addOption(private$..show_correlation_plot)
            self$.addOption(private$..imputedColsOutput)
        }),
    active = list(
        vars = function() private$..vars$value,
        predictor_vars = function() private$..predictor_vars$value,
        maxiter = function() private$..maxiter$value,
        num_trees = function() private$..num_trees$value,
        pmm_k = function() private$..pmm_k$value,
        seed = function() private$..seed$value,
        show_pattern_plot = function() private$..show_pattern_plot$value,
        show_correlation_plot = function() private$..show_correlation_plot$value,
        imputedColsOutput = function() private$..imputedColsOutput$value),
    private = list(
        ..vars = NA,
        ..predictor_vars = NA,
        ..maxiter = NA,
        ..num_trees = NA,
        ..pmm_k = NA,
        ..seed = NA,
        ..show_pattern_plot = NA,
        ..show_correlation_plot = NA,
        ..imputedColsOutput = NA)
)

missRangerImputationResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "missRangerImputationResults",
    inherit = jmvcore::Group,
    active = list(
        imputationInfo = function() private$.items[["imputationInfo"]],
        missingnessTable = function() private$.items[["missingnessTable"]],
        imputedData = function() private$.items[["imputedData"]],
        text = function() private$.items[["text"]],
        patternPlot = function() private$.items[["patternPlot"]],
        correlationPlot = function() private$.items[["correlationPlot"]],
        imputedColsOutput = function() private$.items[["imputedColsOutput"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="MissRanger Imputation")
            self$add(jmvcore::Html$new(
                options=options,
                name="imputationInfo",
                title="About MissRanger Imputation",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="missingnessTable",
                title="Missingness Summary",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="n_missing", 
                        `title`="Missing (N)", 
                        `type`="integer"),
                    list(
                        `name`="pct_missing", 
                        `title`="Missing (%)", 
                        `type`="number", 
                        `format`="dp:1"),
                    list(
                        `name`="n_valid", 
                        `title`="Valid (N)", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="imputedData",
                title="Imputed Values",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="original", 
                        `title`="Original Value", 
                        `type`="text"),
                    list(
                        `name`="imputed", 
                        `title`="Imputed Value", 
                        `type`="text"),
                    list(
                        `name`="rowNumber", 
                        `title`="Row Number", 
                        `type`="integer"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Imputation Summary",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="patternPlot",
                title="Missing Pattern Plot",
                width=600,
                height=600,
                renderFun=".combinationsPlot",
                visible="(show_pattern_plot)",
                requiresData=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="correlationPlot",
                title="Missingness Correlation Heatmap",
                width=600,
                height=500,
                renderFun=".correlationPlot",
                visible="(show_correlation_plot)",
                requiresData=TRUE))
            self$add(jmvcore::Output$new(
                options=options,
                name="imputedColsOutput",
                title="Imputed Variables",
                initInRun=TRUE,
                clearWith=list(
                    "data",
                    "vars",
                    "predictor_vars",
                    "maxiter",
                    "num_trees",
                    "pmm_k",
                    "seed")))}))

missRangerImputationBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "missRangerImputationBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BSS",
                name = "missRangerImputation",
                version = c(0,0,2),
                options = options,
                results = missRangerImputationResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' MissRanger Imputation
#'
#' 
#' @param data .
#' @param vars .
#' @param predictor_vars .
#' @param maxiter .
#' @param num_trees .
#' @param pmm_k .
#' @param seed .
#' @param show_pattern_plot .
#' @param show_correlation_plot .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$imputationInfo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$missingnessTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$imputedData} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$patternPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$correlationPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$imputedColsOutput} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$missingnessTable$asDF}
#'
#' \code{as.data.frame(results$missingnessTable)}
#'
#' @export
missRangerImputation <- function(
    data,
    vars,
    predictor_vars = NULL,
    maxiter = 10,
    num_trees = 100,
    pmm_k = 5,
    seed = "",
    show_pattern_plot = FALSE,
    show_correlation_plot = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("missRangerImputation requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(predictor_vars)) predictor_vars <- jmvcore::resolveQuo(jmvcore::enquo(predictor_vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(predictor_vars), predictor_vars, NULL))


    options <- missRangerImputationOptions$new(
        vars = vars,
        predictor_vars = predictor_vars,
        maxiter = maxiter,
        num_trees = num_trees,
        pmm_k = pmm_k,
        seed = seed,
        show_pattern_plot = show_pattern_plot,
        show_correlation_plot = show_correlation_plot)

    analysis <- missRangerImputationClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

