
# This file is automatically generated, you probably don't want to edit this

ModifiedZOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ModifiedZOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            threshold = "t35",
            treatment = "none",
            trimPercent = 5,
            dispBox = FALSE, ...) {

            super$initialize(
                package="BSS",
                name="ModifiedZ",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariables$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..threshold <- jmvcore::OptionList$new(
                "threshold",
                threshold,
                options=list(
                    "t25",
                    "t30",
                    "t35",
                    "t40"),
                default="t35")
            private$..treatment <- jmvcore::OptionList$new(
                "treatment",
                treatment,
                options=list(
                    "none",
                    "trim_asym",
                    "trim_sym",
                    "win_valid",
                    "win_fence"),
                default="none")
            private$..trimPercent <- jmvcore::OptionNumber$new(
                "trimPercent",
                trimPercent,
                default=5,
                min=1,
                max=49)
            private$..dispBox <- jmvcore::OptionBool$new(
                "dispBox",
                dispBox,
                default=FALSE)
            private$..treatedData <- jmvcore::OptionOutput$new(
                "treatedData")

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..threshold)
            self$.addOption(private$..treatment)
            self$.addOption(private$..trimPercent)
            self$.addOption(private$..dispBox)
            self$.addOption(private$..treatedData)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        threshold = function() private$..threshold$value,
        treatment = function() private$..treatment$value,
        trimPercent = function() private$..trimPercent$value,
        dispBox = function() private$..dispBox$value,
        treatedData = function() private$..treatedData$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..threshold = NA,
        ..treatment = NA,
        ..trimPercent = NA,
        ..dispBox = NA,
        ..treatedData = NA)
)

ModifiedZResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ModifiedZResults",
    inherit = jmvcore::Group,
    active = list(
        iqrInfo = function() private$.items[["iqrInfo"]],
        text = function() private$.items[["text"]],
        outlierTable = function() private$.items[["outlierTable"]],
        outlierList = function() private$.items[["outlierList"]],
        plot = function() private$.items[["plot"]],
        treatedData = function() private$.items[["treatedData"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Outlier Detection Results")
            self$add(jmvcore::Html$new(
                options=options,
                name="iqrInfo",
                title="Thresholds",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Modified Z-Score Outlier Detection Summary"))
            self$add(jmvcore::Table$new(
                options=options,
                name="outlierTable",
                title="Outliers Summary",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="group_level", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="lowerThreshold", 
                        `title`="Lower Threshold", 
                        `type`="number"),
                    list(
                        `name`="upperThreshold", 
                        `title`="Upper Threshold", 
                        `type`="number"),
                    list(
                        `name`="numOutliers", 
                        `title`="Outliers Detected", 
                        `type`="integer"),
                    list(
                        `name`="treatmentApplied", 
                        `title`="Treatment Applied", 
                        `type`="text", 
                        `visible`="(treatment != 'none')"),
                    list(
                        `name`="modifiedN", 
                        `title`="Valid N (After Treatment)", 
                        `type`="integer", 
                        `visible`="(treatment != 'none')"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="outlierList",
                title="Identified Outliers",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="group_level", 
                        `title`="Group", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="rowNumber", 
                        `title`="Row", 
                        `type`="integer"),
                    list(
                        `name`="modifiedZ", 
                        `title`="Modified Z-Score", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Boxplot",
                width=500,
                height=400,
                renderFun=".plot",
                visible="(dispBox)"))
            self$add(jmvcore::Output$new(
                options=options,
                name="treatedData",
                title="Treated Variables",
                initInRun=TRUE,
                clearWith=list(
                    "vars",
                    "group",
                    "threshold",
                    "treatment",
                    "trimPercent")))}))

ModifiedZBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ModifiedZBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BSS",
                name = "ModifiedZ",
                version = c(1,0,0),
                options = options,
                results = ModifiedZResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Outlier Detection
#'
#' 
#' @param data .
#' @param vars .
#' @param group .
#' @param threshold .
#' @param treatment .
#' @param trimPercent .
#' @param dispBox .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$iqrInfo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$outlierTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$outlierList} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$treatedData} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$outlierTable$asDF}
#'
#' \code{as.data.frame(results$outlierTable)}
#'
#' @export
ModifiedZ <- function(
    data,
    vars,
    group,
    threshold = "t35",
    treatment = "none",
    trimPercent = 5,
    dispBox = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ModifiedZ requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- ModifiedZOptions$new(
        vars = vars,
        group = group,
        threshold = threshold,
        treatment = treatment,
        trimPercent = trimPercent,
        dispBox = dispBox)

    analysis <- ModifiedZClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

