
# This file is automatically generated, you probably don't want to edit this

ModifiedZOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ModifiedZOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            groups = NULL,
            threshold = 3.5,
            dispTable = TRUE, ...) {

            super$initialize(
                package="BSS",
                name="ModifiedZ",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"))
            private$..groups <- jmvcore::OptionVariables$new(
                "groups",
                groups,
                suggested=list(
                    "nominal",
                    "ordinal"))
            private$..threshold <- jmvcore::OptionNumber$new(
                "threshold",
                threshold,
                default=3.5)
            private$..dispTable <- jmvcore::OptionBool$new(
                "dispTable",
                dispTable,
                default=TRUE)

            self$.addOption(private$..vars)
            self$.addOption(private$..groups)
            self$.addOption(private$..threshold)
            self$.addOption(private$..dispTable)
        }),
    active = list(
        vars = function() private$..vars$value,
        groups = function() private$..groups$value,
        threshold = function() private$..threshold$value,
        dispTable = function() private$..dispTable$value),
    private = list(
        ..vars = NA,
        ..groups = NA,
        ..threshold = NA,
        ..dispTable = NA)
)

ModifiedZResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ModifiedZResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        outlierTable = function() private$.items[["outlierTable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Modified Z-Score Method Results")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Modified Z-Score Outlier Detection"))
            self$add(jmvcore::Table$new(
                options=options,
                name="outlierTable",
                title="Outliers Summary",
                rows="(vars)",
                visible="(threshold)",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable Name", 
                        `type`="text"),
                    list(
                        `name`="row_number", 
                        `title`="Row Number", 
                        `type`="integer"),
                    list(
                        `name`="modified_z_score", 
                        `title`="Modified Z-Score", 
                        `type`="number"),
                    list(
                        `name`="is_outlier", 
                        `title`="Is Outlier?", 
                        `type`="text"))))}))

ModifiedZBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ModifiedZBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BSS",
                name = "ModifiedZ",
                version = c(0,0,1),
                options = options,
                results = ModifiedZResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Outlier Detection
#'
#' 
#' @param data .
#' @param vars .
#' @param groups .
#' @param threshold .
#' @param dispTable .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$outlierTable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$outlierTable$asDF}
#'
#' \code{as.data.frame(results$outlierTable)}
#'
#' @export
ModifiedZ <- function(
    data,
    vars,
    groups,
    threshold = 3.5,
    dispTable = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ModifiedZ requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(groups)) groups <- jmvcore::resolveQuo(jmvcore::enquo(groups))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(groups), groups, NULL))


    options <- ModifiedZOptions$new(
        vars = vars,
        groups = groups,
        threshold = threshold,
        dispTable = dispTable)

    analysis <- ModifiedZClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

