
# This file is automatically generated, you probably don't want to edit this

NetworkOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "NetworkOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            groupVar = NULL,
            estimator = "EBICglasso",
            corMethod = "auto",
            tableCentrality = TRUE,
            tableClustering = FALSE,
            tableWeights = FALSE,
            plotCentrality = FALSE,
            plotClustering = FALSE,
            plotNetwork = FALSE,
            layoutAlgorithm = "spring",
            showLabels = TRUE,
            plotWidth = 500,
            plotHeight = 500, ...) {

            super$initialize(
                package="BSS",
                name="Network",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..groupVar <- jmvcore::OptionVariable$new(
                "groupVar",
                groupVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..estimator <- jmvcore::OptionList$new(
                "estimator",
                estimator,
                options=list(
                    "EBICglasso",
                    "correlation",
                    "partial_correlation"),
                default="EBICglasso")
            private$..corMethod <- jmvcore::OptionList$new(
                "corMethod",
                corMethod,
                options=list(
                    "auto",
                    "cor",
                    "cov"),
                default="auto")
            private$..tableCentrality <- jmvcore::OptionBool$new(
                "tableCentrality",
                tableCentrality,
                default=TRUE)
            private$..tableClustering <- jmvcore::OptionBool$new(
                "tableClustering",
                tableClustering,
                default=FALSE)
            private$..tableWeights <- jmvcore::OptionBool$new(
                "tableWeights",
                tableWeights,
                default=FALSE)
            private$..plotCentrality <- jmvcore::OptionBool$new(
                "plotCentrality",
                plotCentrality,
                default=FALSE)
            private$..plotClustering <- jmvcore::OptionBool$new(
                "plotClustering",
                plotClustering,
                default=FALSE)
            private$..plotNetwork <- jmvcore::OptionBool$new(
                "plotNetwork",
                plotNetwork,
                default=FALSE)
            private$..layoutAlgorithm <- jmvcore::OptionList$new(
                "layoutAlgorithm",
                layoutAlgorithm,
                options=list(
                    "spring",
                    "circle"),
                default="spring")
            private$..showLabels <- jmvcore::OptionBool$new(
                "showLabels",
                showLabels,
                default=TRUE)
            private$..plotWidth <- jmvcore::OptionInteger$new(
                "plotWidth",
                plotWidth,
                default=500)
            private$..plotHeight <- jmvcore::OptionInteger$new(
                "plotHeight",
                plotHeight,
                default=500)

            self$.addOption(private$..vars)
            self$.addOption(private$..groupVar)
            self$.addOption(private$..estimator)
            self$.addOption(private$..corMethod)
            self$.addOption(private$..tableCentrality)
            self$.addOption(private$..tableClustering)
            self$.addOption(private$..tableWeights)
            self$.addOption(private$..plotCentrality)
            self$.addOption(private$..plotClustering)
            self$.addOption(private$..plotNetwork)
            self$.addOption(private$..layoutAlgorithm)
            self$.addOption(private$..showLabels)
            self$.addOption(private$..plotWidth)
            self$.addOption(private$..plotHeight)
        }),
    active = list(
        vars = function() private$..vars$value,
        groupVar = function() private$..groupVar$value,
        estimator = function() private$..estimator$value,
        corMethod = function() private$..corMethod$value,
        tableCentrality = function() private$..tableCentrality$value,
        tableClustering = function() private$..tableClustering$value,
        tableWeights = function() private$..tableWeights$value,
        plotCentrality = function() private$..plotCentrality$value,
        plotClustering = function() private$..plotClustering$value,
        plotNetwork = function() private$..plotNetwork$value,
        layoutAlgorithm = function() private$..layoutAlgorithm$value,
        showLabels = function() private$..showLabels$value,
        plotWidth = function() private$..plotWidth$value,
        plotHeight = function() private$..plotHeight$value),
    private = list(
        ..vars = NA,
        ..groupVar = NA,
        ..estimator = NA,
        ..corMethod = NA,
        ..tableCentrality = NA,
        ..tableClustering = NA,
        ..tableWeights = NA,
        ..plotCentrality = NA,
        ..plotClustering = NA,
        ..plotNetwork = NA,
        ..layoutAlgorithm = NA,
        ..showLabels = NA,
        ..plotWidth = NA,
        ..plotHeight = NA)
)

NetworkResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "NetworkResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        summary = function() private$.items[["summary"]],
        centrality = function() private$.items[["centrality"]],
        clustering = function() private$.items[["clustering"]],
        weights = function() private$.items[["weights"]],
        centralityPlot = function() private$.items[["centralityPlot"]],
        clusteringPlot = function() private$.items[["clusteringPlot"]],
        networkPlot = function() private$.items[["networkPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Network Analysis")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="instructions",
                title=" ",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="summary",
                title="Network Summary",
                clearWith=list(
                    "vars",
                    "estimator",
                    "corMethod",
                    "groupVar"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(groupVar)"),
                    list(
                        `name`="nodes", 
                        `title`="Nodes", 
                        `type`="integer"),
                    list(
                        `name`="edges", 
                        `title`="Edges (Non-zero)", 
                        `type`="text"),
                    list(
                        `name`="sparsity", 
                        `title`="Sparsity", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="centrality",
                title="Centrality Measures",
                visible="(tableCentrality)",
                refs=list(
                    "qgraph"),
                clearWith=list(
                    "vars",
                    "estimator",
                    "corMethod",
                    "groupVar"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(groupVar)"),
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text", 
                        `format`="string"),
                    list(
                        `name`="strength", 
                        `title`="Strength", 
                        `type`="number"),
                    list(
                        `name`="closeness", 
                        `title`="Closeness", 
                        `type`="number"),
                    list(
                        `name`="betweenness", 
                        `title`="Betweenness", 
                        `type`="number"),
                    list(
                        `name`="expectedInfluence", 
                        `title`="Expected Influence", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="clustering",
                title="Clustering Measures per Variable",
                visible="(tableClustering)",
                refs=list(
                    "qgraph",
                    "igraph"),
                clearWith=list(
                    "vars",
                    "estimator",
                    "corMethod",
                    "groupVar"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(groupVar)"),
                    list(
                        `name`="node", 
                        `title`="Variable", 
                        `type`="text", 
                        `format`="string"),
                    list(
                        `name`="Barrat", 
                        `title`="Barrat", 
                        `type`="number"),
                    list(
                        `name`="WS", 
                        `title`="Local (WS)", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="weights",
                title="Weights (Adjacency Matrix)",
                clearWith=list(
                    "vars",
                    "estimator",
                    "corMethod",
                    "groupVar"),
                columns=list(
                    list(
                        `name`="node", 
                        `title`="", 
                        `type`="text", 
                        `format`="string"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="centralityPlot",
                title="Centrality Plot",
                requiresData=TRUE,
                visible="(plotCentrality)",
                renderFun=".plotCentrality",
                refs=list(
                    "qgraph",
                    "ggplot2"),
                clearWith=list(
                    "vars",
                    "estimator",
                    "corMethod",
                    "groupVar")))
            self$add(jmvcore::Image$new(
                options=options,
                name="clusteringPlot",
                title="Clustering Plot",
                requiresData=TRUE,
                visible="(plotClustering)",
                renderFun=".plotClustering",
                refs=list(
                    "qgraph",
                    "ggplot2",
                    "igraph"),
                clearWith=list(
                    "vars",
                    "estimator",
                    "corMethod",
                    "groupVar")))
            self$add(jmvcore::Image$new(
                options=options,
                name="networkPlot",
                title="Network Plot",
                requiresData=TRUE,
                visible="(plotNetwork)",
                renderFun=".plotNetwork",
                refs=list(
                    "qgraph"),
                clearWith=list(
                    "vars",
                    "estimator",
                    "corMethod",
                    "layoutAlgorithm",
                    "showLabels",
                    "plotWidth",
                    "plotHeight",
                    "groupVar")))}))

NetworkBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "NetworkBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BSS",
                name = "Network",
                version = c(1,0,0),
                options = options,
                results = NetworkResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' For continuous data
#'
#' 
#' @param data .
#' @param vars .
#' @param groupVar .
#' @param estimator .
#' @param corMethod .
#' @param tableCentrality .
#' @param tableClustering .
#' @param tableWeights .
#' @param plotCentrality .
#' @param plotClustering .
#' @param plotNetwork .
#' @param layoutAlgorithm .
#' @param showLabels .
#' @param plotWidth .
#' @param plotHeight .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$centrality} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$clustering} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$weights} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$centralityPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$clusteringPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$networkPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summary$asDF}
#'
#' \code{as.data.frame(results$summary)}
#'
#' @export
Network <- function(
    data,
    vars,
    groupVar = NULL,
    estimator = "EBICglasso",
    corMethod = "auto",
    tableCentrality = TRUE,
    tableClustering = FALSE,
    tableWeights = FALSE,
    plotCentrality = FALSE,
    plotClustering = FALSE,
    plotNetwork = FALSE,
    layoutAlgorithm = "spring",
    showLabels = TRUE,
    plotWidth = 500,
    plotHeight = 500) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("Network requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(groupVar)) groupVar <- jmvcore::resolveQuo(jmvcore::enquo(groupVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(groupVar), groupVar, NULL))

    for (v in groupVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- NetworkOptions$new(
        vars = vars,
        groupVar = groupVar,
        estimator = estimator,
        corMethod = corMethod,
        tableCentrality = tableCentrality,
        tableClustering = tableClustering,
        tableWeights = tableWeights,
        plotCentrality = plotCentrality,
        plotClustering = plotClustering,
        plotNetwork = plotNetwork,
        layoutAlgorithm = layoutAlgorithm,
        showLabels = showLabels,
        plotWidth = plotWidth,
        plotHeight = plotHeight)

    analysis <- NetworkClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

