
# This file is automatically generated, you probably don't want to edit this

networkanalysisOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "networkanalysisOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mode = "continuous",
            vars_net = NULL,
            groupVar_net = NULL,
            nodeGroupVar_net = NULL,
            estimator_net = "EBICglasso",
            corMethod_net = "auto",
            tableCentrality_net = TRUE,
            tableClustering_net = FALSE,
            tableWeights_net = FALSE,
            plotCentrality_net = FALSE,
            plotClustering_net = FALSE,
            plotNetwork_net = FALSE,
            layoutAlgorithm_net = "spring",
            showLabels_net = TRUE,
            plotWidth_net = 500,
            plotHeight_net = 500,
            varsCont_mixed = NULL,
            varsCat_mixed = NULL,
            varsCount_mixed = NULL,
            groupVar_mixed = NULL,
            nodeGroupVar_mixed = NULL,
            lambdaSelMethod_mixed = "EBIC",
            kFolds_mixed = 3,
            lambdaGam_mixed = 0.5,
            ruleReg_mixed = "AND",
            tableCentrality_mixed = TRUE,
            tableClustering_mixed = FALSE,
            tableWeights_mixed = FALSE,
            plotCentrality_mixed = FALSE,
            plotClustering_mixed = FALSE,
            plotNetwork_mixed = TRUE,
            layoutAlgorithm_mixed = "spring",
            showLabels_mixed = TRUE,
            plotWidth_mixed = 500,
            plotHeight_mixed = 500, ...) {

            super$initialize(
                package="BSS",
                name="networkanalysis",
                requiresData=TRUE,
                ...)

            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "continuous",
                    "mixed"),
                default="continuous")
            private$..vars_net <- jmvcore::OptionVariables$new(
                "vars_net",
                vars_net,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..groupVar_net <- jmvcore::OptionVariable$new(
                "groupVar_net",
                groupVar_net,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..nodeGroupVar_net <- jmvcore::OptionVariable$new(
                "nodeGroupVar_net",
                nodeGroupVar_net,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor",
                    "id"),
                default=NULL)
            private$..estimator_net <- jmvcore::OptionList$new(
                "estimator_net",
                estimator_net,
                options=list(
                    "EBICglasso",
                    "correlation",
                    "partial_correlation"),
                default="EBICglasso")
            private$..corMethod_net <- jmvcore::OptionList$new(
                "corMethod_net",
                corMethod_net,
                options=list(
                    "auto",
                    "cor",
                    "cov"),
                default="auto")
            private$..tableCentrality_net <- jmvcore::OptionBool$new(
                "tableCentrality_net",
                tableCentrality_net,
                default=TRUE)
            private$..tableClustering_net <- jmvcore::OptionBool$new(
                "tableClustering_net",
                tableClustering_net,
                default=FALSE)
            private$..tableWeights_net <- jmvcore::OptionBool$new(
                "tableWeights_net",
                tableWeights_net,
                default=FALSE)
            private$..plotCentrality_net <- jmvcore::OptionBool$new(
                "plotCentrality_net",
                plotCentrality_net,
                default=FALSE)
            private$..plotClustering_net <- jmvcore::OptionBool$new(
                "plotClustering_net",
                plotClustering_net,
                default=FALSE)
            private$..plotNetwork_net <- jmvcore::OptionBool$new(
                "plotNetwork_net",
                plotNetwork_net,
                default=FALSE)
            private$..layoutAlgorithm_net <- jmvcore::OptionList$new(
                "layoutAlgorithm_net",
                layoutAlgorithm_net,
                options=list(
                    "spring",
                    "circle"),
                default="spring")
            private$..showLabels_net <- jmvcore::OptionBool$new(
                "showLabels_net",
                showLabels_net,
                default=TRUE)
            private$..plotWidth_net <- jmvcore::OptionInteger$new(
                "plotWidth_net",
                plotWidth_net,
                default=500)
            private$..plotHeight_net <- jmvcore::OptionInteger$new(
                "plotHeight_net",
                plotHeight_net,
                default=500)
            private$..varsCont_mixed <- jmvcore::OptionVariables$new(
                "varsCont_mixed",
                varsCont_mixed,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..varsCat_mixed <- jmvcore::OptionVariables$new(
                "varsCat_mixed",
                varsCat_mixed,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..varsCount_mixed <- jmvcore::OptionVariables$new(
                "varsCount_mixed",
                varsCount_mixed,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..groupVar_mixed <- jmvcore::OptionVariable$new(
                "groupVar_mixed",
                groupVar_mixed,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..nodeGroupVar_mixed <- jmvcore::OptionVariable$new(
                "nodeGroupVar_mixed",
                nodeGroupVar_mixed,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor",
                    "id"),
                default=NULL)
            private$..lambdaSelMethod_mixed <- jmvcore::OptionList$new(
                "lambdaSelMethod_mixed",
                lambdaSelMethod_mixed,
                options=list(
                    "EBIC",
                    "CV"),
                default="EBIC")
            private$..kFolds_mixed <- jmvcore::OptionInteger$new(
                "kFolds_mixed",
                kFolds_mixed,
                default=3,
                min=2)
            private$..lambdaGam_mixed <- jmvcore::OptionNumber$new(
                "lambdaGam_mixed",
                lambdaGam_mixed,
                default=0.5,
                min=0,
                max=1)
            private$..ruleReg_mixed <- jmvcore::OptionList$new(
                "ruleReg_mixed",
                ruleReg_mixed,
                options=list(
                    "AND",
                    "OR"),
                default="AND")
            private$..tableCentrality_mixed <- jmvcore::OptionBool$new(
                "tableCentrality_mixed",
                tableCentrality_mixed,
                default=TRUE)
            private$..tableClustering_mixed <- jmvcore::OptionBool$new(
                "tableClustering_mixed",
                tableClustering_mixed,
                default=FALSE)
            private$..tableWeights_mixed <- jmvcore::OptionBool$new(
                "tableWeights_mixed",
                tableWeights_mixed,
                default=FALSE)
            private$..plotCentrality_mixed <- jmvcore::OptionBool$new(
                "plotCentrality_mixed",
                plotCentrality_mixed,
                default=FALSE)
            private$..plotClustering_mixed <- jmvcore::OptionBool$new(
                "plotClustering_mixed",
                plotClustering_mixed,
                default=FALSE)
            private$..plotNetwork_mixed <- jmvcore::OptionBool$new(
                "plotNetwork_mixed",
                plotNetwork_mixed,
                default=TRUE)
            private$..layoutAlgorithm_mixed <- jmvcore::OptionList$new(
                "layoutAlgorithm_mixed",
                layoutAlgorithm_mixed,
                options=list(
                    "spring",
                    "circle"),
                default="spring")
            private$..showLabels_mixed <- jmvcore::OptionBool$new(
                "showLabels_mixed",
                showLabels_mixed,
                default=TRUE)
            private$..plotWidth_mixed <- jmvcore::OptionInteger$new(
                "plotWidth_mixed",
                plotWidth_mixed,
                default=500)
            private$..plotHeight_mixed <- jmvcore::OptionInteger$new(
                "plotHeight_mixed",
                plotHeight_mixed,
                default=500)

            self$.addOption(private$..mode)
            self$.addOption(private$..vars_net)
            self$.addOption(private$..groupVar_net)
            self$.addOption(private$..nodeGroupVar_net)
            self$.addOption(private$..estimator_net)
            self$.addOption(private$..corMethod_net)
            self$.addOption(private$..tableCentrality_net)
            self$.addOption(private$..tableClustering_net)
            self$.addOption(private$..tableWeights_net)
            self$.addOption(private$..plotCentrality_net)
            self$.addOption(private$..plotClustering_net)
            self$.addOption(private$..plotNetwork_net)
            self$.addOption(private$..layoutAlgorithm_net)
            self$.addOption(private$..showLabels_net)
            self$.addOption(private$..plotWidth_net)
            self$.addOption(private$..plotHeight_net)
            self$.addOption(private$..varsCont_mixed)
            self$.addOption(private$..varsCat_mixed)
            self$.addOption(private$..varsCount_mixed)
            self$.addOption(private$..groupVar_mixed)
            self$.addOption(private$..nodeGroupVar_mixed)
            self$.addOption(private$..lambdaSelMethod_mixed)
            self$.addOption(private$..kFolds_mixed)
            self$.addOption(private$..lambdaGam_mixed)
            self$.addOption(private$..ruleReg_mixed)
            self$.addOption(private$..tableCentrality_mixed)
            self$.addOption(private$..tableClustering_mixed)
            self$.addOption(private$..tableWeights_mixed)
            self$.addOption(private$..plotCentrality_mixed)
            self$.addOption(private$..plotClustering_mixed)
            self$.addOption(private$..plotNetwork_mixed)
            self$.addOption(private$..layoutAlgorithm_mixed)
            self$.addOption(private$..showLabels_mixed)
            self$.addOption(private$..plotWidth_mixed)
            self$.addOption(private$..plotHeight_mixed)
        }),
    active = list(
        mode = function() private$..mode$value,
        vars_net = function() private$..vars_net$value,
        groupVar_net = function() private$..groupVar_net$value,
        nodeGroupVar_net = function() private$..nodeGroupVar_net$value,
        estimator_net = function() private$..estimator_net$value,
        corMethod_net = function() private$..corMethod_net$value,
        tableCentrality_net = function() private$..tableCentrality_net$value,
        tableClustering_net = function() private$..tableClustering_net$value,
        tableWeights_net = function() private$..tableWeights_net$value,
        plotCentrality_net = function() private$..plotCentrality_net$value,
        plotClustering_net = function() private$..plotClustering_net$value,
        plotNetwork_net = function() private$..plotNetwork_net$value,
        layoutAlgorithm_net = function() private$..layoutAlgorithm_net$value,
        showLabels_net = function() private$..showLabels_net$value,
        plotWidth_net = function() private$..plotWidth_net$value,
        plotHeight_net = function() private$..plotHeight_net$value,
        varsCont_mixed = function() private$..varsCont_mixed$value,
        varsCat_mixed = function() private$..varsCat_mixed$value,
        varsCount_mixed = function() private$..varsCount_mixed$value,
        groupVar_mixed = function() private$..groupVar_mixed$value,
        nodeGroupVar_mixed = function() private$..nodeGroupVar_mixed$value,
        lambdaSelMethod_mixed = function() private$..lambdaSelMethod_mixed$value,
        kFolds_mixed = function() private$..kFolds_mixed$value,
        lambdaGam_mixed = function() private$..lambdaGam_mixed$value,
        ruleReg_mixed = function() private$..ruleReg_mixed$value,
        tableCentrality_mixed = function() private$..tableCentrality_mixed$value,
        tableClustering_mixed = function() private$..tableClustering_mixed$value,
        tableWeights_mixed = function() private$..tableWeights_mixed$value,
        plotCentrality_mixed = function() private$..plotCentrality_mixed$value,
        plotClustering_mixed = function() private$..plotClustering_mixed$value,
        plotNetwork_mixed = function() private$..plotNetwork_mixed$value,
        layoutAlgorithm_mixed = function() private$..layoutAlgorithm_mixed$value,
        showLabels_mixed = function() private$..showLabels_mixed$value,
        plotWidth_mixed = function() private$..plotWidth_mixed$value,
        plotHeight_mixed = function() private$..plotHeight_mixed$value),
    private = list(
        ..mode = NA,
        ..vars_net = NA,
        ..groupVar_net = NA,
        ..nodeGroupVar_net = NA,
        ..estimator_net = NA,
        ..corMethod_net = NA,
        ..tableCentrality_net = NA,
        ..tableClustering_net = NA,
        ..tableWeights_net = NA,
        ..plotCentrality_net = NA,
        ..plotClustering_net = NA,
        ..plotNetwork_net = NA,
        ..layoutAlgorithm_net = NA,
        ..showLabels_net = NA,
        ..plotWidth_net = NA,
        ..plotHeight_net = NA,
        ..varsCont_mixed = NA,
        ..varsCat_mixed = NA,
        ..varsCount_mixed = NA,
        ..groupVar_mixed = NA,
        ..nodeGroupVar_mixed = NA,
        ..lambdaSelMethod_mixed = NA,
        ..kFolds_mixed = NA,
        ..lambdaGam_mixed = NA,
        ..ruleReg_mixed = NA,
        ..tableCentrality_mixed = NA,
        ..tableClustering_mixed = NA,
        ..tableWeights_mixed = NA,
        ..plotCentrality_mixed = NA,
        ..plotClustering_mixed = NA,
        ..plotNetwork_mixed = NA,
        ..layoutAlgorithm_mixed = NA,
        ..showLabels_mixed = NA,
        ..plotWidth_mixed = NA,
        ..plotHeight_mixed = NA)
)

networkanalysisResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "networkanalysisResults",
    inherit = jmvcore::Group,
    active = list(
        instructions_net = function() private$.items[["instructions_net"]],
        summary_net = function() private$.items[["summary_net"]],
        centrality_net = function() private$.items[["centrality_net"]],
        clustering_net = function() private$.items[["clustering_net"]],
        weights_net = function() private$.items[["weights_net"]],
        centralityPlot_net = function() private$.items[["centralityPlot_net"]],
        clusteringPlot_net = function() private$.items[["clusteringPlot_net"]],
        networkPlot_net = function() private$.items[["networkPlot_net"]],
        instructions_mixed = function() private$.items[["instructions_mixed"]],
        summary_mixed = function() private$.items[["summary_mixed"]],
        centrality_mixed = function() private$.items[["centrality_mixed"]],
        clustering_mixed = function() private$.items[["clustering_mixed"]],
        weights_mixed = function() private$.items[["weights_mixed"]],
        centralityPlot_mixed = function() private$.items[["centralityPlot_mixed"]],
        clusteringPlot_mixed = function() private$.items[["clusteringPlot_mixed"]],
        networkPlot_mixed = function() private$.items[["networkPlot_mixed"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Network Analysis")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="instructions_net",
                title=" ",
                visible="(mode == 'continuous')"))
            self$add(jmvcore::Table$new(
                options=options,
                name="summary_net",
                title="Network Summary",
                visible="(mode == 'continuous')",
                refs=list(
                    "bootnet"),
                clearWith=list(
                    "vars_net",
                    "estimator_net",
                    "corMethod_net",
                    "groupVar_net"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(groupVar_net)"),
                    list(
                        `name`="nodes", 
                        `title`="Nodes", 
                        `type`="integer"),
                    list(
                        `name`="edges", 
                        `title`="Edges (Non-zero)", 
                        `type`="text"),
                    list(
                        `name`="sparsity", 
                        `title`="Sparsity", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="centrality_net",
                title="Centrality Measures",
                visible="(mode == 'continuous' && tableCentrality_net)",
                refs=list(
                    "bootnet",
                    "qgraph"),
                clearWith=list(
                    "vars_net",
                    "estimator_net",
                    "corMethod_net",
                    "groupVar_net"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(groupVar_net)"),
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text", 
                        `format`="string"),
                    list(
                        `name`="strength", 
                        `title`="Strength", 
                        `type`="number"),
                    list(
                        `name`="closeness", 
                        `title`="Closeness", 
                        `type`="number"),
                    list(
                        `name`="betweenness", 
                        `title`="Betweenness", 
                        `type`="number"),
                    list(
                        `name`="expectedInfluence", 
                        `title`="Expected Influence", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="clustering_net",
                title="Clustering Measures per Variable",
                visible="(mode == 'continuous' && tableClustering_net)",
                refs=list(
                    "bootnet",
                    "qgraph",
                    "igraph"),
                clearWith=list(
                    "vars_net",
                    "estimator_net",
                    "corMethod_net",
                    "groupVar_net"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(groupVar_net)"),
                    list(
                        `name`="node", 
                        `title`="Variable", 
                        `type`="text", 
                        `format`="string"),
                    list(
                        `name`="Barrat", 
                        `title`="Barrat", 
                        `type`="number"),
                    list(
                        `name`="Onnela", 
                        `title`="Onnela", 
                        `type`="number"),
                    list(
                        `name`="WS", 
                        `title`="WS", 
                        `type`="number"),
                    list(
                        `name`="Zhang", 
                        `title`="Zhang", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="weights_net",
                title="Weights (Adjacency Matrix)",
                visible="(mode == 'continuous' && tableWeights_net)",
                clearWith=list(
                    "vars_net",
                    "estimator_net",
                    "corMethod_net",
                    "groupVar_net"),
                columns=list(
                    list(
                        `name`="node", 
                        `title`="", 
                        `type`="text", 
                        `format`="string"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="centralityPlot_net",
                title="Centrality Plot",
                requiresData=TRUE,
                visible="(mode == 'continuous' && plotCentrality_net)",
                renderFun=".plotCentrality_net",
                refs=list(
                    "bootnet",
                    "qgraph",
                    "ggplot2"),
                clearWith=list(
                    "vars_net",
                    "estimator_net",
                    "corMethod_net",
                    "groupVar_net",
                    "nodeGroupVar_net")))
            self$add(jmvcore::Image$new(
                options=options,
                name="clusteringPlot_net",
                title="Clustering Plot",
                requiresData=TRUE,
                visible="(mode == 'continuous' && plotClustering_net)",
                renderFun=".plotClustering_net",
                refs=list(
                    "bootnet",
                    "qgraph",
                    "ggplot2",
                    "igraph"),
                clearWith=list(
                    "vars_net",
                    "estimator_net",
                    "corMethod_net",
                    "groupVar_net",
                    "nodeGroupVar_net")))
            self$add(jmvcore::Image$new(
                options=options,
                name="networkPlot_net",
                title="Network Plot",
                requiresData=TRUE,
                visible="(mode == 'continuous' && plotNetwork_net)",
                renderFun=".plotNetwork_net",
                refs=list(
                    "bootnet",
                    "qgraph"),
                clearWith=list(
                    "vars_net",
                    "estimator_net",
                    "corMethod_net",
                    "layoutAlgorithm_net",
                    "showLabels_net",
                    "plotWidth_net",
                    "plotHeight_net",
                    "groupVar_net",
                    "nodeGroupVar_net")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="instructions_mixed",
                title=" ",
                visible="(mode == 'mixed')"))
            self$add(jmvcore::Table$new(
                options=options,
                name="summary_mixed",
                title="Network Summary",
                visible="(mode == 'mixed')",
                refs=list(
                    "mgm"),
                clearWith=list(
                    "varsCont_mixed",
                    "varsCat_mixed",
                    "varsCount_mixed",
                    "groupVar_mixed",
                    "nodeGroupVar_mixed",
                    "lambdaSelMethod_mixed",
                    "kFolds_mixed",
                    "lambdaGam_mixed",
                    "ruleReg_mixed"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(groupVar_mixed)"),
                    list(
                        `name`="nodes", 
                        `title`="Nodes", 
                        `type`="integer"),
                    list(
                        `name`="edges", 
                        `title`="Edges (Non-zero)", 
                        `type`="text"),
                    list(
                        `name`="sparsity", 
                        `title`="Sparsity", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="centrality_mixed",
                title="Centrality Measures",
                visible="(mode == 'mixed' && tableCentrality_mixed)",
                refs=list(
                    "mgm",
                    "qgraph"),
                clearWith=list(
                    "varsCont_mixed",
                    "varsCat_mixed",
                    "varsCount_mixed",
                    "groupVar_mixed",
                    "nodeGroupVar_mixed",
                    "lambdaSelMethod_mixed",
                    "kFolds_mixed",
                    "lambdaGam_mixed",
                    "ruleReg_mixed"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(groupVar_mixed)"),
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text", 
                        `format`="string"),
                    list(
                        `name`="strength", 
                        `title`="Strength", 
                        `type`="number"),
                    list(
                        `name`="closeness", 
                        `title`="Closeness", 
                        `type`="number"),
                    list(
                        `name`="betweenness", 
                        `title`="Betweenness", 
                        `type`="number"),
                    list(
                        `name`="expectedInfluence", 
                        `title`="Expected Influence", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="clustering_mixed",
                title="Clustering Measures per Variable",
                visible="(mode == 'mixed' && tableClustering_mixed)",
                refs=list(
                    "mgm",
                    "qgraph",
                    "igraph"),
                clearWith=list(
                    "varsCont_mixed",
                    "varsCat_mixed",
                    "varsCount_mixed",
                    "groupVar_mixed",
                    "nodeGroupVar_mixed",
                    "lambdaSelMethod_mixed",
                    "kFolds_mixed",
                    "lambdaGam_mixed",
                    "ruleReg_mixed"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(groupVar_mixed)"),
                    list(
                        `name`="node", 
                        `title`="Variable", 
                        `type`="text", 
                        `format`="string"),
                    list(
                        `name`="Barrat", 
                        `title`="Barrat", 
                        `type`="number"),
                    list(
                        `name`="Onnela", 
                        `title`="Onnela", 
                        `type`="number"),
                    list(
                        `name`="WS", 
                        `title`="WS", 
                        `type`="number"),
                    list(
                        `name`="Zhang", 
                        `title`="Zhang", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="weights_mixed",
                title="Weights (Adjacency Matrix)",
                visible="(mode == 'mixed' && tableWeights_mixed)",
                refs=list(
                    "mgm"),
                clearWith=list(
                    "varsCont_mixed",
                    "varsCat_mixed",
                    "varsCount_mixed",
                    "groupVar_mixed",
                    "nodeGroupVar_mixed",
                    "lambdaSelMethod_mixed",
                    "kFolds_mixed",
                    "lambdaGam_mixed",
                    "ruleReg_mixed"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(groupVar_mixed)"),
                    list(
                        `name`="rowname", 
                        `title`="", 
                        `type`="text", 
                        `format`="string"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="centralityPlot_mixed",
                title="Centrality Plot",
                requiresData=TRUE,
                visible="(mode == 'mixed' && plotCentrality_mixed)",
                renderFun=".plotCentrality_mixed",
                refs=list(
                    "mgm",
                    "qgraph",
                    "ggplot2",
                    "reshape2",
                    "gtools",
                    "dplyr"),
                clearWith=list(
                    "varsCont_mixed",
                    "varsCat_mixed",
                    "varsCount_mixed",
                    "groupVar_mixed",
                    "nodeGroupVar_mixed",
                    "lambdaSelMethod_mixed",
                    "kFolds_mixed",
                    "lambdaGam_mixed",
                    "ruleReg_mixed")))
            self$add(jmvcore::Image$new(
                options=options,
                name="clusteringPlot_mixed",
                title="Clustering Plot",
                requiresData=TRUE,
                visible="(mode == 'mixed' && plotClustering_mixed)",
                renderFun=".plotClustering_mixed",
                refs=list(
                    "mgm",
                    "qgraph",
                    "igraph",
                    "ggplot2",
                    "reshape2",
                    "gtools",
                    "dplyr"),
                clearWith=list(
                    "varsCont_mixed",
                    "varsCat_mixed",
                    "varsCount_mixed",
                    "groupVar_mixed",
                    "nodeGroupVar_mixed",
                    "lambdaSelMethod_mixed",
                    "kFolds_mixed",
                    "lambdaGam_mixed",
                    "ruleReg_mixed")))
            self$add(jmvcore::Image$new(
                options=options,
                name="networkPlot_mixed",
                title="Network Plot",
                requiresData=TRUE,
                visible="(mode == 'mixed' && plotNetwork_mixed)",
                renderFun=".plotNetwork_mixed",
                refs=list(
                    "mgm",
                    "qgraph"),
                clearWith=list(
                    "varsCont_mixed",
                    "varsCat_mixed",
                    "varsCount_mixed",
                    "groupVar_mixed",
                    "nodeGroupVar_mixed",
                    "lambdaSelMethod_mixed",
                    "kFolds_mixed",
                    "lambdaGam_mixed",
                    "ruleReg_mixed",
                    "layoutAlgorithm_mixed",
                    "showLabels_mixed",
                    "plotWidth_mixed",
                    "plotHeight_mixed")))}))

networkanalysisBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "networkanalysisBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BSS",
                name = "networkanalysis",
                version = c(1,0,0),
                options = options,
                results = networkanalysisResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Network analysis
#'
#' 
#' @param data .
#' @param mode .
#' @param vars_net .
#' @param groupVar_net .
#' @param nodeGroupVar_net .
#' @param estimator_net .
#' @param corMethod_net .
#' @param tableCentrality_net .
#' @param tableClustering_net .
#' @param tableWeights_net .
#' @param plotCentrality_net .
#' @param plotClustering_net .
#' @param plotNetwork_net .
#' @param layoutAlgorithm_net .
#' @param showLabels_net .
#' @param plotWidth_net .
#' @param plotHeight_net .
#' @param varsCont_mixed .
#' @param varsCat_mixed .
#' @param varsCount_mixed .
#' @param groupVar_mixed .
#' @param nodeGroupVar_mixed .
#' @param lambdaSelMethod_mixed .
#' @param kFolds_mixed .
#' @param lambdaGam_mixed .
#' @param ruleReg_mixed .
#' @param tableCentrality_mixed .
#' @param tableClustering_mixed .
#' @param tableWeights_mixed .
#' @param plotCentrality_mixed .
#' @param plotClustering_mixed .
#' @param plotNetwork_mixed .
#' @param layoutAlgorithm_mixed .
#' @param showLabels_mixed .
#' @param plotWidth_mixed .
#' @param plotHeight_mixed .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions_net} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$summary_net} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$centrality_net} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$clustering_net} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$weights_net} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$centralityPlot_net} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$clusteringPlot_net} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$networkPlot_net} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$instructions_mixed} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$summary_mixed} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$centrality_mixed} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$clustering_mixed} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$weights_mixed} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$centralityPlot_mixed} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$clusteringPlot_mixed} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$networkPlot_mixed} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summary_net$asDF}
#'
#' \code{as.data.frame(results$summary_net)}
#'
#' @export
networkanalysis <- function(
    data,
    mode = "continuous",
    vars_net,
    groupVar_net = NULL,
    nodeGroupVar_net = NULL,
    estimator_net = "EBICglasso",
    corMethod_net = "auto",
    tableCentrality_net = TRUE,
    tableClustering_net = FALSE,
    tableWeights_net = FALSE,
    plotCentrality_net = FALSE,
    plotClustering_net = FALSE,
    plotNetwork_net = FALSE,
    layoutAlgorithm_net = "spring",
    showLabels_net = TRUE,
    plotWidth_net = 500,
    plotHeight_net = 500,
    varsCont_mixed = NULL,
    varsCat_mixed = NULL,
    varsCount_mixed = NULL,
    groupVar_mixed = NULL,
    nodeGroupVar_mixed = NULL,
    lambdaSelMethod_mixed = "EBIC",
    kFolds_mixed = 3,
    lambdaGam_mixed = 0.5,
    ruleReg_mixed = "AND",
    tableCentrality_mixed = TRUE,
    tableClustering_mixed = FALSE,
    tableWeights_mixed = FALSE,
    plotCentrality_mixed = FALSE,
    plotClustering_mixed = FALSE,
    plotNetwork_mixed = TRUE,
    layoutAlgorithm_mixed = "spring",
    showLabels_mixed = TRUE,
    plotWidth_mixed = 500,
    plotHeight_mixed = 500) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("networkanalysis requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars_net)) vars_net <- jmvcore::resolveQuo(jmvcore::enquo(vars_net))
    if ( ! missing(groupVar_net)) groupVar_net <- jmvcore::resolveQuo(jmvcore::enquo(groupVar_net))
    if ( ! missing(nodeGroupVar_net)) nodeGroupVar_net <- jmvcore::resolveQuo(jmvcore::enquo(nodeGroupVar_net))
    if ( ! missing(varsCont_mixed)) varsCont_mixed <- jmvcore::resolveQuo(jmvcore::enquo(varsCont_mixed))
    if ( ! missing(varsCat_mixed)) varsCat_mixed <- jmvcore::resolveQuo(jmvcore::enquo(varsCat_mixed))
    if ( ! missing(varsCount_mixed)) varsCount_mixed <- jmvcore::resolveQuo(jmvcore::enquo(varsCount_mixed))
    if ( ! missing(groupVar_mixed)) groupVar_mixed <- jmvcore::resolveQuo(jmvcore::enquo(groupVar_mixed))
    if ( ! missing(nodeGroupVar_mixed)) nodeGroupVar_mixed <- jmvcore::resolveQuo(jmvcore::enquo(nodeGroupVar_mixed))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars_net), vars_net, NULL),
            `if`( ! missing(groupVar_net), groupVar_net, NULL),
            `if`( ! missing(nodeGroupVar_net), nodeGroupVar_net, NULL),
            `if`( ! missing(varsCont_mixed), varsCont_mixed, NULL),
            `if`( ! missing(varsCat_mixed), varsCat_mixed, NULL),
            `if`( ! missing(varsCount_mixed), varsCount_mixed, NULL),
            `if`( ! missing(groupVar_mixed), groupVar_mixed, NULL),
            `if`( ! missing(nodeGroupVar_mixed), nodeGroupVar_mixed, NULL))

    for (v in groupVar_net) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in varsCat_mixed) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in groupVar_mixed) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- networkanalysisOptions$new(
        mode = mode,
        vars_net = vars_net,
        groupVar_net = groupVar_net,
        nodeGroupVar_net = nodeGroupVar_net,
        estimator_net = estimator_net,
        corMethod_net = corMethod_net,
        tableCentrality_net = tableCentrality_net,
        tableClustering_net = tableClustering_net,
        tableWeights_net = tableWeights_net,
        plotCentrality_net = plotCentrality_net,
        plotClustering_net = plotClustering_net,
        plotNetwork_net = plotNetwork_net,
        layoutAlgorithm_net = layoutAlgorithm_net,
        showLabels_net = showLabels_net,
        plotWidth_net = plotWidth_net,
        plotHeight_net = plotHeight_net,
        varsCont_mixed = varsCont_mixed,
        varsCat_mixed = varsCat_mixed,
        varsCount_mixed = varsCount_mixed,
        groupVar_mixed = groupVar_mixed,
        nodeGroupVar_mixed = nodeGroupVar_mixed,
        lambdaSelMethod_mixed = lambdaSelMethod_mixed,
        kFolds_mixed = kFolds_mixed,
        lambdaGam_mixed = lambdaGam_mixed,
        ruleReg_mixed = ruleReg_mixed,
        tableCentrality_mixed = tableCentrality_mixed,
        tableClustering_mixed = tableClustering_mixed,
        tableWeights_mixed = tableWeights_mixed,
        plotCentrality_mixed = plotCentrality_mixed,
        plotClustering_mixed = plotClustering_mixed,
        plotNetwork_mixed = plotNetwork_mixed,
        layoutAlgorithm_mixed = layoutAlgorithm_mixed,
        showLabels_mixed = showLabels_mixed,
        plotWidth_mixed = plotWidth_mixed,
        plotHeight_mixed = plotHeight_mixed)

    analysis <- networkanalysisClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

