
# This file is automatically generated, you probably don't want to edit this

outlierDetectionOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "outlierDetectionOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            iqr15 = FALSE,
            iqr22 = FALSE,
            iqr30 = FALSE,
            dispBox = TRUE, ...) {

            super$initialize(
                package="BSS",
                name="outlierDetection",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..group <- jmvcore::OptionVariables$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..iqr15 <- jmvcore::OptionBool$new(
                "iqr15",
                iqr15,
                default=FALSE)
            private$..iqr22 <- jmvcore::OptionBool$new(
                "iqr22",
                iqr22,
                default=FALSE)
            private$..iqr30 <- jmvcore::OptionBool$new(
                "iqr30",
                iqr30,
                default=FALSE)
            private$..dispBox <- jmvcore::OptionBool$new(
                "dispBox",
                dispBox,
                default=TRUE)

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..iqr15)
            self$.addOption(private$..iqr22)
            self$.addOption(private$..iqr30)
            self$.addOption(private$..dispBox)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        iqr15 = function() private$..iqr15$value,
        iqr22 = function() private$..iqr22$value,
        iqr30 = function() private$..iqr30$value,
        dispBox = function() private$..dispBox$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..iqr15 = NA,
        ..iqr22 = NA,
        ..iqr30 = NA,
        ..dispBox = NA)
)

outlierDetectionResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "outlierDetectionResults",
    inherit = jmvcore::Group,
    active = list(
        outlierTable = function() private$.items[["outlierTable"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Outlier Detection Results")
            self$add(jmvcore::Table$new(
                options=options,
                name="outlierTable",
                title="Outliers Summary",
                rows="(vars)",
                visible="(iqr15 || iqr22 || iqr30)",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="group_level", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="lowerFence_1.5", 
                        `title`="Lower Fence (1.5 IQR)", 
                        `type`="number", 
                        `visible`="(iqr15)"),
                    list(
                        `name`="upperFence_1.5", 
                        `title`="Upper Fence (1.5 IQR)", 
                        `type`="number", 
                        `visible`="(iqr15)"),
                    list(
                        `name`="lowerFence_2.2", 
                        `title`="Lower Fence (2.2 IQR)", 
                        `type`="number", 
                        `visible`="(iqr22)"),
                    list(
                        `name`="upperFence_2.2", 
                        `title`="Upper Fence (2.2 IQR)", 
                        `type`="number", 
                        `visible`="(iqr22)"),
                    list(
                        `name`="lowerFence_3.0", 
                        `title`="Lower Fence (3.0 IQR)", 
                        `type`="number", 
                        `visible`="(iqr30)"),
                    list(
                        `name`="upperFence_3.0", 
                        `title`="Upper Fence (3.0 IQR)", 
                        `type`="number", 
                        `visible`="(iqr30)"),
                    list(
                        `name`="numOutliers_1.5", 
                        `title`="Outliers (1.5 IQR)", 
                        `type`="integer", 
                        `visible`="(iqr15)"),
                    list(
                        `name`="numOutliers_2.2", 
                        `title`="Outliers (2.2 IQR)", 
                        `type`="integer", 
                        `visible`="(iqr22)"),
                    list(
                        `name`="numOutliers_3.0", 
                        `title`="Outliers (3.0 IQR)", 
                        `type`="integer", 
                        `visible`="(iqr30)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Boxplot with Outliers",
                width=500,
                height=400,
                renderFun=".plot",
                visible="(dispBox)"))}))

outlierDetectionBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "outlierDetectionBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BSS",
                name = "outlierDetection",
                version = c(1,0,0),
                options = options,
                results = outlierDetectionResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Outlier Detection
#'
#' 
#' @param data .
#' @param vars .
#' @param group .
#' @param iqr15 .
#' @param iqr22 .
#' @param iqr30 .
#' @param dispBox .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$outlierTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$outlierTable$asDF}
#'
#' \code{as.data.frame(results$outlierTable)}
#'
#' @export
outlierDetection <- function(
    data,
    vars,
    group,
    iqr15 = FALSE,
    iqr22 = FALSE,
    iqr30 = FALSE,
    dispBox = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("outlierDetection requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- outlierDetectionOptions$new(
        vars = vars,
        group = group,
        iqr15 = iqr15,
        iqr22 = iqr22,
        iqr30 = iqr30,
        dispBox = dispBox)

    analysis <- outlierDetectionClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

