
# This file is automatically generated, you probably don't want to edit this

outliersOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "outliersOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mode = "iqr",
            var_dixon = NULL,
            group_dixon = NULL,
            alpha_dixon = "alpha05",
            treatment_dixon = "none",
            dispBox_dixon = FALSE,
            vars_modz = NULL,
            group_modz = NULL,
            threshold_modz = "t35",
            treatment_modz = "none",
            trimPercent_modz = 5,
            dispBox_modz = FALSE,
            vars_iqr = NULL,
            group_iqr = NULL,
            iqrMultiplier_iqr = "iqr15",
            treatment_iqr = "none",
            trimPercent_iqr = 5,
            dispBox_iqr = TRUE, ...) {

            super$initialize(
                package="BSS",
                name="outliers",
                requiresData=TRUE,
                ...)

            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "dixon",
                    "modz",
                    "iqr"),
                default="iqr")
            private$..var_dixon <- jmvcore::OptionVariable$new(
                "var_dixon",
                var_dixon,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group_dixon <- jmvcore::OptionVariables$new(
                "group_dixon",
                group_dixon,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..alpha_dixon <- jmvcore::OptionList$new(
                "alpha_dixon",
                alpha_dixon,
                options=list(
                    "alpha10",
                    "alpha05",
                    "alpha01"),
                default="alpha05")
            private$..treatment_dixon <- jmvcore::OptionList$new(
                "treatment_dixon",
                treatment_dixon,
                options=list(
                    "none",
                    "trim_asym",
                    "win_valid"),
                default="none")
            private$..dispBox_dixon <- jmvcore::OptionBool$new(
                "dispBox_dixon",
                dispBox_dixon,
                default=FALSE)
            private$..treatedData_dixon <- jmvcore::OptionOutput$new(
                "treatedData_dixon")
            private$..vars_modz <- jmvcore::OptionVariables$new(
                "vars_modz",
                vars_modz,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group_modz <- jmvcore::OptionVariables$new(
                "group_modz",
                group_modz,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..threshold_modz <- jmvcore::OptionList$new(
                "threshold_modz",
                threshold_modz,
                options=list(
                    "t25",
                    "t30",
                    "t35",
                    "t40"),
                default="t35")
            private$..treatment_modz <- jmvcore::OptionList$new(
                "treatment_modz",
                treatment_modz,
                options=list(
                    "none",
                    "trim_asym",
                    "trim_sym",
                    "win_valid",
                    "win_fence"),
                default="none")
            private$..trimPercent_modz <- jmvcore::OptionNumber$new(
                "trimPercent_modz",
                trimPercent_modz,
                default=5,
                min=1,
                max=49)
            private$..dispBox_modz <- jmvcore::OptionBool$new(
                "dispBox_modz",
                dispBox_modz,
                default=FALSE)
            private$..treatedData_modz <- jmvcore::OptionOutput$new(
                "treatedData_modz")
            private$..vars_iqr <- jmvcore::OptionVariables$new(
                "vars_iqr",
                vars_iqr,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group_iqr <- jmvcore::OptionVariables$new(
                "group_iqr",
                group_iqr,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..iqrMultiplier_iqr <- jmvcore::OptionList$new(
                "iqrMultiplier_iqr",
                iqrMultiplier_iqr,
                options=list(
                    "iqr15",
                    "iqr22",
                    "iqr30"),
                default="iqr15")
            private$..treatment_iqr <- jmvcore::OptionList$new(
                "treatment_iqr",
                treatment_iqr,
                options=list(
                    "none",
                    "trim_asym",
                    "trim_sym",
                    "win_valid",
                    "win_fence"),
                default="none")
            private$..trimPercent_iqr <- jmvcore::OptionNumber$new(
                "trimPercent_iqr",
                trimPercent_iqr,
                default=5,
                min=1,
                max=49)
            private$..dispBox_iqr <- jmvcore::OptionBool$new(
                "dispBox_iqr",
                dispBox_iqr,
                default=TRUE)
            private$..treatedData_iqr <- jmvcore::OptionOutput$new(
                "treatedData_iqr")

            self$.addOption(private$..mode)
            self$.addOption(private$..var_dixon)
            self$.addOption(private$..group_dixon)
            self$.addOption(private$..alpha_dixon)
            self$.addOption(private$..treatment_dixon)
            self$.addOption(private$..dispBox_dixon)
            self$.addOption(private$..treatedData_dixon)
            self$.addOption(private$..vars_modz)
            self$.addOption(private$..group_modz)
            self$.addOption(private$..threshold_modz)
            self$.addOption(private$..treatment_modz)
            self$.addOption(private$..trimPercent_modz)
            self$.addOption(private$..dispBox_modz)
            self$.addOption(private$..treatedData_modz)
            self$.addOption(private$..vars_iqr)
            self$.addOption(private$..group_iqr)
            self$.addOption(private$..iqrMultiplier_iqr)
            self$.addOption(private$..treatment_iqr)
            self$.addOption(private$..trimPercent_iqr)
            self$.addOption(private$..dispBox_iqr)
            self$.addOption(private$..treatedData_iqr)
        }),
    active = list(
        mode = function() private$..mode$value,
        var_dixon = function() private$..var_dixon$value,
        group_dixon = function() private$..group_dixon$value,
        alpha_dixon = function() private$..alpha_dixon$value,
        treatment_dixon = function() private$..treatment_dixon$value,
        dispBox_dixon = function() private$..dispBox_dixon$value,
        treatedData_dixon = function() private$..treatedData_dixon$value,
        vars_modz = function() private$..vars_modz$value,
        group_modz = function() private$..group_modz$value,
        threshold_modz = function() private$..threshold_modz$value,
        treatment_modz = function() private$..treatment_modz$value,
        trimPercent_modz = function() private$..trimPercent_modz$value,
        dispBox_modz = function() private$..dispBox_modz$value,
        treatedData_modz = function() private$..treatedData_modz$value,
        vars_iqr = function() private$..vars_iqr$value,
        group_iqr = function() private$..group_iqr$value,
        iqrMultiplier_iqr = function() private$..iqrMultiplier_iqr$value,
        treatment_iqr = function() private$..treatment_iqr$value,
        trimPercent_iqr = function() private$..trimPercent_iqr$value,
        dispBox_iqr = function() private$..dispBox_iqr$value,
        treatedData_iqr = function() private$..treatedData_iqr$value),
    private = list(
        ..mode = NA,
        ..var_dixon = NA,
        ..group_dixon = NA,
        ..alpha_dixon = NA,
        ..treatment_dixon = NA,
        ..dispBox_dixon = NA,
        ..treatedData_dixon = NA,
        ..vars_modz = NA,
        ..group_modz = NA,
        ..threshold_modz = NA,
        ..treatment_modz = NA,
        ..trimPercent_modz = NA,
        ..dispBox_modz = NA,
        ..treatedData_modz = NA,
        ..vars_iqr = NA,
        ..group_iqr = NA,
        ..iqrMultiplier_iqr = NA,
        ..treatment_iqr = NA,
        ..trimPercent_iqr = NA,
        ..dispBox_iqr = NA,
        ..treatedData_iqr = NA)
)

outliersResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "outliersResults",
    inherit = jmvcore::Group,
    active = list(
        dixonInfo = function() private$.items[["dixonInfo"]],
        dixonTable = function() private$.items[["dixonTable"]],
        dixonOutlierList = function() private$.items[["dixonOutlierList"]],
        dixonPlot = function() private$.items[["dixonPlot"]],
        treatedData_dixon = function() private$.items[["treatedData_dixon"]],
        modzInfo = function() private$.items[["modzInfo"]],
        modzTable = function() private$.items[["modzTable"]],
        modzOutlierList = function() private$.items[["modzOutlierList"]],
        modzPlot = function() private$.items[["modzPlot"]],
        treatedData_modz = function() private$.items[["treatedData_modz"]],
        iqrInfo = function() private$.items[["iqrInfo"]],
        iqrTable = function() private$.items[["iqrTable"]],
        iqrPlot = function() private$.items[["iqrPlot"]],
        treatedData_iqr = function() private$.items[["treatedData_iqr"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Outlier Detection and Treatment Results")
            self$add(jmvcore::Html$new(
                options=options,
                name="dixonInfo",
                title="About Dixon's Q Test",
                visible="(mode == 'dixon')"))
            self$add(jmvcore::Table$new(
                options=options,
                name="dixonTable",
                title="Dixon's Q Test Results",
                visible="(mode == 'dixon')",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="group_level", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="outlier_value", 
                        `title`="Outlier Value", 
                        `type`="number"),
                    list(
                        `name`="outlier_side", 
                        `title`="Side", 
                        `type`="text"),
                    list(
                        `name`="q_statistic", 
                        `title`="Q Statistic", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="q_critical", 
                        `title`="Q Critical", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="significant", 
                        `title`="Outlier Detected", 
                        `type`="text"),
                    list(
                        `name`="treatmentApplied", 
                        `title`="Treatment Applied", 
                        `type`="text", 
                        `visible`="(treatment_dixon != 'none')"),
                    list(
                        `name`="modifiedN", 
                        `title`="Valid N (After Treatment)", 
                        `type`="integer", 
                        `visible`="(treatment_dixon != 'none')"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="dixonOutlierList",
                title="Identified Outliers (Dixon's Q Test)",
                visible="(mode == 'dixon')",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="group_level", 
                        `title`="Group", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="rowNumber", 
                        `title`="Row", 
                        `type`="integer"),
                    list(
                        `name`="outlier_value", 
                        `title`="Value", 
                        `type`="number"),
                    list(
                        `name`="outlier_side", 
                        `title`="Side", 
                        `type`="text"),
                    list(
                        `name`="q_statistic", 
                        `title`="Q Statistic", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="dixonPlot",
                title="Dixon's Q Test Boxplot",
                width=500,
                height=400,
                renderFun=".plot",
                visible="(mode == 'dixon' && dispBox_dixon)",
                refs=list(
                    "ggplot2")))
            self$add(jmvcore::Output$new(
                options=options,
                name="treatedData_dixon",
                title="Treated Variable (Dixon)",
                initInRun=TRUE,
                clearWith=list(
                    "var_dixon",
                    "group_dixon",
                    "alpha_dixon",
                    "treatment_dixon")))
            self$add(jmvcore::Html$new(
                options=options,
                name="modzInfo",
                title="About Modified Z-Score Method",
                visible="(mode == 'modz')"))
            self$add(jmvcore::Table$new(
                options=options,
                name="modzTable",
                title="Modified Z-Score Outliers Summary",
                visible="(mode == 'modz')",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="group_level", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="lowerThreshold", 
                        `title`="Lower Threshold", 
                        `type`="number"),
                    list(
                        `name`="upperThreshold", 
                        `title`="Upper Threshold", 
                        `type`="number"),
                    list(
                        `name`="numOutliers", 
                        `title`="Outliers Detected", 
                        `type`="integer"),
                    list(
                        `name`="treatmentApplied", 
                        `title`="Treatment Applied", 
                        `type`="text", 
                        `visible`="(treatment_modz != 'none')"),
                    list(
                        `name`="modifiedN", 
                        `title`="Valid N (After Treatment)", 
                        `type`="integer", 
                        `visible`="(treatment_modz != 'none')"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="modzOutlierList",
                title="Identified Outliers (Modified Z-Score)",
                visible="(mode == 'modz')",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="group_level", 
                        `title`="Group", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="rowNumber", 
                        `title`="Row", 
                        `type`="integer"),
                    list(
                        `name`="modifiedZ", 
                        `title`="Modified Z-Score", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="modzPlot",
                title="Modified Z-Score Boxplot",
                width=500,
                height=400,
                renderFun=".plot",
                visible="(mode == 'modz' && dispBox_modz)",
                refs=list(
                    "ggplot2",
                    "gridExtra")))
            self$add(jmvcore::Output$new(
                options=options,
                name="treatedData_modz",
                title="Treated Variables (Modified Z)",
                initInRun=TRUE,
                clearWith=list(
                    "vars_modz",
                    "group_modz",
                    "threshold_modz",
                    "treatment_modz",
                    "trimPercent_modz")))
            self$add(jmvcore::Html$new(
                options=options,
                name="iqrInfo",
                title="About IQR Method",
                visible="(mode == 'iqr')"))
            self$add(jmvcore::Table$new(
                options=options,
                name="iqrTable",
                title="IQR Outliers Summary",
                visible="(mode == 'iqr')",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="group_level", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="lowerFence", 
                        `title`="Lower Fence", 
                        `type`="number"),
                    list(
                        `name`="upperFence", 
                        `title`="Upper Fence", 
                        `type`="number"),
                    list(
                        `name`="numOutliers", 
                        `title`="Outliers Detected", 
                        `type`="integer"),
                    list(
                        `name`="treatmentApplied", 
                        `title`="Treatment Applied", 
                        `type`="text", 
                        `visible`="(treatment_iqr != 'none')"),
                    list(
                        `name`="modifiedN", 
                        `title`="Valid N (After Treatment)", 
                        `type`="integer", 
                        `visible`="(treatment_iqr != 'none')"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="iqrPlot",
                title="IQR Method Boxplot",
                width=500,
                height=400,
                renderFun=".plot",
                visible="(mode == 'iqr' && dispBox_iqr)",
                refs=list(
                    "ggplot2",
                    "gridExtra")))
            self$add(jmvcore::Output$new(
                options=options,
                name="treatedData_iqr",
                title="Treated Variables (IQR)",
                initInRun=TRUE,
                clearWith=list(
                    "vars_iqr",
                    "group_iqr",
                    "iqrMultiplier_iqr",
                    "treatment_iqr",
                    "trimPercent_iqr")))}))

outliersBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "outliersBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BSS",
                name = "outliers",
                version = c(1,0,0),
                options = options,
                results = outliersResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Outliers detection and treatment
#'
#' 
#' @param data .
#' @param mode .
#' @param var_dixon .
#' @param group_dixon .
#' @param alpha_dixon .
#' @param treatment_dixon .
#' @param dispBox_dixon .
#' @param vars_modz .
#' @param group_modz .
#' @param threshold_modz .
#' @param treatment_modz .
#' @param trimPercent_modz .
#' @param dispBox_modz .
#' @param vars_iqr .
#' @param group_iqr .
#' @param iqrMultiplier_iqr .
#' @param treatment_iqr .
#' @param trimPercent_iqr .
#' @param dispBox_iqr .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$dixonInfo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$dixonTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dixonOutlierList} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dixonPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$treatedData_dixon} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$modzInfo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$modzTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$modzOutlierList} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$modzPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$treatedData_modz} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$iqrInfo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$iqrTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$iqrPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$treatedData_iqr} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$dixonTable$asDF}
#'
#' \code{as.data.frame(results$dixonTable)}
#'
#' @export
outliers <- function(
    data,
    mode = "iqr",
    var_dixon,
    group_dixon,
    alpha_dixon = "alpha05",
    treatment_dixon = "none",
    dispBox_dixon = FALSE,
    vars_modz,
    group_modz,
    threshold_modz = "t35",
    treatment_modz = "none",
    trimPercent_modz = 5,
    dispBox_modz = FALSE,
    vars_iqr,
    group_iqr,
    iqrMultiplier_iqr = "iqr15",
    treatment_iqr = "none",
    trimPercent_iqr = 5,
    dispBox_iqr = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("outliers requires jmvcore to be installed (restart may be required)")

    if ( ! missing(var_dixon)) var_dixon <- jmvcore::resolveQuo(jmvcore::enquo(var_dixon))
    if ( ! missing(group_dixon)) group_dixon <- jmvcore::resolveQuo(jmvcore::enquo(group_dixon))
    if ( ! missing(vars_modz)) vars_modz <- jmvcore::resolveQuo(jmvcore::enquo(vars_modz))
    if ( ! missing(group_modz)) group_modz <- jmvcore::resolveQuo(jmvcore::enquo(group_modz))
    if ( ! missing(vars_iqr)) vars_iqr <- jmvcore::resolveQuo(jmvcore::enquo(vars_iqr))
    if ( ! missing(group_iqr)) group_iqr <- jmvcore::resolveQuo(jmvcore::enquo(group_iqr))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(var_dixon), var_dixon, NULL),
            `if`( ! missing(group_dixon), group_dixon, NULL),
            `if`( ! missing(vars_modz), vars_modz, NULL),
            `if`( ! missing(group_modz), group_modz, NULL),
            `if`( ! missing(vars_iqr), vars_iqr, NULL),
            `if`( ! missing(group_iqr), group_iqr, NULL))

    for (v in group_dixon) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in group_modz) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in group_iqr) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- outliersOptions$new(
        mode = mode,
        var_dixon = var_dixon,
        group_dixon = group_dixon,
        alpha_dixon = alpha_dixon,
        treatment_dixon = treatment_dixon,
        dispBox_dixon = dispBox_dixon,
        vars_modz = vars_modz,
        group_modz = group_modz,
        threshold_modz = threshold_modz,
        treatment_modz = treatment_modz,
        trimPercent_modz = trimPercent_modz,
        dispBox_modz = dispBox_modz,
        vars_iqr = vars_iqr,
        group_iqr = group_iqr,
        iqrMultiplier_iqr = iqrMultiplier_iqr,
        treatment_iqr = treatment_iqr,
        trimPercent_iqr = trimPercent_iqr,
        dispBox_iqr = dispBox_iqr)

    analysis <- outliersClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

