
# This file is automatically generated, you probably don't want to edit this

resourceEquationSampleSizeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "resourceEquationSampleSizeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            design = "Design 1 (One-way ANOVA)",
            nGroups = 2,
            nMeasures = 0,
            sacrifice = FALSE, ...) {

            super$initialize(
                package="BSS",
                name="resourceEquationSampleSize",
                requiresData=FALSE,
                ...)

            private$..design <- jmvcore::OptionList$new(
                "design",
                design,
                options=list(
                    "Design 1 (One-way ANOVA)",
                    "Design 2 (Repeated Measures)",
                    "Design 3 (Mixed ANOVA)"),
                default="Design 1 (One-way ANOVA)")
            private$..nGroups <- jmvcore::OptionInteger$new(
                "nGroups",
                nGroups,
                default=2)
            private$..nMeasures <- jmvcore::OptionInteger$new(
                "nMeasures",
                nMeasures,
                default=0)
            private$..sacrifice <- jmvcore::OptionBool$new(
                "sacrifice",
                sacrifice,
                default=FALSE)

            self$.addOption(private$..design)
            self$.addOption(private$..nGroups)
            self$.addOption(private$..nMeasures)
            self$.addOption(private$..sacrifice)
        }),
    active = list(
        design = function() private$..design$value,
        nGroups = function() private$..nGroups$value,
        nMeasures = function() private$..nMeasures$value,
        sacrifice = function() private$..sacrifice$value),
    private = list(
        ..design = NA,
        ..nGroups = NA,
        ..nMeasures = NA,
        ..sacrifice = NA)
)

resourceEquationSampleSizeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "resourceEquationSampleSizeResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        sampleSizeTable = function() private$.items[["sampleSizeTable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Resource Equation Sample Size Calculation")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Resource Equation Sample Size Calculation"))
            self$add(jmvcore::Table$new(
                options=options,
                name="sampleSizeTable",
                title="Sample Size Calculation Results",
                rows="(design)",
                visible=TRUE,
                columns=list(
                    list(
                        `name`="design", 
                        `title`="Design Type", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="nGroups", 
                        `title`="Number of Groups (k)", 
                        `type`="integer", 
                        `visible`="(design != \"Design 2 (Repeated Measures)\")"),
                    list(
                        `name`="nMeasures", 
                        `title`="Number of Repeated Measures (r)", 
                        `type`="integer", 
                        `visible`="(design != \"Design 1 (One-way ANOVA)\")"),
                    list(
                        `name`="sacrifice", 
                        `title`="Animals Sacrificed", 
                        `type`="text", 
                        `visible`="(design != \"Design 1 (One-way ANOVA)\")"),
                    list(
                        `name`="minN", 
                        `title`="Minimum Sample Size per Group", 
                        `type`="integer", 
                        `visible`=TRUE),
                    list(
                        `name`="maxN", 
                        `title`="Maximum Sample Size per Group", 
                        `type`="integer", 
                        `visible`=TRUE),
                    list(
                        `name`="minTotal", 
                        `title`="Minimum Total Sample Size", 
                        `type`="integer", 
                        `visible`=TRUE),
                    list(
                        `name`="maxTotal", 
                        `title`="Maximum Total Sample Size", 
                        `type`="integer", 
                        `visible`=TRUE))))}))

resourceEquationSampleSizeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "resourceEquationSampleSizeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BSS",
                name = "resourceEquationSampleSize",
                version = c(0,0,1),
                options = options,
                results = resourceEquationSampleSizeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Animals design
#'
#' 
#' @param design .
#' @param nGroups .
#' @param nMeasures .
#' @param sacrifice .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$sampleSizeTable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$sampleSizeTable$asDF}
#'
#' \code{as.data.frame(results$sampleSizeTable)}
#'
#' @export
resourceEquationSampleSize <- function(
    design = "Design 1 (One-way ANOVA)",
    nGroups = 2,
    nMeasures = 0,
    sacrifice = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("resourceEquationSampleSize requires jmvcore to be installed (restart may be required)")


    options <- resourceEquationSampleSizeOptions$new(
        design = design,
        nGroups = nGroups,
        nMeasures = nMeasures,
        sacrifice = sacrifice)

    analysis <- resourceEquationSampleSizeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

