
# This file is automatically generated, you probably don't want to edit this

samplesizeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "samplesizeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mode = "finite",
            method_finite = "Slovin",
            population_size_finite = 1000,
            confidence_level_finite = 95,
            margin_error_finite = 5,
            population_proportion_finite = 0.5,
            design_animals = "Design 1 (One-way ANOVA)",
            nGroups_animals = 2,
            nMeasures_animals = 0,
            sacrifice_animals = FALSE, ...) {

            super$initialize(
                package="BSS",
                name="samplesize",
                requiresData=FALSE,
                ...)

            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "finite",
                    "animals"),
                default="finite")
            private$..method_finite <- jmvcore::OptionList$new(
                "method_finite",
                method_finite,
                options=list(
                    "Cochran",
                    "Slovin"),
                default="Slovin")
            private$..population_size_finite <- jmvcore::OptionInteger$new(
                "population_size_finite",
                population_size_finite,
                default=1000)
            private$..confidence_level_finite <- jmvcore::OptionNumber$new(
                "confidence_level_finite",
                confidence_level_finite,
                default=95)
            private$..margin_error_finite <- jmvcore::OptionNumber$new(
                "margin_error_finite",
                margin_error_finite,
                default=5)
            private$..population_proportion_finite <- jmvcore::OptionNumber$new(
                "population_proportion_finite",
                population_proportion_finite,
                default=0.5)
            private$..design_animals <- jmvcore::OptionList$new(
                "design_animals",
                design_animals,
                options=list(
                    "Design 1 (One-way ANOVA)",
                    "Design 2 (Repeated Measures)",
                    "Design 3 (Mixed ANOVA)"),
                default="Design 1 (One-way ANOVA)")
            private$..nGroups_animals <- jmvcore::OptionInteger$new(
                "nGroups_animals",
                nGroups_animals,
                default=2)
            private$..nMeasures_animals <- jmvcore::OptionInteger$new(
                "nMeasures_animals",
                nMeasures_animals,
                default=0)
            private$..sacrifice_animals <- jmvcore::OptionBool$new(
                "sacrifice_animals",
                sacrifice_animals,
                default=FALSE)

            self$.addOption(private$..mode)
            self$.addOption(private$..method_finite)
            self$.addOption(private$..population_size_finite)
            self$.addOption(private$..confidence_level_finite)
            self$.addOption(private$..margin_error_finite)
            self$.addOption(private$..population_proportion_finite)
            self$.addOption(private$..design_animals)
            self$.addOption(private$..nGroups_animals)
            self$.addOption(private$..nMeasures_animals)
            self$.addOption(private$..sacrifice_animals)
        }),
    active = list(
        mode = function() private$..mode$value,
        method_finite = function() private$..method_finite$value,
        population_size_finite = function() private$..population_size_finite$value,
        confidence_level_finite = function() private$..confidence_level_finite$value,
        margin_error_finite = function() private$..margin_error_finite$value,
        population_proportion_finite = function() private$..population_proportion_finite$value,
        design_animals = function() private$..design_animals$value,
        nGroups_animals = function() private$..nGroups_animals$value,
        nMeasures_animals = function() private$..nMeasures_animals$value,
        sacrifice_animals = function() private$..sacrifice_animals$value),
    private = list(
        ..mode = NA,
        ..method_finite = NA,
        ..population_size_finite = NA,
        ..confidence_level_finite = NA,
        ..margin_error_finite = NA,
        ..population_proportion_finite = NA,
        ..design_animals = NA,
        ..nGroups_animals = NA,
        ..nMeasures_animals = NA,
        ..sacrifice_animals = NA)
)

samplesizeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "samplesizeResults",
    inherit = jmvcore::Group,
    active = list(
        text_finite = function() private$.items[["text_finite"]],
        sampleSizeTable_finite = function() private$.items[["sampleSizeTable_finite"]],
        text_animals = function() private$.items[["text_animals"]],
        sampleSizeTable_animals = function() private$.items[["sampleSizeTable_animals"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Sample size calculation")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text_finite",
                title="Finite Population Sample Size Calculation",
                visible="(mode == 'finite')"))
            self$add(jmvcore::Table$new(
                options=options,
                name="sampleSizeTable_finite",
                title="Sample Size Calculation Results",
                rows=1,
                visible="(mode == 'finite')",
                columns=list(
                    list(
                        `name`="method", 
                        `title`="Method", 
                        `type`="text"),
                    list(
                        `name`="population_size", 
                        `title`="Population Size (N)", 
                        `type`="integer"),
                    list(
                        `name`="confidence_level", 
                        `title`="Confidence Level (%)", 
                        `type`="number"),
                    list(
                        `name`="margin_error", 
                        `title`="Margin of Error (%)", 
                        `type`="number"),
                    list(
                        `name`="population_proportion", 
                        `title`="Population Proportion (p)", 
                        `type`="number", 
                        `visible`="(method_finite == \"Cochran\")"),
                    list(
                        `name`="sample_size", 
                        `title`="Sample Size (n)", 
                        `type`="integer"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text_animals",
                title="Resource Equation Sample Size Calculation",
                visible="(mode == 'animals')"))
            self$add(jmvcore::Table$new(
                options=options,
                name="sampleSizeTable_animals",
                title="Sample Size Calculation Results (Resource Equation)",
                visible="(mode == 'animals')",
                columns=list(
                    list(
                        `name`="parameter", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))}))

samplesizeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "samplesizeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BSS",
                name = "samplesize",
                version = c(1,0,0),
                options = options,
                results = samplesizeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Sample size calculation
#'
#' 
#' @param mode .
#' @param method_finite .
#' @param population_size_finite .
#' @param confidence_level_finite .
#' @param margin_error_finite .
#' @param population_proportion_finite .
#' @param design_animals .
#' @param nGroups_animals .
#' @param nMeasures_animals .
#' @param sacrifice_animals .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text_finite} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$sampleSizeTable_finite} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$text_animals} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$sampleSizeTable_animals} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$sampleSizeTable_finite$asDF}
#'
#' \code{as.data.frame(results$sampleSizeTable_finite)}
#'
#' @export
samplesize <- function(
    mode = "finite",
    method_finite = "Slovin",
    population_size_finite = 1000,
    confidence_level_finite = 95,
    margin_error_finite = 5,
    population_proportion_finite = 0.5,
    design_animals = "Design 1 (One-way ANOVA)",
    nGroups_animals = 2,
    nMeasures_animals = 0,
    sacrifice_animals = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("samplesize requires jmvcore to be installed (restart may be required)")


    options <- samplesizeOptions$new(
        mode = mode,
        method_finite = method_finite,
        population_size_finite = population_size_finite,
        confidence_level_finite = confidence_level_finite,
        margin_error_finite = margin_error_finite,
        population_proportion_finite = population_proportion_finite,
        design_animals = design_animals,
        nGroups_animals = nGroups_animals,
        nMeasures_animals = nMeasures_animals,
        sacrifice_animals = sacrifice_animals)

    analysis <- samplesizeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

